### ISSUE TITLE
Reorganize ExploreASL structure

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#1040]
### Description

A few script names developed historically and are not really useful anymore. Keeping everything short and simple has some benefits. I'd recommend to do the tasks below together with the **2.0.0** release. The major release gives us the chance to organize a bit better. Feel free to comment on the proposed changes.

### Tasks

- [ ] Task 1: Rename `ExploreASL_Master` to `ExploreASL` and get rid of the previous `ExploreASL` wrapper, since the existing `ExploreASL_Master` is already cleaned up nicely.
- [ ] Task 2: Rename `ExploreASL_ImportMaster` to `ExploreASL_Import`.
- [ ] Task 3: Rename `ExploreASL_ProcessMaster` to `ExploreASL_Process`.
- [ ] Task 4: Move the templates (`DataParTemplate.json`, `DataParTemplate.md`) to a tutorials or templates directory.
- [ ] Task 5: Reorganize the functions directory (move `...adm...` to an `Administration` sub-directory etc. and put `Development` there, too)

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Reorganize the ExploreASL structure, rename essential scripts, etc.
