### ISSUE TITLE
Restructure the `Population` directory

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#1048]
### Description

Restructure the `Population` directory, all qCBF & qCBF masked images could go into a directory called CerebralBloodFlow to make it more human readable, all rc1T1 images could go into a directory called Segmentations, ... It's nice to do something like this in a major release, so we don't have to worry about backwards compatibility of Population directories.

### Tasks after revamping

- [x] We skip commits of completely Task 1: give the population module wrappers the `_wrp_` prefix
- [ ] We skip commits of Task 2 completely as this will be organized differently in BIDS-derivatives. Task 2: reorganize population directories
- [ ] Task 3: refactor wrapper functions

### Release notes

Nothing. Will be restructured later according to BIDS.

**Comment by MichaelStritt** [comment]
Don't know if it's worth the effort right now. Whenever I fix one bug there's another one. Seems like the ASL and Population module are not "modular" enough. In theory I should be able to define new paths in `xASL_init_FileSystem` and `xASL_init_DefinePaths` and everything else should still work, but there are a lot of places in the Population module especially where sub-directories like the Population directory or the current subject directory are scanned for files. In addition there were rerun bugs with the bNativeSpaceAnalysis thing. It seems to be defined in the Population module but already used in the ASL module. I can't fix all of that on my own so maybe someone else also needs to have a look into this. In theory the current code creates a Population folder like this ...

```
Population
- perf
--- ASL
--- ASLCheck (rename to ASL-check)
--- ATT_Check (rename to ATT-check)
--- DICOMparameters (rename to DICOM-check)
--- M0Check (rename to M0-check)
--- M0Reg_ASL (rename to M0-registration)
--- MotionASL (rename to ASL-motion)
- anat
--- FLAIR
--- FLAIRCheck (rename to FLAIR-check)
--- T1w
--- T1Check (rename to T1-check)
--- T2Check (rename to T2-check)
--- TissueVolume (?)
- stats
--- Histograms
--- SliceGradient (?)
--- Statistics
--- StatsMaps
```

... which is a lot more like ASL-BIDS and easier to read for newcomers. Can't get it to work with all of those small bugs though. The time I can spend on ExploreASL is limited so that's it from my side for now. Maybe someone else will tackle this beast.

**Comment by HenkMutsaerts** [comment]
commit b9423af (refactoring xASL_wrp_ComputeWsCV), 0f62320 (bugfix xASL_wrp_SegmentT1w), d9b49fd (refactoring xASL_wrp_GetVolumeStatistics) are potentially useful to implement right now, as these seem to be simple code improvements that we can use.

Otherwise, this is a good idea but negated by new BIDS derivatives developments. In fact, all derivatives in the population module need to go to the subject folders per BIDS derivatives, e.g. something like:

perf/sub-001_ses-20240315_space_asl_CBF.nii.gz
perf/sub-001_ses-20240315_space_mni_CBF.nii.gz
