### ISSUE TITLE
Philips HAD4 and HAD8 import

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1059]
### Description

Import of TE and PLD for Philips HAD8 is not entirely correct. With hopefully no impact on the later quantification though.

The aslcontext.json of FME HAD4 is not with the correct order of C and L.
It should repeat C based on the nr of TEs.
Ex: HAD4 = 4 PLDs, each PLD with 8 TEs.

### Tasks

- [x] 1. HAD8 - TE is repeated for each volume despite only a single unique TE should be used. 1427e09
- [x] 2. HAD8 - Repeated TE for M0 as well. 1427e09
- [x] 3. HAD8 - PLDs are repeated correctly number of times, but they are grouped by the same PLDs instead of grouping them by Hadamard cycles. [1 1 1 2 2 2 3 3 3...] instead of [1 2 3 1 2 3 1 2 3...] ->this works for Amnah's data because it's only one repetition. So I tested it with Saima's data as well (see comment below)
- [x] 4. HAD4 - aslcontext should be: 8 x C and then Ls ( C C C C C C C C L L L L L L L L L L L L L L L L L L....), as the TEs of the first PLD should be controls, as the first PLD is the control image.
- [x] 5. Change the TotalAcquiredPairs of Hadamard to count the number of controls from the asl_context (ex: C,L,L,L,C,L,L,L to be as 2 acquired pairs) (duplicate #1042)
- [x] 6. Remove this warning from Population module 'Parms.EchoTime had multiple values' (duplicate #1054) - "'Parms.EchoTime had multiple values' (xASL_stat_GetDICOMStatistics, line 98)" 1427e09

### Release notes

Fix TE and ASLcontext in Hadamard import.

**Comment by BeatrizPadrela** [comment]
For the first task:

![image](https://user-images.githubusercontent.com/73699072/150760318-117de916-483e-4077-a715-7daa42c94f31.png)

Here it's where the pipeline reads the Echo Time (the functions open are the path inside ExploreASL of where to find this xASL_bids_Dicom2JSON)

**Comment by BeatrizPadrela** [comment]
![image](https://user-images.githubusercontent.com/73699072/150766323-bf19cea4-ad8b-45d2-a212-80e66feba3d9.png)

Here in line 150, this function does not exist yet

**Comment by BeatrizPadrela** [comment]
Note: check this ReorderTimeEncoded for Amnah's data
![image](https://user-images.githubusercontent.com/73699072/150772743-38bdc60b-588e-4039-857d-0929ad8c93b6.png)

**Comment by BeatrizPadrela** [comment]
For task 2: Repeats TE as well for M0 -> It repeats the process for second iScan. So if the TE value is not being repeated for ASL, is also not being repeated for M0:


![image](https://user-images.githubusercontent.com/73699072/150773786-41d76218-688a-4c28-b08f-1f88d6bedcb9.png)
solved!
![image](https://user-images.githubusercontent.com/73699072/150773993-03a7f5b3-fa6d-406f-a449-db6571b88e3c.png)

**Comment by BeatrizPadrela** [comment]
Task 3:
this is how HAD8 looks like. Need to correct the asl context to be C LLLLLLL, C LLLLLLL and PLDs to be [3.4, 0.6, 1, 1.4, 1.8, 2.2, 2.6, 3 and for second repetition 3.6, 0.8, 1.2, 1.6, 2, 2.4, 2.8, 3.2]

![image](https://user-images.githubusercontent.com/73699072/150786783-99a9865f-7201-4961-b6a7-31c78033f1f1.png)

**Comment by BeatrizPadrela** [comment]
Task 5: Total Acquired Pairs

@jan-petr, do we want to do this? And how? If HAD data has 4 PLDs and 2 repetitions, is it called 8 acquired pairs? why do we need this? CLLL is not a pair anymore.

**Comment by jan-petr** [comment]
> Task 5: Total Acquired Pairs
> 
> @jan-petr, do we want to do this? And how? If HAD data has 4 PLDs and 2 repetitions, is it called 8 acquired pairs? why do we need this? CLLL is not a pair anymore.

How we defined this in BIDS is that for Hadamard - CLLL is a single 'pair'. So irrespective of how many PLDs we have for Hadamard the number of pairs is equal to the number repetitions. We used the name TotalAcquiredPairs instead of Repetitions, because somebody might think that CLLL are 4 repetitions and not 1, but TotalAcquiredPairs are in fact repetitions ;)

**Comment by BeatrizPadrela** [comment]
Checking Total Acquired Pairs for every Hadamard function:
HAD4_FME: gives an error
![image](https://user-images.githubusercontent.com/73699072/151552305-5bc50dc5-022f-4d76-a13f-52aec83af4a5.png)

Already corrected in
For HAD8_FME: gives an error in nifti->BIDS:
![image](https://user-images.githubusercontent.com/73699072/151552162-ef42a77c-e183-439d-934c-1846edf6e0fe.png)
