### ISSUE TITLE
Correct JSON when splitting M0

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1062]
### Description

When splitting an M0 image from an ASL volumes, then we have to remove certain ASL tags when creating the M0.json as not all ASL tags are supposed to be there. 

Test on `Siemens_PCASL_3DGRASE_VE11C_3` and also find out why there is the `T1` tag, why the PLD and labdur tags are wrong, and why the TotalAcquiredPairs tag is wrong after import to BIDS.

When we are removing the dummyScans, we should make sure to reduce and check the TotalAcquiredPairs as well. For example in Siemens_PCASL_2DEPI_VE11C_MB_1, we have 45 pairs (including 2 dummy scans and 2 m0scans). We remove correctly both in BIDS2Legacy, but we reduce the TotalAcquired pairs only to 44 and not to 43.

### Tasks

- [x] When splitting M0 from ASL, run the BIDS function that strips the unnecessary ASL tags from the M0.json. Test on `Siemens_PCASL_3DGRASE_VE11C_3`. Check T1 tag, PLD and labdurs lengths.
- [x] Check `TotalAcquiredPairs` tag and adjust for removing dummy scans after splitting in `Siemens_PCASL_3DGRASE_VE11C_3`. and in `Siemens_PCASL_2DEPI_VE11C_MB_1`.
- [x] Check totalPairs and dummy in `xASL_bids_BIDSifyASLJSON`, `xASL_bids_parseM0`, `xASL_bids_BIDSifyASLNII`, `xASL_bids_MergeNifti`.

### How to test

- [x] Update `Siemens_PCASL_multi_VE11C_1` flavor.
- [x] RUn flavors test.
- [x] Do final flavor updates.

### Release notes

Fix TotalAcquiredPairs calculation with dummy scans.
