### ISSUE TITLE
Missing QC for DummyStructural

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1071]
### Description

Some QC images are missing when running analysis without T1 using the DummyStructural option. Or it might be the BASIL option on as well.
Specifically, ASLCheck and M0Check is empty.

**HENK** A few issues to make BASIL-CBF working equal to xASL-CBF
1. Previous FSL output should be removed
2. we save BASIL CBF in native space as CBF.nii, in standard space as CBF.nii
but we save xASL CBF in native space as CBF.nii, and in standard space as qCBF.nii. To keep BASIL stuff working similarly as the normal quantification, I suggest also saving BASIL output as qCBF.nii and standard space
3. Standard space masked version of ASL is only created for xASL, I suggest creating this also for BASIL as well.

### Tasks
- [x] 1. Remove residual BASIL output files from previous runs
- [x] 2. For BASIL: x.P.Pop_Path_CBF -> x.P.Pop_Path_qCBF
- [x] 3. Generate qCBF_masked also for BASIL

### Testing
Tested by Henk.

### Release notes
Fix standard space CBF naming for BASIL.
