### ISSUE TITLE
New category of development functions

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1073]
### Description

These functions are supposed to be used by developers to create documentation, atlases, and run other maintenance functions for xASL. But not directly used by the users.
We will use the notation `xASL_dev_FunctionName`

### Tasks

- [x] Create a folder `Functions/Development`
- [x] Add folder to init
- [x] Add folder to Documentation + crawler + pages
- [x] Add the following function: `xASL_io_ConvertNiiGz2Mat.m`
- [x] Add the following function: `/Functions/Administration/xASL_adm_DocCrawler.m`, `xASL_dev_DocInitialize.m`, and other docu functions
- [x] Check all other development/Functions etc for stuff to be moved here.

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Duplicate. Done in #1075.
