### ISSUE TITLE
Improve clarity

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1079]
### Description

Here, I list some suggestions I got when going through the newest version of ExploreASL.

### Tasks

- [ ] `/ExploreASL/Templates` is not a useful name, as the word "templates" is also used for atlas templates, so let's reserve this word for that and rename this folder (or move the json-templates elsewhere)
- [ ] `/ExploreASL/Maps/` (==`x.D.MapsDir`) only contains the folder `/ExploreASL/Maps/Templates` (==`x.D.TemplateDir`), we can simplify this by removing one folder layer. 
- [ ] `xASL_module_ASL: *_CheckASL`: `skip` should be `bSkip`
- [ ] `xASL_module_ASL:` *_CheckASL`: `result` is unused and can be deleted
- [ ] `xASL_module_ASL`: `xASL_adm_DefineASLSequence` was performed twice
- [ ] When `bRegistrationCBF` is off, no need to create a `VascularTemplate` file
- [ ] What happens if `x.modules.asl.bRegistrationContrast==0` but no `mean_control` exists? Should issue warning & skip registration

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
