### ISSUE TITLE
Revamp M0 masking & smoothing

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1080]
### Description

I propose to revamp `xASL_wrp_ProcessM0`, by removing `x.modules.asl.M0_conventionalProcessing` and create the following parameter:

* `x.modules.asl.bMaskSmoothM0` == 0 -> skips M0 masking & smoothing
* `x.modules.asl.bMaskSmoothM0` == 1 -> conventional M0 masking & smoothing
* `x.modules.asl.bMaskSmoothM0` == 2 -> ExploreASL M0 masking & smoothing

This came up when testing QASPER processing in #743, for which we want `x.modules.asl.bMaskSmoothM0` == 0 when `x.bQASPERPhantom` is true.

### Tasks

- [ ] revamp `xASL_wrp_ProcessM0` slightly, spreading the sections A) M0 registration B) M0 quantification and C) M0 masking & smoothing
- [ ] add `x.modules.asl.bMaskSmoothM0` to `DataParTemplate.md`
- [ ] Add parameter `x.modules.asl.bMaskSmoothM0`
- [ ] Default to `x.modules.asl.bMaskSmoothM0`==2
- [ ] replace `x.modules.asl.M0_conventionalProcessing` by `x.modules.asl.bMaskSmoothM0` == 1
- [ ] Change in documentation?

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
