### ISSUE TITLE
Legacy import issues

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1093]
### Description

* When `StudyID` is added as parameter to `sourceStructure.json`, this may point the import to a wrong folder.

* Settings added to the `studyPar.json` will be propagated to the `/derivatives/ExploreASL/dataPar.json` which is wrong
* If /`dataPar.json` exists (which should be renamed to `settingsPar.json`) this should be taken into account for processing settings
* we need to keep the parameters belonging to the data and the processing settings strictly separated

### Tasks

- [ ] when loading `sourceStructure.json`, and finding `studyID`, ignore this and give a warning that we ignore it
- [ ] when processing settings are detected in `studyPar.json`, ignore them and give a warning that we will ignore them
- [ ] when detecting a `dataPar.json` in import, take this in account and use settings for processing (so move this to '/derivatives/ExploreASL/') and merge field-by-field with the default `dataPar.json` created by the import

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
