### ISSUE TITLE
xASL_test_TestExploreASL wrong defaults

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1104]
### Description

`xASL_qc_TestExploreASL` was converted to `xASL_test_ExploreASL` during which the input parameter parsing was changed. It doesn't correctly return the defaults anymore. E.g., 

Related to #1105

### Tasks

- [x] default `0` should be replaced by `false`
- [x] - [ ] default `1` should be replaced by `true`
- [x] matlabpath should be defaulted `if isnumeric`, not `if isempty`
- [x] testDataUsed should be defaulted to `false` `if isempty`, this doesn't work now

### How to test

Run the following:
>> [ResultsTable] = xASL_test_TestExploreASL(TestDirOrig, TestDirDest, RunMethod, bTestSPM, [], [], [], bOverwrite, [], [], 0);

### Release notes

Nothing to release. Duplicate to #1105
