### ISSUE TITLE
Revert use of addOptional

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1105]
### Description

addOptional parsing is suboptimal for our purpose:
1. It doesn't allow customized error messages
2. It doesn't allow default values for the middle parameters

We have to revise and possibly revert the use of addOptional in the entire code.

### Tasks

- [x] Fix Testing/xASL_test_TestExploreASL.m
- [x] Fix Functions/InputOutput/xASL_io_dcm2nii.m
- [x] Fix Functions/Administration/xASL_adm_FindByRegExp.m
- [x] Fix ExploreASL_Initialize.m

### Release notes

Fixes input parameter checking at multiple locations and optimized internal variables.
