### ISSUE TITLE
Change TestDataSets repository structure to new ExploreASL BIDS data structure

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1110]
### Description

Change TestDataSets repository structure to new ExploreASL BIDS data structure

### Tasks

- [x] edit dataPar.json to the new format: subject_regexp -> dataset.subjectRegexp, Quality -> settings.Quality, DELETETEMP -> settings.DELETETEMP --> this and more done in ebc270c9b8b43cffbc5e05819bcc77c324ae33ca
- [x] Rename the dataPar.json to a correct name --> Done previously by Michael.
- [x] Move all data to the correct derivatives or rawdata structure - depending if preprocessed or not - and add ASLcontext.tsv --> New issue #1152 because we need to remove the scaleSlopes etc.
- [x] Fix all the correct BIDS names in rawdata --> will be done in #1152 
- [x] Update all ASL.jsons --> done for GE, for the rest in #1152 

### How to test

I've updated the dataPar.json, and JSONs for GE and put everything in derivatives - but the rest - full BIDS and all in rawdata, will have to be done in a next issue.

### Release notes

Move TestDataSets to derivatives and update dataPar.json.
