### ISSUE TITLE
Debugging population module for Mathijs

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#1117]
### Description

Spatial CoV sorting of ASL images is not working, currently the JPEGs are not divided into sub categories based on spatial CoV.

### Tasks

- [x] When Population modules crashes, it reports an error not recognizing the QC module
- [x] `xASL_stat_GetRegistrationStatistics` crashes if a subject doesn't have ASL QC (e.g., if subjects have missing ASL scans)
- [x] `xASL_stat_PrintStats` call the first column 'participant_id' instead of 'SUBJECT'
- [x] `xASL_qc_SortBySpatialCoV` needs fixing for a subjectsession list vs only subjectlist

### Release notes
Fix Spatial CoV sorting of ASL images.
