### ISSUE TITLE
FEAST quantification warnings

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1118]
### Description

Allow dual compartment quantification option for FEAST. Currently, when dual compartment quantification is requested, this is only applied to the crushed & non-crushed CBF images separately, and FEAST only uses the single-compartment model when calculating the ATT times. We might just want to give a warning when a dual compartment quantification was used but FEAST works with single compartment quantification.

Perhaps a bit too much for now to use FEAST with the dual compartment model, which the original FEAST paper also doesn't do.

Likewise, we probably want a warning when CBF was quantified with BASIL (even though this now outputs a separate CBF NIfTI); as it may not do this in the future.

### Tasks

- [x] Print in `xASL_quant_FEAST` that we assume the white paper single compartment quantification model for obtaining the FEAST ATT
- [x] `xASL_quant_FEAST`: Add warning if `x.Q.bUseBasilQuantification==0`
- [x] `xASL_quant_FEAST`: Add warning if `x.Q.nCompartments~=1`
- [x] `xASL_wrp_Quantify`: Add warning if 'x.Q.nCompartments` wasn't 1 or 2

### How to test

Run single PreDiva dataset

### Release notes

Improve FEAST quantification warnings
