### ISSUE TITLE
Import Module should support multiple contexts

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#1129]
### Description

More complicated datasets often contain scanner switches or related alterations. At baseline they might have been acquired on, say, a Siemens scanner without an M0 with a control-label sequence and at a followup visit they might have been scanned on a GE scanner with a deltam + M0 output. At the current time, ExploreASL's Import module can't handle this scenario: a user would have to split up subjects/visits to different `sourcedata` directories, run the Import module separately for each, and then try to join them back together. 

Key things we agreed upon (I am just trying to summarize, please correct me if I'm wrong)

1. Single studyPar.json in root directory that defines everything
2. studyPar.json will be created manually or in a GUI, but it will be 'applied' inside ExploreASL. The GUI will help to create it, but it won't be using or interpreting it. Reason: We keep comfort for user, but we allow editing it and have this option available for all users.
3. Because of 2, this studyPar.json will be used in the NII2BIDS phase (not in DICOM2NII phase).
4. Because of 3, we won't have the original folder and filenames available to assist in this multi-study process. Instead, we will have to work with the aliases assigned by sourceStructure.json.
5. Because of 4, we will be able to work with 'subject name', 'session (a.k.a. visit)', 'run (a.k.a. session) name'
6. We will have either a normal and plain studyPar.json - then everything is applied to all sessions.
7. We have ImportContexts keyword with an array of nested lists.
8. We go through the list starting from the top and going to the bottom.
9. Top-most entry is the most general one applied to all (it doesn't need to have, but it could have conditions).
10. All entries below need to have conditions, if conditions are fulfilled, then the previous entries are overwritten - i.e. the last entry in the list has the highest priority.
11. Conditions contain SubjectList, SessionList, VisitList (just ideas, the names can change). At least one of these has to be provided for each but the first entry. These three conditions are connected by AND - i.e. all provided conditions for an entry have to be fulfilled. However, within each list, they are connected by OR.
12. SubjectList - an array of strings of subject names - could be full names or regexp.
13. SessionList, VisitList - array of numbers - corresponding to the aliases given in sourcestructure.json (I know that the sourcestructure.json is really an archaic stuff and we have to get rid of it - but we can't do everything at once ;)).

I think that this is a comprehensive definition of how to do things.
So with your example:
![FolderExample](https://user-images.githubusercontent.com/29886537/190461911-f4df25ae-f257-4eee-979f-3a975b9a4105.png)

I would use the following sourceStructure.json:
`"folderHierarchy": ["^(sub088Siemens3DwithM0|sub128Philips2DnoM0)$", "^(Baseline|Followup)$", "^(ASL|M0|T1)$"],`
`"tokenOrdering":[1,2,0,3],`
`"tokenVisitAliases":"Baseline","1","Followup","2"],`
`"tokenSessionAliases":["",""],`
`"tokenScanAliases":["^ASL$","ASL4D","^T1w$","T1w","^M0$","M0"],`

Then, taking your example from above, lets go for the following studyPar.json. Note that I included some stuff in the general definition, just so that we have it ;) Also - lets say that most subjects on baseline were Siemens PASL with PLD 1.8 with M0. But there was one subject without M0. And all followups were PCASLs done on GE. This should be applicable also to the example you give above, but I have used something that would work with the provided file-structure screenshot. The studyPar.json would look like (note that I deleted some tags just to make it a bit shorter and easier to read):
`  "ImportContexts": [`
`    {  `
`      "ASLContext": "label, control",`
`      "M0": true,`
`      "Manufacturer": "Siemens",`
`      "LabelingType": "PASL",`
`      "PostLabelingDelay": 1.8,`
`    },`
`    {  `
`      "SubjectList": ["sub128Philips2DnoM0","^sub.*withoutM0$"]`
`      "M0": false,`
`    },`
`    {  `
`      "VisitList": [2]`
`      "ASLContext": "deltam",`
`      "M0": true,`
`      "Manufacturer": "GE",`
`      "LabelingType": "PCASL",`
`      "PostLabelingDelay": 1.525,`
`    },`
`    {  `
`      "SubjectList": ["subWithPhilipsFollowup"]`
`      "VisitList": [2]`
`      "ASLContext": "control,label",`
`      "M0": true,`
`      "Manufacturer": "Philips",`
`      "LabelingType": "PCASL",`
`      "PostLabelingDelay": 1.800,`
`    },`
  ]
}`

Few things to note on this scheme, which will make it easy to use:
1. regexp in lists.
2. we have inheritance, so we can easily redefine just a single parameter when needed.
3. If played smartly with a correct priority, we don't have to list all cases, but we just rewrite entire group of subjects or sessions, or both.
4. The last one is an exceptional subject that was scanned normally on session 1, but on session 2, he received Philips. So we have to redefine all tags again - and it has to be the last in the list.

To implement it on ExploreASL side (not the GUI side), we will only need to do the following:
1. In NII2BIDS, we will not read studyPar.json normally (that checks for backwards compatability - but with a normal json_read).
2. Then when processing every subject (at each run), we will not use the studyPar.json, but we will run a function that goes through this studyPar.json and selects the correct subset. Then we run the backwards compatability function.
3. The resulting specific studyPar will be passed upon a subfunction.
4. When going to a following subject, we go to step 2.
### Tasks
- [x] Read enhanced study par and correctly check all subsets. Fix in xASL_io_ReadDataPar.
- [x] Function that takes subject/visit/session and solves the priority to construct the correct specific studyPar.
- [x] fix xASL_wrp_NII2BIDS_Subject for new studyPar version
- [x] fix xASL_wrp_NII2BIDS for new StudyPar version
- [x] Use the specific studyPar - inside xASL_imp_NII2BIDS_Run, because here it should be already fixed xASL_imp_NII2BIDS_RunPerf.m
- [x] Make sure that it works as well here - xASL_imp_DCM2NII_Subject_SortASLVolumes.m - no worries, we don't distinguish between anything else than TimeEncoded and TimeEncodedFME, so we should make it a single param only. We have to use ImportContext instead of a simple studyPar. Can we extract aliases in this case? We can from here x.overview.subject_001.visit_001. We should run the priority function anyway.
- [x] And here - xASL_imp_BasicParameterChecks.m
- [x] Update Documentation and explain.
- [x] Write UT function for the prioritization.
- [x] Test with flavor Siemens_PCASL_3DGRASE_VD13A_DEBBIE - merged HAD4 and HAD8
- [x] Merge flavors Siemens_PCASL_2DEPI_VE11C_MB_1 and 2 and their respective 3DGraSE counterparts.
- [x] verify: ExploreASL_Import.m
- [x] verify: xASL_bids_MergeStudyPar.m
- [x] verify: xASL_imp_NII2BIDS_Subject_DefineM0Type.m
- [x] verify: xASL_imp_DCM2NII_Subject_SortASLVolumes.m
- [x] verify: xASL_imp_BasicParameterChecks.m
- [x] Rename ImportContexts to StudyPars
- [x] Rename AliasHierarchy to SubjectRegexp, VisitRegexp, SessionRegexp.
- [x] Fix Documentation
- [x] Fix issue with RegExp field deleting.

### Release notes

StudyPar supports multi-parameter definitions for import of multi-sequence datasets.

**Comment by HenkMutsaerts** [comment]
@jan-petr why don't we do the same as BIDS does. 
Option 1: inheritance principole: So the parent studyPar.json etc are valid for everything unless overruled by a sidecar studyPar.json. 
Option 2: participants.tsv where you tabulate subjects, visits, sessions, and add the settings that differentiate.

Option 2 is probably easiest for both us and the users. It would replace studyPar.json (perhaps with a grace period for backward compatibility)

**Comment by jan-petr** [comment]
The inheritance principle is a good idea - but that can easily work with the proposition of Maurice: we will have a general schema, and then for defined subset, we will either overwrite a parameter or keep as is  by default.

Regarding option 2: I would definitively argue against any pre-historical concepts that BIDS uses. Tabulating might work for automatically generated and processed data. Forcing users to list things in a table is just a horrible practice. I already hate the striking inefficiency of ASLcontext.tsv - the worst possible option they could have chosen. As you say - disadvantage is being prone to errors, horrible inefficiency, etc. It is in no way user-friendly and you don't have an overview ;)

**Comment by MauricePasternak** [comment]
I lean towards Option 1 for a couple of reasons:

1) From what the BIDS docs imply, participants.tsv is more appropriate for metadata (participant age, sex, etc.)

2) For the GUI, when data is read from .json files, value types are guarenteed to be accurate. When reading in spreadsheets, some error-prone logic must be added. For example, is a cell with contents: `9001` supposed to be a number or a string? Besides, all the error-checking and operativity of the GUI is based on JSON-like structure already.

3) participants.tsv is a nightmare for documenting complex fields (i.e. arrays, nested JSON objects). Might make things harder down the line. 

---

So, as I understand it with this example:

![Untitled](https://user-images.githubusercontent.com/57411571/182886935-8d8bfc9c-5cc7-490c-b6c8-2bf2bbd386d6.png)

Subjects 8 & 9 would have their own import parameters. Subject 10 would have its own import parameters. And Subjects 11 & 12 would fall under the global set of import parameters.

^ Assuming the above is correct, then from my end I can glob for additional parameter files and have one general form for the global studyPar.json:

![ImportModule__DefineExtraPars](https://user-images.githubusercontent.com/57411571/182895322-282a19da-5dd0-44da-8283-6260fefe9ccc.png)

...followed by similar sub-forms below it populated by any detected additional parameter files. Of course, users will be able to add/remove these subforms as needed. When proceeding to the next step (Run ExploreASL Import Module), StudyPar.json and all the additional parameter files are deleted, then re-created as needed.

**Comment by jan-petr** [comment]
Fully agree with the arguments above for Option 1 - in-line with my own thoughts.

Regarding the directory structure - Do we want to have separate files in sub-directories. Or rather a nested main file that includes sub-jsons describing groups of subjects this applies to? While separate files is in principle fine for me, it might be a bit more complex to handle, with not so much added values. I'd be happier to have everything in a single nested JSON - that way, it will be easier to change parameters for all sessions or all visits at once. So more flexibility, without added user or developer complexity. 
What do you think @MauricePasternak ?

**Comment by MauricePasternak** [comment]
One file is actually more convenient for me too (no more need for globbing & merging jsons). I was just working with the assumption that you were thinking of it looking exactly like BIDS, with multiple files. Indeed, I prefer one file with an array field for multiple contexts.

**Comment by jan-petr** [comment]
I meant nested, not array field. So essentially like you had it, but instead of multiple files in each directory, these would be nested inside a single file.

The leaves would look like BIDS, but the nested structure would be ours. Because anyway BIDS doesn't have anything like that.

Having a single file than a file for each dir would save us the hassle of copying files everywhere.

**Comment by MauricePasternak** [comment]
Okay, gave this some thinking and I'd like to hear your thoughts on the attached revision of a modified `studyPar` that I can generate by GUI input. Attached a picture of the folder structure for context (pun not intended).
 
[SubjectAndVisitMulti.zip](https://github.com/ExploreASL/ExploreASL/files/9420564/SubjectAndVisitMulti.zip)

So what I'm thinking is the prospect of combining sourceStructure.json and studyPar.json into the later. `folderHierarchy` will then be distributed across the different `ImportContexts` (let me know if a different key name is better/more accurate). As in the current case, `folderHierarchy` remains an array of regexes.

In terms of how my GUI orders the contexts: the first is the "global" context that targets everything after sourcedata, with the exception of scans that the user specifically asked to be ignored. Every followup context then applies to only select subjects/visits/sessions/etc.

Given this, two common approaches are possible:

- Go in reverse: handle the additional contexts first and let the existence of ".status" files prevent overwriting of subjects/visits/sessions that are imported first.
- Go forward: run global first, then each followup context overwrites as necessary.

The forward option would probably be easier to implement, given that the ".status" files of the import module are purely based on subjects being completed (probably needs to be a separate issue) and therefore aren't currently reliable to when visits/sessions start getting involved.

**Pros of this setup, in my opinion:**

- Far easier to integrate into the existing ExploreASL codebase than having separate keys for Subject, Session, Visit, etc. basenames or filepaths.
- Covers pretty much most case scenarios. There is one case scenario where this system becomes tedious for the user: when they have inconsistent acquisitions. For example, consider a dataset with 3 visits per subjects where almost all of subjects have a GE scan at baseline and a Siemens one at followup1 and followup2. Except for a few subjects who were only scanned on Siemens. In such a scenario, it would be necessary for the user to group acquisitons into "grouping" folders (i.e. a folder named SiemensOnly and a folder named GEToSiemens) in order to allow the `folderHierarchy` of a particular context to have an extra array element for fine-tuned selection. To be fair, without the use of complex negative lookaheads/lookbehinds, the current `folderHierarchy` system also faces the same limitation.
- The use of `folderHierarchy` across the different contexts still allows for sharing studyPar.json files.

**Cons:**

- As per above...users with those case scenarios may find it annoying to create extra folders.
- In my honest opinion, I think regexs are powerful but too blunt of an approach. I understand the intent is to keep parameter files transferable between researchers, hence why absolute filepaths shouldn't be included (even if they offer better precision). It'd probably require too much change to the codebase but perhaps the compromise is something to consider for the future: relative filepaths (relative to the study root).

**Comment by jan-petr** [comment]
@MauricePasternak Sorry, I got a bit lost on what we agreed upon. If the last message here is an add-on to what we agreed upon or if this was the initial proposition and only afterwards we discussed it. And I can't find any other emails or notes about this. So please excuse me if am I redefining something we have agreed upon and just let me know ;)

So to sum up - see the following message, where I will try to put all things we agreed upon and please make modifs to that.

**Comment by MauricePasternak** [comment]
So, just to clarify, my previous commentary was written after our meeting where we agreed upon the general structure. We agreed that an overwrite/forward approach is easier to scale, so that's what I went with in the GUI.

I recall we both didn't like the prospect of using `SubjectList`, `SessionList`, and `VisitList`. More fields = more error-prone. It would be a lot easier if there was a single field that operated on regexp in lists, like you suggested. And since `folderHierarchy` already does this, I thought I'd move `folderHierarchy` from sourceStructure.json into the individual contexts. It will then be the field responsible for determining which folders to incorporate when running a particular context. Therefore, using the example you mentioned, the GUI would define the following `ImportContexts` field:

```json5
{
  "ImportContexts": [
    // This is the "global" context; will probably result in errors when trying to import the GE and the Philips cases; but that's okay
    {
        "FolderHierarchy": ["^(sub088Siemens3DwithM0|sub128Philips2DnoM0)$", "^(Baseline|Followup)$", "^(ASL|M0|T1)$"],
        "ASLContext": "label, control",
        "M0": true,
        "Manufacturer": "Siemens",
        "LabelingType": "PASL",
        "PostLabelingDelay": 1.8,
    },
    // This context covers the GE cases; 
    {
        "FolderHierarchy": ["^(sub088Siemens3DwithM0|sub.*withoutM0)$", "^(Followup)$", "^(.*)$"],
        "ASLContext": "deltam",
        "M0": true,
        "Manufacturer": "GE",
        "LabelingType": "PCASL",
        "PostLabelingDelay": 1.525,
    },
    // This context covers the single exceptional Philips subject
    {
        "FolderHierarchy": ["^(sub128Philips2DnoM0)$", "^(Followup)$", "^(.*)$"],
        "ASLContext": "control,label",
        "M0": true,
        "Manufacturer": "Philips",
        "LabelingType": "PCASL",
        "PostLabelingDelay": 1.800,
    }
  ]
}
```
^ Without the `//` comments, of course; they're just included for the clarification.

Besides that difference, everything else seems fine. What do you think about this point of difference?

**Comment by jan-petr** [comment]
Discussion result:
Maurice keeps folderHierarchy and does the subject splitting in GUI and will run ExploreASL multiple-times, each time running only selected subjects.
Jan will use aliasHierarchy, and does apply this inside ExploreASL.

Perhaps both approaches to be merged in the future.

**Comment by jan-petr** [comment]
I have copied the same answer to PR as well:
> 
> * We have multiple `studyParameters`, not sure where "context" comes from?
Good catch. That's because we called it ImportContexts previously. I have fixed this everywhere. [501c564](https://github.com/ExploreASL/ExploreASL/pull/1186/commits/501c564f97cc6f6da1dd7530c304c655959eab5b)

> * We create a function that parses `studyPar.json`. This provides a heads-up to the user for each aliasHierarchy, e.g.,:
>   "Note that for cases that match subject regular expression ˆsub-\d{3} session regular expression ... run regular expression, we will change the data parameters XX YY and ZZ.""

This doesn't make sense IMHO. Because this only states the basic functionality of the multi-parameter studyPar :) It doesn't make to report general warning, it makes sense to only report specific warnings to cases that are actually happening. 
So I would go with the warning you previously agreed upon: "When it reads the non-first study par, it warns "Note that for subjects XX sessions YY we're using parameter XX instead of YY"

An example of a current warning is:
`Evaluating multi-parameter studyPar for subject/visit/session: Sub1/1/2`
` For RegExp subject/visit/session //2, overwriting fields:  LabelingDuration, PostLabelingDelay, TimeEncodedMatrixSize, ASLContext,`

> * Later, we will expand this with provenance: [Import provenance #1190](https://github.com/ExploreASL/ExploreASL/issues/1190)
OK. Will check later

I agree in general with #1193, but note that we will anyway revamp the legacy structure of parameters that dataPar uses - so things might still change a bit. Anyway - I agree that we have to clean that. These things happen step-by-step - don't criticize when things are a mess, because they were a super-mess before :D
