### ISSUE TITLE
Parallelization using slurm

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1148]
### Description

For parallel processing, we simply start Matlab & ExploreASL multiple times, telling ExploreASL how many "workers" there are and which "worker" the current instance is. This then calculates which subjects to process.

See as an example [THIS script](https://github.com/ExploreASL/CustomScripts/blob/main/SABRE/ParallelProcessingSABRE_Viktory.sh)

For Flux, this needs to be slightly replaced:

### Tasks
**MAJOR**
- [x] Create a bash script with as input `iWorker` and `nWorkers` (this is used by ExploreASL to gauge which subjects should be processed). Inside this bash script, call Matlab & ExploreASL
- [x] Create a separate script that loops across the `iWorkers` and calls the bash script using the slurm command `sbatch`
**MINOR**
- [x] Correct paths
- [x] Load Matlab appropriately instead of providing the path only (also allows putting in the string `matlab`)

### How to test

Parallel run `ExploreASL('~/lood_storage/divi/Projects/ExploreASL/MSOPT', 0, 1);` with `nWorkers=10`

### Release notes

Required: summarize the changes for the release notes here

**Comment by maartenhammer** [comment]
https://github.com/ExploreASL/CustomScripts/tree/feature-%231148-slurm-parallelization/flux

In CustomScripts a new folder has been made with an example for Slurm parallelization, it uses a master script that creates a slurm instance with two environmental variables (nworkers and iworker). The worker script uses these Environmental variables and folders set up in the worker script itself to run a parallelized instance.
