### ISSUE TITLE
spm_jsonread new warning

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1159]
### Description

Spm_jsonread writes 'Warning duplicate key' without providing path tot he file or saying that this is about spm_jsonread at all.

### Tasks

- [x] Add spm_jsonread to all warnings and errors in spm_jsonread.
- [x] Compile on Windows, Linux, Mac
- [x] Add a message on reading of all JSONs at the start of the function - that is going to be helpful as invalid JSON related errors are really common among ExploreASL users.

### Release notes

Improve spm_jsonread warnings and print file path.
