### ISSUE TITLE
General bugfixing of testing - critical errors

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1161]
### Description

Various bugs are uncovered and fixed while running the full scale testing of import/processing/UT.

### Tasks

- [x] Minor fixes in xASL_test_TestExploreASL paths and variables
- [x] Fix outputs of Deface
- [x] Fix error in tsv_read - uninitialized variable ``lineNumberIncorrectLength``
- [x] Fix Flavor Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1
- [x] Fix Flavor GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1
- [x] Fix Flavor Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1

### Release notes

General bugfixing ExploreASL.

**Comment by jan-petr** [comment]
{'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing folder'        }    {'/sub-Sub1/anat'                                                        }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_FLAIR.json'                                    }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_FLAIR.nii.gz'                                  }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T1w.json'                                      }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T1w.nii.gz'                                    }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                                      }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                                    }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                                }
    {'GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1'  }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/ASL4D_Source.json'                           }
    {'GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1'  }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/ASL4D_Source.nii.gz'                         }
    {'GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1'  }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/ASL4Dcontext_Source.tsv'                     }
    {'GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1'  }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/M0.json'                                     }
    {'GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1'  }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/M0.nii.gz'                                   }
    {'GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1'  }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-001/ASL_1/ASL4D.json'          }
    {'GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1'  }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-001/ASL_1/ASL4D.nii.gz'}
    {'GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1'  }    {'Both'                }    {'Different file content'}    {'Matrix dimensions do not agree: /ExploreASL/sub-001/ASL_1/ASL4D.nii.gz'}
    {'GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1'  }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-001/ASL_1/ASL4Dcontext.tsv'    }
    {'Philips_PASL_2DEPI_5.4.1.0_ADNI3_006_S_6681_1'}    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-001/ASL_1/ASL4D.json'          }
    {'Philips_PCASL_2DEPI_PARREC_1'                 }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub01/ASL_1/ASL4D.json'        }
    {'Philips_PCASL_3DGRASE_5.6.1.1_CBFonly_1'      }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-001_1/ASL_1/ASL4D.json'        }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivativesReference'}    {'Missing folder'        }    {'/ExploreASL/temp'                                                      }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub1_1/ASL_1'                                          }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.json'                            }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.mat'                             }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                               }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                             }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'                        }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.nii.gz'                      }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'                         }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext_Source.tsv'                  }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                                  }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                                }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/FLAIR.json'                                     }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/FLAIR.nii.gz'                                   }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T1.json'                                        }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T1.nii.gz'                                      }

**Comment by jan-petr** [comment]
{'Data'                          }    {'mean_qCBF_TotalGM'}    {'median_qCBF_TotalGM'}    {'median_qCBF_DeepWM'}    {'CoV_qCBF_TotalGM'}    {'GMvol' }    {'WMvol' }    {'CSFvol'}    {'PipelineCompleted'}    {'TC_ASL_Registration'}    {'TC_M0_Registration'}
    {'GE_3Dspiral_T1prefilled_Cyst…'}    {'65.094'           }    {'52.5562'            }    {'32.2689'           }    {'0.29578'         }    {[0.6399]}    {[0.5052]}    {[0.4329]}    {[                1]}    {[             0.8998]}    {[            0.9321]}
    {'Philips_2DEPI_FEAST_Longitud…'}    {'39.5495'          }    {'27.5973'            }    {'6.6213'            }    {'0.71024'         }    {[0.5349]}    {[0.4590]}    {[0.4056]}    {[                1]}    {[             0.7291]}    {[            0.8170]}
    {'Philips_2DEPI_FLAIR_Disabled…'}    {'73.8912'          }    {'56.3172'            }    {'23.055'            }    {'0.33702'         }    {[0.5442]}    {[0.3921]}    {[0.3564]}    {[                1]}    {[             0.9195]}    {[            0.9479]}
    {'Philips_2DEPI_FLAIR_Segm_PWI…'}    {'48.7977'          }    {'43.2525'            }    {'20.1293'           }    {'0.42119'         }    {[0.6994]}    {[0.5816]}    {[0.2222]}    {[                1]}    {[             0.8130]}    {[            0.8346]}
    {'Philips_2DEPI_Lesion_NoFLAIR…'}    {'empty'            }    {'14.172'             }    {'2.9897'            }    {'0.89531'         }    {[0.7099]}    {[0.5136]}    {[0.1939]}    {[                1]}    {[             0.7593]}    {[            0.8910]}
    {'Philips_2DEPI_Segmentation_2…'}    {'45.3768'          }    {'39.6839'            }    {'10.5861'           }    {'0.32242'         }    {[0.7547]}    {[0.4862]}    {[0.1671]}    {[                1]}    {[             0.8592]}    {[            0.8105]}
    {'Philips_3DGRASE_FLAIR_M0_2nd…'}    {'34.509'           }    {'25.7327'            }    {'7.5753'            }    {'0.64092'         }    {[0.5709]}    {[0.5279]}    {[0.4220]}    {[                1]}    {[             0.8597]}    {[            0.7545]}
    {'Philips_3DGRASE_MultiSession…'}    {'33.0357'          }    {'25.0264'            }    {'9.1691'            }    {'0.43047'         }    {[0.7239]}    {[0.5520]}    {[0.3564]}    {[                1]}    {[             0.8477]}    {[            0.8952]}
    {'Siemens3DGRASE_Structural_Al…'}    {'empty'            }    {'empty'              }    {'empty'             }    {'empty'           }    {[0.5191]}    {[0.4658]}    {[0.4054]}    {[                1]}    {0×0 double           }    {0×0 double          }
    {'Siemens_2DEPI_noBsup_FLAIR_LoQ'}    {'68.6563'          }    {'51.5917'            }    {'13.8923'           }    {'0.32113'         }    {[0.6887]}    {[0.6031]}    {[0.3101]}    {[                1]}    {[             0.8726]}    {[            0.9589]}
