### ISSUE TITLE
General bugfixing of testing - minor errors

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1162]
### Description

Various bugs are uncovered and fixed while running the full scale testing of import/processing/UT - this is the second part of the task with errors not really in code, but in the testing data and scripts. This can be corrected later as it won't affect normal ExploreASL execution by the users.

### Tasks

- [x] Unzip Population/Template_6.nii before running segmentation in ``Philips_2DEPI_Segmentation_2D_T2_SPM_HiQ``
- [x] M0 Incorrectly changed from UseControlAsM0 -> Absent for Bsup == ON. This is incorrect, as also for this flavor, we can compensate for BSup and run M0 quantification. Includes these flavors: `Philips_PCASL_2DEPI_PARREC_1`, `Siemens_PASL_3DGRASE_VE11C_1`, `Siemens_PASL_3DGRASE_VE11C_2`
- [x] The following datasets have CBF only, so they should have M0 set to Absent in Flavors: `Philips_PCASL_3DGRASE_5.1.7.2_1`, 
- [x] Fix Flavor Philips_PASL_2DEPI_5.4.1.0_ADNI3_006_S_6681_1 - M0 replaced with M0Type
- [x] Fix Flavor Siemens_PCASL_3DGRASE_VB17A_multiPLD_1 - unknown issue
- [x] Rename GE flavors folder names
- [x] Should we then make M0_parms loading conditional upon ApplyQuantification(4)?
- [x] TestDataSet 10% different results ``Siemens3DGRASE_Structural_AlreadyDone_HiQ``
- [x] Add 1.9.0 Reference to ResultsReference for TestDataSetTesting 
- [x] Fix UT test of xASL_wrp_BIDS2Legacy - neither test passed - issues with dro 2.3.0, not a real error
- [x] Fix TestDataSet Philips_2DEPI_Segmentation_2 - slightly different - what parameter changed?!
- [x] Fix TestDataSet Philips_2DEPI_FLAIR_Disabled - crashes because of ApplyQuantification 0 and M0 issues
- [x] Fix UT test of xASL_ExploreASL - only test 9 failed - 'DRO 2.3.0 (Run processing starting from derivatives with dataPar.json input (outdated))'
- [x] Finish testing Flavors
- [x] Finish UT
- [x] Finish TestDataSets
- [x] If ExploreASL is initialized, it always searches for the dataset root folder, and will issue a warning if not specified

### Release notes

General bug fixing of ExploreASL.

**Comment by jan-petr** [comment]
Comment to the following commit:
1. We have to load M0_parms anyway even if ApplyQuantification(5) == 0, because ApplyQuantification(4) can be still 1.
2. If ApplyQuantification(5) == 0, then we assign M0=NaN - so we shouldn't then later complain about that ;)

**Comment by HenkMutsaerts** [comment]
> Comment to the following commit:
> 
> 1. We have to load M0_parms anyway even if ApplyQuantification(5) == 0, because ApplyQuantification(4) can be still 1.
> 2. If ApplyQuantification(5) == 0, then we assign M0=NaN - so we shouldn't then later complain about that ;)

1. Should we then make `M0_parms` loading conditional upon `ApplyQuantification(4)`?
2. I thought we would keep complaining if an M0 image exists that is empty, even if we don't use the image, but maybe not needed

**Comment by jan-petr** [comment]
> 1. Should we then make `M0_parms` loading conditional upon `ApplyQuantification(4)`?
> 2. I thought we would keep complaining if an M0 image exists that is empty, even if we don't use the image, but maybe not needed

Added these to tasks.

> 3. See also my last added task and commit

Agree. Re-running UT to check this.
