### ISSUE TITLE
xASL_adm_GzipAllFiles bug

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1164]
### Description

<img width="905" alt="image" src="https://user-images.githubusercontent.com/27774254/185466268-f39293bf-502c-48ee-a6ab-12ab91a06220.png">

This is a Linux bug:

  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.11.1.el7.x86_64
      Architecture: x86-64

On an UCL Linux server I got the following errors:

>> for: Command not found.
i: Undefined variable.
for: Command not found.
i: Undefined variable.

Within `xASL_adm_GzipAllFiles` for:
>> for i in `find * | grep -E \.nii$`; do gzip -1 -f -q -v "$i"; done'

These errors seem the consequence of using an old Linux distribution:
centOS 7 with Linux Kernel 3.10.0x (2013-2014). Apparently, this looping wasn't possible back then?

### Tasks

- [x] Address the looping for the old Linux version?
- [x] Allow catching errors for the Linux-zipping and use the slower Matlab-zipping as backup
- [x] Check also issue #1052 - is that the same problem?

### How to test

Try running `xASL_adm_GzipAllFiles`

**Comment by jan-petr** [comment]
#1159 Wasn't merged yet, because I haven't noted the SPM-changes to the readme file.

Besides, there are weird errors before launching a MEX - "for command not found".

It runs on my Linux also without JVM. There can be of course some more complex problem with compatibility, but I would say that there something wrong with Matlab in general, and not this specific MEX.

**Comment by HenkMutsaerts** [comment]
It was the Matlab version, it defaulted to Matlab 2012a ;)

But with the correct version, it still gives these errors:

>> for: Command not found.
i: Undefined variable.
for: Command not found.
i: Undefined variable.

Let me try to find tomorrow how this comes about, and add this to #1162 OK?

**Comment by jan-petr** [comment]
That still sounds like an issue with Matlab itself and not with our code.

I would check paths to Matlab and Matlab/bin. And also see if those are correctly defined in environmental variables.

So on second thought - I would investigate this, but I wouldn't add it to #1162 and I would close this issue as duplicate, as this is your local error unrelated to ExploreASL code.
