### ISSUE TITLE
GE_Premier_RX28 MS Hong Kong

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1170]
### Description

New flavor challenge!

See this branch: https://github.com/ExploreASL/FlavorDatabase/tree/bug-%231170_GE_Premier_HongKong
[BRANCH](https://github.com/ExploreASL/FlavorDatabase/tree/bug-%231170_GE_Premier_HongKong)

GE data Hong Kong has some issues, it is from a new GE Premier scanner.
The ASL deltaM & M0 are correctly concatenated in 4D. Structural module goes fine, if the wrong structural images matrix size is corrected. ASL module goes fine, if the M0 issue below is corrected.

### Tasks

- [x] Waiting for the correct `studyPar.json` settings (now I don't know the ASL protocol settings yet). JAN:No need to wait - all settings are correctly read from DICOM.
- [x] `studyPar.M0 = true` doesn't work (although this seemingly used to work with older flavors). It should apparently be `studyPar.M0Type = Included` which will set an intermediate `jsonLocal.M0 = true` in `xASL_imp_NII2BIDS_Subject_DefineM0Type`. Something went wrong here recently? Same when testing with older GE flavor release DV22.0 (`/FlavorDatabase/GE_PCASL_3Dspiral_22.0LX_1`). This leads to "M0Type":"Absent" in `rawdata` and no `m0scan` in `aslcontext.tsv`. If I change this manually to "M0Type":"Included", and replace one `deltaM` by `m0scan`. JAN: That's correct, M0 is not a ASL-BIDS parameter and thus should not be provided in studyPar.json. You should provide only ASL-BIDS compliant parameters there. Besides, m0scan and deltaM positions are correctly read from the DICOMs.

HENK: OK then please provide a warning to the user whenever DICOM fields overwrite `studyPar.json` or vice versa (this should be a general comparison function, you have that already right?

- [x] We get the following warning (also when running older GE flavor release DV22.0). JAN: Will be fixed in #342 

>> Warning: Field EchoTime in xASL structure has a value 0.0528, which is outside of the
recommended range <0.5,500> ms. 
> In xASL_bids_parms2BIDS (line 101)
  In xASL_bids_Dicom2JSON (line 632)
  In xASL_imp_DCM2NII_Subject_StoreJSON (line 38)
  In xASL_imp_DCM2NII_ConvertScan (line 172)
  In xASL_wrp_DCM2NII_Subject (line 126)
  In xASL_wrp_DCM2NII (line 45)
  In xASL_module_Import (line 147)
  In xASL_init_Iteration>runIteration (line 382)
  In xASL_init_Iteration (line 125)
  In ExploreASL_Import (line 50)
  In ExploreASL (line 91) 

- [x] The T1w and FLAIR NIfTIs are incorrectly sorted: each left/right part of the matrix is put in a 4rd dim, 
so [0.5*(X Y Z) 2] instead of [X Y Z 1]. JAN: this was reported as a dcm2nii issue already and should be solved in the new dcm2nii version - see #435 
- [x] Is #1133 slightly related? JAN: Yes, both will be fixed in #435
- [x] Anonymize this dataset. JAN: I will anonymize the DICOMs.
- [x] Add formally to flavors. JAN: Yes, added the correct JSONs and DICOMs and set everything up.
- [x] Add references to flavors (ASL). JAN: We can add this one already, as this works nicely, but we need to wait for the structural data.
- [x] Add references to flavors (structural). JAN: We need to wait for the #435 fix to have the perfect consistent flavors.
- [ ] Once done, delete the original branch in Flavors.

### How to test

[Flavor BRANCH](https://github.com/ExploreASL/FlavorDatabase/tree/bug-%231170_GE_Premier_HongKong)

### Release notes

Added a GE_RX28.0 to flavors.
