### ISSUE TITLE
Running BASIL in WSL and WSL2

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1172]
### Description

BASIL paths are not set correctly for WSL. See the issue below:

That's the input/output paths for Basil (ref. lines 40-43 in xASL_quant_Basil).
For example, the command uses a path 'C:\FSL_eASL_test\...\ASL_1\PWI4D_BasilInput.nii' instead of '/mnt/c/FSL_eASL_test/.../ASL_1/PWI4D_BasilInput.nii'. If somebody is running from Linux distribution, it should not be an issue, but for WSL, it needs some correction.

@yevap, @HenkMutsaerts  Can you please write here some examples of paths? I.e. write what is in the FSLdir and WSLdir variables and what are really the correct names to be used in the WSL call. I'll then try to find these and fix these in the code.

### Tasks

- [x] Fix paths in single-PLD and multi-PLD
- [x] Fix paths in quantify and all related scripts
- [x] Fix this also inside #927 
- [x] Yeva tests this in WSL2
- [x] Henk tests this in WSL

### Release notes

Duplicate. Problem fixed elsewhere.

**Comment by HenkMutsaerts** [comment]
This should be addressed by `xASL_fsl_RunFSL`
