### ISSUE TITLE
Merge BASIL and FABBER calls

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1181]
### Description

BASIL and Fabber calls use different functions for calling the program and to prepare arguments for it. It would be good to merge both to a single function and just have an option - BASIL/Fabber.

The function will not have BASIL or FABBER in the name, only FSL. Merging inside the function `xASL_quant_Basil`.
### Tasks

- [x] I made first commits - before continuing, make sure to check with Mathijs on what he is doing with multi-PLD and merge all issues and rebase (recreate+cherry pick) this branch
- [x] Make sure that FSL options for BASIL and FABBER are done the same way.
- [x] Check all in the `xASL_quant_BASIL` - all BASIL and FABBER names are used correctly.
- [x]     %% 2. Delete previous BASIL/Fabber output -> here the output may be separate for calculating different maps (e.g., one may want to compute Tex twice, once with CBF and ATT maps from sequence A and once from sequence B)
- [x] Synchronize config file behavior (`xASL_quant_Fabber_Options`): if output is in the config file or in the command

### Release notes

Nothing. Duplicate to #1301
