### ISSUE TITLE
Split xASL_io_ReadDataPar -> xASL_io_ReadDataPar & xASL_io_ReadStudyPar

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1193]
### Description

We require different parameters for the `studyPar` and the `dataPar`, so good to split this.

### Tasks

- [ ] the legacy option to accept `dataPar.m` and convert this to `dataPar.json` doesn't apply to the `studyPar`
- [ ] the iteration over `studyPars` doesn't apply to `dataPar`
- [ ] the legacy GROUP and LOAD parsings doesn't apply to `studyPar`
- [ ] the deprecated field check doesn't apply to `studyPar`
- [ ]  parsing the `Q` struct doesn't apply to `studyPar`
- [ ]  the conversion of strings containing numbers can be replaced for both using `xASL_str2num`
- [ ]  fixing the matlab notation `''` to the json notation `""` doesn't apply to `studyPar`
- [ ] Header explanation is outdated for both

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
