### ISSUE TITLE
Testing GE_RX28 MS HongKong

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1201]
### Description

Testing the flavor merged in #1170.

### Tasks

- [ ] `aslcontext` gives twice an `m0scan`, and `asl.nii.gz` contains 2 M0 volumes
- [ ] error:
>> xASL_Move: skip: destination exists: /Users/henk/ExploreASL/FlavorDatabase/GE_PCASL_3Dspiral_RX28.02_1/derivatives/ExploreASL/temp/Sub124/ASL_1/ASL4D_4_.nii
xASL_Move: skip: destination exists: /Users/henk/ExploreASL/FlavorDatabase/GE_PCASL_3Dspiral_RX28.02_1/derivatives/ExploreASL/temp/Sub124/ASL_1/ASL4D_4_.json

- [ ] Somehow `"ArterialSpinLabelingType": "PCASL" (`studyPar.json`) was incorrectly set to `"ArterialSpinLabelingType": "PCASL" (`ASL.json`)
- [ ] PLD should be 2025 according to the protocol PDF file but 1525 was found by conversion (`ASL.json`)?

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by jan-petr** [comment]
COMPARISON TABLE:
                         flavor                                  dataset                        name                                                   message                                    
    _________________________________________________    ________________________    __________________________    _______________________________________________________________________________

    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing folder'        }    {'/sub-Sub1/anat'                                                             }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_FLAIR.json'                                         }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_FLAIR.nii.gz'                                       }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T1w.json'                                           }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T1w.nii.gz'                                         }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                                           }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                                         }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                                     }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'         }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_run-1_m0scan.json'          }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'         }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_run-2_m0scan.json'          }
    {'Siemens_PCASL_3DGRASE_VD13D_2'                }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                                           }
    {'Siemens_PCASL_3DGRASE_VD13D_2'                }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                                         }
    {'Siemens_PCASL_3DGRASE_VD13D_2'                }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                                     }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-sub1/anat/sub-sub1_run-1_T1w.json'             }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-1_asl.json'             }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-1_m0scan.json'          }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /sub-sub1/perf/sub-sub1_run-1_m0scan.nii.gz'}
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-2_asl.json'             }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-2_m0scan.json'          }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /sub-sub1/perf/sub-sub1_run-2_m0scan.nii.gz'}
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-3_asl.json'             }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-3_m0scan.json'          }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /sub-sub1/perf/sub-sub1_run-3_m0scan.nii.gz'}
    {'GE_PCASL_2DEPI_HD23.0_1'                      }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Philips_PASL_2DEPI_5.4.0.2-LookLocker_1'      }    {'derivativesReference'}    {'Missing folder'        }    {'/ExploreASL/temp'                                                           }
    {'Philips_PASL_2DEPI_5.4.0.2-LookLocker_1'      }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.json'                                 }
    {'Philips_PASL_2DEPI_5.4.0.2-LookLocker_1'      }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.mat'                                  }
    {'Philips_PASL_2DEPI_5.4.1.0_ADNI3_006_S_6681_1'}    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-001/ASL_1/ASL4D.json'               }
    {'Philips_PCASL_2DEPI_3.2.1.1_1'                }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Philips_PCASL_2DEPI_3.2.1.1_2'                }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Philips_PCASL_2DEPI_3.2.1.1_3'                }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Philips_PCASL_2DEPI_3.2.1.1_dummyLL_1'        }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Philips_PCASL_2DEPI_3.2.1.1_dummyMultiPLD_1'  }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Philips_PCASL_2DEPI_3.2.1.1_dummyQUASAR_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Philips_PCASL_2DEPI_4.1.2.1_1'                }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Philips_PCASL_2DEPI_5.1.9.1_GMB_1'            }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub0004_1/ASL_1/ASL4D.json'         }
    {'Philips_PCASL_2DEPI_5.3.1.1_1'                }    {'derivativesReference'}    {'Missing folder'        }    {'/ExploreASL/temp'                                                           }
    {'Philips_PCASL_2DEPI_5.3.1.1_1'                }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.json'                                 }
    {'Philips_PCASL_2DEPI_5.3.1.1_1'                }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.mat'                                  }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'      }    {'derivativesReference'}    {'Missing folder'        }    {'/ExploreASL/temp'                                                           }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'      }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.json'                                 }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'      }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.mat'                                  }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivativesReference'}    {'Missing folder'        }    {'/ExploreASL/temp'                                                           }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub1_1/ASL_1'                                               }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.json'                                 }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.mat'                                  }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                    }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                                  }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'                             }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.nii.gz'                           }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'                              }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext_Source.tsv'                       }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                                       }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                                     }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/FLAIR.json'                                          }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/FLAIR.nii.gz'                                        }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T1.json'                                             }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'  }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T1.nii.gz'                                           }
    {'Siemens_PASL_3DGRASE_VD13D_1'                 }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Siemens_PCASL_2DEPI_NA_1'                     }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'            }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'         }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/M0.json'               }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'         }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_2/M0.json'               }
    {'Siemens_PCASL_3DGRASE_VD13D_2'                }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub1_1/ASL_1'                                               }
    {'Siemens_PCASL_3DGRASE_VD13D_2'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                    }
    {'Siemens_PCASL_3DGRASE_VD13D_2'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                                  }
    {'Siemens_PCASL_3DGRASE_VD13D_2'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'                              }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D.json'            }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/M0.json'               }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-sub1_1/ASL_1/M0.nii.gz'     }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_2/ASL4D.json'            }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_2/M0.json'               }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-sub1_1/ASL_2/M0.nii.gz'     }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_3/ASL4D.json'            }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_3/M0.json'               }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-sub1_1/ASL_3/M0.nii.gz'     }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'    }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/T1.json'                     }

LOGGING TABLE:
