### ISSUE TITLE
Revamp xASL_wrp_ResampleASL for single-/multi-PLD/Hadamard

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1205]
### Description

`xASL_wrp_ResampleASL` now has too many unnecessary if-statements and the option `bSavePWI4D` was ignored.

### Tasks

- [ ] Use existing input option `bSavePWI4D` (which should be defaulted to true for multi-PLD)
- [ ] Save PWI4D at a single location
- [ ] Treat single-PLD as multi-PLD with a single PLD
- [ ] Find out how to run sections 9-11 and obtain QC parameters such as tSD, tSNR, wsCV,sCoV, for multi-PLD and/or multi-TE sequences

### How to test

Should still run the same for single-PLD, multi-PLD, Hadamard

### Release notes

Required: summarize the changes for the release notes here

**Comment by HenkMutsaerts** [comment]
Was duplicate with #997
