### ISSUE TITLE
Simplify single- and multi-parameters

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1210]
### Description

Let's simplify the behavior of parameters that are often singular (i.e., a scalar) but can become plural (i.e., a vector). This means that all ASL scans are processed as multi-TE with a single TE as default, multi-PLD with a single PLD as default, etc. Are there other options? LabDur?

### Tasks

- [ ] Always multi-TE processing
- [ ] Always multi-PLD processing
- [ ] Always multi-labdur processing?

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
