### ISSUE TITLE
Harmonized warnings, booleans, etc handling at beginning ASL module

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1211]
### Description

Ensure that important warnings for boolean/settings/sequence/flavors combinations are issued at the start of the ASL module rather than somewhere in the middle of the code. This makes it clear to the user right at the start of a module, rather than in the middle of running something.

### Tasks

- [x] We move `xASL_module_ASL` section D (parsing ASL processing settings) to a `xASL_module_ASL` subfunction.
- [x] Simplify parameter for-loop
- [x] rename Number -> n; NumberPars -> nUniquePars
- [x] remove 's' from parameters (e.g. NumberEchoTime(s))
- [x] bQUantifyMultiTE and PLD -> to docu in the correct name **JAN** done e3754ca093e8915dc3676f4876a1eccc75873fa2
- [x] bQUantifyMultiTE/PLD inside x.modules.asl - fix everywhere **JAN** done e3754ca093e8915dc3676f4876a1eccc75873fa2
- [x] x.Q.bUseBasilQuantification -> x.modules.asl.bUseBasilQuantification : In code, deprecated fields, and docu. The same for other BASIL parameters. **JAN** Done in b100dadf

### Release notes

Nothing. Report with #997,
