### ISSUE TITLE
Clean dataPar documentation

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1212]
### Description

[The documentation - page datapar](https://exploreasl.github.io/Documentation/1.10.0beta/ProcessingParameters/) contains many deprecated parameters, some things are not explained, and some things are missing.

### Tasks

- [x] Add option x.modules.population,'bNativeSpaceAnalysis' to the documentation.
- [x] We should make clear examples of what should be in studyPar and dataPar.
- [x] All input parameters related to sequence should be removed from here as they should all be applied in the import. Having then here makes it confusing for the reader and they then think that they  should fill these values in dataPar.
- [x] Add datatype output - see line 212 of population module. x.S.DataTypes = {'qCBF'}; "S": {"DataTypes": ["qCBF","ATT"]} % Alternatives: 'Tex' 'ATT' 'SD' 'TT' 'M0' 'R1' 'ASL_HctCohort' 'ASL_HctCorrInd'. Improve this comment in the code and in the manual and add sCoV as well.
- [x] Update CHANGES.md

### Release notes

Improve the manual description of studyPar and dataPar.jsons

**Comment by MauricePasternak** [comment]
I hope to replicate this change in the GUI for the "Define Parameters" section. Let me know if the following list of fields to drop makes sense:

- `x.SESSIONS`
- `x.session.options`
- `x.Q.M0`
- `x.Q.BackgroundSuppressionNumberPulses`
- `x.Q.PresaturationTime`
- `x.Q.readoutDim`
- `x.Q.Vendor`
- `x.Q.Sequence`
- `x.Q.LabelingType`
- `x.Q.Initial_PLD`
- `x.Q.LabelingDuration`
- `x.Q.SliceReadoutTime`
- `x.modules.asl.M0_GMScaleFactor`
- `x.modules.asl.M0PositionInASL4D`
- `x.modules.asl.DummyScanPositionInASL4D`

**Comment by jan-petr** [comment]
There's a couple that can be only here:
> * `x.SESSIONS`
> * `x.session.options`
> * `x.modules.asl.DummyScanPositionInASL4D`
> * `x.modules.asl.M0_GMScaleFactor`

The following ones can be kept here, but should normally be defined in the import (sometimes with a slightly different name or notation):

> * `x.modules.asl.M0PositionInASL4D`
> * `x.Q.M0`
> * `x.Q.BackgroundSuppressionNumberPulses`
> * `x.Q.readoutDim`
> * `x.Q.Vendor`
> * `x.Q.Sequence`
> * `x.Q.LabelingType`
> * `x.Q.Initial_PLD`
> * `x.Q.LabelingDuration`
> * `x.Q.SliceReadoutTime`

This is a very special field and can be probably dropped now:
> * `x.Q.PresaturationTime`
