### ISSUE TITLE
Vendor-specific DICOM field list

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1215]
### Description

With anonimization, often important ASL-related fields are removed (mostly because they are in private fields). It would be good to have a list of these fields, that we can give to collaborators such that the IT guys can adapt their anonimization.

### Tasks

- [ ] Create GE list of necessary DICOM fields (that could be anonimized)
- [ ] Create Philips list of necessary DICOM fields (that could be anonimized)
- [ ] Create Siemens list of necessary DICOM fields (that could be anonimized)
- [ ] Upload these lists to BIDS or our own documentation

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
