### ISSUE TITLE
Ordering HAD4 & HAD8 volumes - import module

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#1218]
### Description

Before quantification, the volumes should be: all 8TEs for PLD1 then all 8TEs for PLD2, etc.
However, in DEBBIE LCBC scans, the acquisition was: all PLDs for TE1, all PLDs for TE2 etc.

If we don't reorder the volumes, the quantification doesn't work (creates a negative TExch map).

The PLDs vector written in rawdata's ASL.json is correct with the order of acquisition. What we need to ensure is that we reorganize them as 8TEs for PLD1 and then all 8TEs for PLD2, so [3.5x8 0.5x8 1.5x8 2.5x8] - for HAD4

Issue #1216 is labelled as duplicate but it still has code that we can use for this issue!

### Tasks for Bea to check

- [x] The problem was in DCM2NII in merging several NII+JSON - it hasn't recognized that it's a FME sequence, so it hasn't merged the NIIs. So it didn't write the TEs in the merged JSON.
- [x] Once we have the correct TE vector, then in DCM2NII, it correctly reorders it.
- [x] Then NII2BIDS step doesn't even need to reorder anything.
- [x] We only need to check if ASL module correctly identifies that the sequence is Time-encoded multi-TE. But I don't expect issues there.
- [x] And we want to add this to flavors as well (Jan will do).

### Release notes

Fix issue with Hadamard NII merging and ordering.

### BEA & HENK
* Quick & Dirty solution: Bea manually sorts them; editing the basil options text file, as this is the same for all scans per site.
* Future solution: register images to vascular template. Henk creates proximal to distal template based on MRA template & ATT template; and this proximal-distance signal gradient is then used to sort the control-label volumes. The sum(signal) of a whole control-label pair can help sorting the later phases for T1w-decay.

**Comment by jan-petr** [comment]
A few difference in flavors to deal with.
COMPARISON TABLE:
                        flavor                                 dataset                        name                                                  message                                   
    _______________________________________________    ________________________    __________________________    _____________________________________________________________________________


    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub1_1/ASL_2'                                             }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                                     }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                                   }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/ASL4D.json'                                  }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/ASL4D.nii.gz'                                }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/ASL4Dcontext.tsv'                            }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/M0.json'                                     }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/M0.nii.gz'                                   }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'          }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'}
    {'Siemens_PCASL_3DGRASE_VD13D_2'              }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub1_1/ASL_1'                                             }
    {'Siemens_PCASL_3DGRASE_VD13D_2'              }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                  }
    {'Siemens_PCASL_3DGRASE_VD13D_2'              }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                                }
    {'Siemens_PCASL_3DGRASE_VD13D_2'              }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'                            }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'  }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-sub1_1/ASL_1/ASL4D.nii.gz'}
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'  }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-sub1_1/ASL_2/ASL4D.nii.gz'}
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'  }    {'Both'                }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-sub1_1/ASL_3/ASL4D.nii.gz'}
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD'        }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                         }

**Comment by jan-petr** [comment]
@BeatrizPadrela I Fixed the errors above. But please verify that ASL4D.nii in `Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1` is now correctly imported and decoded and I will the update the reference.

**Comment by BeatrizPadrela** [comment]
Testing LCBC data -> DCM2NII stopped because of this:
![image](https://user-images.githubusercontent.com/73699072/198210995-a022234e-2ebd-4e8d-af54-6613e3aa7315.png)
