### ISSUE TITLE
PDF Report restart

### ISSUE THREAD

**Issue by maartenhammer** [ExploreASL/ExploreASL#1225]
### Description

Restart of issue #984 as to keep the PDF report generated by Maarten separate from the one created by Micheal as well as creating an issue/branch to submit changes to. 

### Tasks

- [x] Have a meeting with Bas to look at the PDF reader.
- [x] Change import of images from qc.results to manual import. 
- [x] Allow images to be added to PDFGenerator
- [x] Allow scans to be added to PDFGenerator
- [x] Allow QC values to be added to PDFGenerator
- [x] Add a rudimentory form of Block forming with automated scaling. 
- [x] Implement a function that reads participants.tsv to include patient information if relevant. 
- [x] Clean up TemplateConfig.Json
- [x] Add information about the scanner and the ASL sequence type.
- [x] Change JSON objects to a unnamed Array instead
- [x] Change filePath to absolutePath or relativePath
- [x] More Complex Example
- [x] Create Markdown Manual
- [x] Add figure titles 

### How to test

- [x] Run MakeReport with complete data
- [x] Run MakeReport with incomplete data 
- [x] Run MakeReport with incomplete Config.json
- [x] Run MakeReport with incomplete Config.json and data
- [x] For anyone trying this in the test branch, a [small manual](https://github.com/ExploreASL/ExploreASL/blob/f5bb987cd9a04ddf6e7fe2a594a38af4cee17c0d/WorkInProgress/QualityControl/PDFGenerator.md ) has been written in addition to the example. Please check it out. 
- [x] Make a follow-up issue to read new version of x.output fields. Createdin #1552 
- [x] Move manual to docs before merging.

### Release notes

New, JSON-configurable PDF report, which can be used for QC output.

**Comment by maartenhammer** [comment]
Had a Talk with Bas Jasperse about the layout an ASL report. 
Main remarks: 
- Less is more, don't include things that arent relevant
- adding information about structural module is not neccesarily required for radiologists, at most to see if segmentation is done correctly
HENK: I agree, I would make a scan-specific PDF (see also below). So an ASL report should be ASL-only, and a T1w-report would include T1w-specific QC and segmentations etc.
- While a generic report is nice, there should be an appendix with disease/studies specific information down the line. 

The layout/goal we have (so far) come can be seen [here](https://drive.google.com/file/d/1fssv4d2fsNgTBJlq3A06w-ug7_G13rUi/view?usp=sharing).

<img width="620" alt="image" src="https://user-images.githubusercontent.com/27774254/209802255-01701597-4971-4e06-9e61-27709b9f1218.png">

## Boils down to: 
(by Maarten, inline comments by Henk)

- Generic Patient information (if it exists/in clinical trails)
- Technical details of scanner settings and some quality parameters like software version
- Quality control values:
- Labeling slab/plane placement (DICOM (0018, 9250-9260 contain information for this, in BIDS the values "LabelingOrientation", "LabelingDistance" and "LabelingDuration" can be relevant for this, if possible visualize this as well.
- Motion correction
- Signal to noise
- With Multi PLD Bas' suggestion was to create a plot of average intensity of the (raw) scans at each PLD. His theory is that as the PLD's get later you can see the average intensity go up and down. This would then show that in your analysis you have included the moment when intensity (and thus blood flow) is maximal and such can accurately say that you didnt have a PLD interval that is either too short or too low, in one look. 
HENK: Nice idea! We would have to see how/if this works like you write it here; and many ASL acquisitions are single-PLD only so then this wouldn't work. Currently, we are starting with single-PLD only, only later with multi-PLD.

- With respect to "less is more" Bas' suggestion is to leave out any structural QC, my personal suggestion is to include at least a segmentation image to confirm correct wm/gm masks.
*** HENK: Good idea: I would create a separate PDF/page for T1w/FLAIR; perhaps we can create a PDF function that we can paste in each ExploreASL module?
- for asl a table with the cbf, sd and cov for respective regions. 

As a radiologist will be looking at this repoer alongside the brain scans in a PACS, Bas claims that including more or less brain images in this report is not important, as you would just look at those in the PACS itself anyway. 

## HENK: 
Nice! This is indeed from the perspective of the radiologist, we also have to think about the perspective of clinical trials (for ASPIRE).

I like the section heading! We probably need a bit more parameters.

- [x] You wanted to create a JSON file where we could adjust the parameters to include per section, their reference values? And the path to images etc? Would be great if the PDF is easily configurable; different studies/use cases may ask for different PDFs.

### Minor: 
- [ ] Convert residual Dutch words to English (e.g., referentiewaarden)

**Comment by maartenhammer** [comment]
Frederik asked me to add minimal identification information to our PDF report, about the scanner and ASL protocol used, with some parameters. We can easily do this, but it would be tricky perhaps to still fit this on a single PDF page :)
#224

**Comment by maartenhammer** [comment]
Would be great - similar to fMRIprep - to have some sort of copy of the BIDS input and image processing parameters provenance to the methods section of the eventual paper, together with the references used.
Disclaimer: automatically generated methods part, so will be flagged up by plagiarism detection methods, similar to fMRIprep.
#229

**Comment by maartenhammer** [comment]
- [x] Change JSON objects to a unnamed Array instead
- [x] Change filePath to absolutePath or relativePath
- [x] More Complex Example
- [x] Upload Markdown Manual
- [x] Add Figure Titles

**Comment by maartenhammer** [comment]
For anyone trying this in the test branch, a [small manual](https://github.com/ExploreASL/ExploreASL/blob/f5bb987cd9a04ddf6e7fe2a594a38af4cee17c0d/WorkInProgress/QualityControl/PDFGenerator.md ) has been written in addition to the example. Please check it out.

**Comment by HenkMutsaerts** [comment]
> For anyone trying this in the test branch, a [small manual](https://github.com/ExploreASL/ExploreASL/blob/f5bb987cd9a04ddf6e7fe2a594a38af4cee17c0d/WorkInProgress/QualityControl/PDFGenerator.md) has been written in addition to the example. Please check it out.

Which test branch?
