### ISSUE TITLE
Miscellaneous improvements part 2

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1233]
### Description

Here, I list some suggestions I got when going through the newest version of ExploreASL. Part was already fixed previously in #1079 . We moved the remaining ones here.

### Tasks

- [ ] change the name `x.settings.Pediatric_Template` for generalization, as this could also be used for non-pediatric templates (though not urgent)
- [ ] `/ExploreASL/Maps/` (==`x.D.MapsDir`) only contains the folder `/ExploreASL/Maps/Templates` (==`x.D.TemplateDir`), we can simplify this by removing one folder layer. 
- [ ] When `bRegistrationCBF` is off, no need to create a `VascularTemplate` file
- [ ] What happens if `x.modules.asl.bRegistrationContrast==0` but no `mean_control` exists? Should issue warning & skip registration
- [ ] `xASL_wrp_SegmentT1w`>`xASL_wrp_SPM12Segmentation` line 417 filling pediatric template NifTIs, also line 496, requires existing NIfTIs. Here, we can add a warning if these don't exist, and add some code comments that this is a developer option only, and to which CustomScript/developer script this is affiliated (the script you can use to create the pediatric templates)
- [ ] should `x.modules.asl.motionCorrection` be `x.modules.asl.bMotionCorrection`? We discussed this but cannot remember. We should either change this, or add an explanation in a comment
- [ ] if `x.modules.asl.bRegistrationContrast` == 0 but we only have a PWI or CBF image, do we default to `x.modules.asl.bRegistrationContrast` == 2?
- [ ] `xASL_wrp_UseTemplateAsDummyStructural` needs revamping. 
- [ ] `xASL_wrp_UseTemplateAsDummyStructural` should not create `catVolFile` (line 66), `MatFile` (line 67) and `SaveFile` (line 72). Line 87 "look" -> "lock". Line 91: "correct" -> "accordingly"
- [ ] We save all images in max single floating point, which should be sufficient. But in the quantification module, should we convert temporarily to double (64 bit)? Or on other occasions?

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
