### ISSUE TITLE
Update CAT12

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1238]
### Description

Update CAT12 to a more recent version.

### Tasks

- [ ] Here we should list all our own changes and see how these should be applied in the update; also we can notify Robert Dahnke to see if he wishes to account for them. Best to review our changes with Robert?
- [ ] Should we take any SPM12 update into account?
- [ ] Potentially use this testing dataset: (LINK)[https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.kaggle.com%2Fdatasets%2Fukeppendorf%2Ffrequently-traveling-human-phantom-fthp-dataset&data=05%7C01%7Ch.j.mutsaerts%40amsterdamumc.nl%7C46e7bd5d5aff4230c3dd08daade356ee%7C68dfab1a11bb4cc6beb528d756984fb6%7C0%7C0%7C638013489187173257%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6Ex5NeRl5Yvt16HoFlGDoyyul%2Frdsfuj09%2FwGo%2F8MQ4%3D&reserved=0]

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by HenkMutsaerts** [comment]
Feedback from Robert:

The differences mostly depend on the initial affine registration.  The affine registration is one of the first and most critical steps.  If the alignment of subject and template brain is not good then all following steps such as segmentation, spatial registration or surface processing have severe problems or fail completely.  Especially in pediatric brains the head tissue classes (of the TPM or in the T1 template) caused many problems.  In these cases the affine registration focused more on fitting the head outline than the brain.  The segmented brain is then often too small because the initial SPM segmentation is biased by the bad aligned TPM.  Hence, we use a fast skull-stripping approach to stabilize this process.  Another solution is to use pediatric T1 template and TPM. 
I also expect that the skull-stripping and segmentation problem in Case 5 are the result of a bad affine registration (you can see the SPM brainmask in frontal regions) - this cause that the CSF class gets to many high intensity voxels that finally cause the miss-segmentation on the left … You can try to increase the SPM preprocessing accuracy parameter.
 
 
In case of super-large ventricles the standard TPM can cause a lot of problems in the initial SPM segmentation, where the WM class is to strong covered by ventricular CSF.  SPM then simply use the CSF intensity as WM intensity (as you can see in Case 5 CAT12.5) and cause often a tissue intensity error in the AMAP segmentation.  It is possible to use the relative new KAMAP segmentation approach in the expert mode  „Extended options for CAT12 preprocessing“ .. "Initial segmentation“   that uses the SPM segmentation only for bias corrections and for initial skull-stripping and runs the AMAP with a k-means classification to create the initial SPM segmentation.  However, this setting needs further test someday.
  
 
CAT does not include any detections of tumors or lesions and we just add a case to ignore masked regions. However, we are open for better solution that are simple and fast to implement. 
 
 
As far as this overlap is quite important to detect problems, we add the TPM brain and head outlines in the CAT report.  In children the brain outline should fit quite good, whereas the head outline of the standard adult TPM is more or less around the head.

**Comment by HenkMutsaerts** [comment]
Last discussion:

We extended our work slightly, bringing me two questions.
We started a project to artificially create artifacts on 3D T1w images (see attached, confidential), and then compare QC algorithms and see which combination works best in detecting artifacts, first in healthy controls (what level of artificla artifacts will be detrimental on determining brain age?) and later in MS, AD, and brain tumor patients.
In our early evaluations, the CAT12 IQR worked quite well [LINK](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpubmed.ncbi.nlm.nih.gov%2F35839659%2F&data=05%7C01%7Ch.j.mutsaerts%40amsterdamumc.nl%7C46e7bd5d5aff4230c3dd08daade356ee%7C68dfab1a11bb4cc6beb528d756984fb6%7C0%7C0%7C638013489187173257%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kuXXABwpdCMg3zO1rWM8zFZyKQO6gVUmhBLSoPUUO54%3D&reserved=0) so I’m interested if you continued your QC work?
I am currently running the final tests (at least I hope that) to update the paper.  I plan to keep it simple in the main part and have moved most of the details and evaluation aspects to the supplement. Although it is somehow pity to spend so much efforts in stabilizing something and then hide it, but it would only confuse readers and reviewers. I also added further test that allow a more stable estimation in case of incorrect segmentations and prepared an independent SPM batch, ie., to evaluate some images for some segmentation (eg. to estimate the T1 quality based on the SPM segmentation or to estimate the T2/PD quality based on a (registered) T1 segmentation) However, I am not expecting huge improvements in most real datasets.
Based on the paper behind the LINK - good to see that CAT is stable so far.  Btw. the WMHs estimated in T1 can be also separately written in developer mode (as class 7) and lesions/tumors that may bias registration could be handled by masking the input and setting some flags (tested in the ATLAS lesion database some versions ago).   


Some comments for the phantoms in Figure 4 of your application.
Is this the BWP? 
Smoothing - I am currently working on a new measure to quantify anatomical resolution/details by the sharpness of the GM/WM boundary rather than voxel size that would fit here pretty well. In my test cases I downsampled-resampled and smoothed data.
Deformations - are of course hard to quantify in real data. We have a huge test-retest dataset (living phantom) that show this between different sites, but I have no idea who to quantify this because this could be also real/natural. 
Inhomogeneity - this can be done with the BWP by default (3 fields A,B,C) and you can define also negative values that result in much inoptimal (=noisier) cases that cause severe errors (e.g. in SPM12).
Motion - this is mostly needed, but it would need some sub-categories with share-high frequent to low-frequent artifacts. 
Spikes - haven’t seen this one so far but should be similar like motion and result in increased noise.
Ghosting - similar like low-frequency motion and would result in increase noise (and bias).
Related to Figure 4 and 7: I have roughly tested for aging, AD and lesions and it was so far ok. White matter hyperintensities can be handled more or less but small-vessel-disease seams to be problematic because it is so similar to noise. No idea how this could be improved by normal imaging techniques and so I would see in that case the clear potential of DL.

As a reviewer, I would may ask how you quantify and include real artifacts, as far as some of your simulation are maybe too artificial und do not overlap with reality. I think I read something about it but can't find it now - so you maybe can stress this a bit more if this is still work in progress.

There are some format typos for the references in the table 2.



 
Secondly, in our clinical MS protocol, all patients get a 3D FLAIR but hardly anyone gets a 3D T1w (only in research settings they do). But more and more we find that volumetrics may be as important as WMH in MS patients (the work of my colleague Menno Schoonheim, CC). Did you continue extending CAT12 for segmenting GM-WM-CSF on FLAIR (given sufficient contrast of course)?
Not really. I only test this special cases from time to time to avoid severe problems. Overall, the processing is possible but quiet error-prone due the low contrast and the results are not really nice (especially the surfaces) and I am not sure if this can be use. However, in big clinical samples it is maybe possible (same for low-resolution and low-contrast T1 data). 
It would be possible to use the segmentation of cases with T1 data as ground-truth to somewhat quantify how robust the processing finally is.

**Comment by Doc-LI-desgin** [comment]
I installed SPM12 on Matlab 2018b, but my page does not have the option 'specialy-2nd-level'. May I ask why this is happening? I saw in the video that someone else installed the same version of SPM with this option on Matlab 2016b, and I occasionally noticed that this option appears on my SPM12, but most of the time it is not available. How can I solve this problem？
The version is SPM12 
<img width="350" alt="微信图片_20241114183147" src="https://github.com/user-attachments/assets/f14aeaba-f61e-4938-b21d-0687cfa5e542">
7771
