### ISSUE TITLE
Implement an automated testing script to run all tests in one go 

### ISSUE THREAD

**Issue by maartenhammer** [ExploreASL/ExploreASL#1247]
### Description

xASL_test_RunAll.sh is a shell script that runs all four currently available tests (Test SPM, Unit tests, Test Pipeline and Test Flavor Database) in succession and concatenates the results in a single folder.
This script can be ran manually or added to cron if you want repeated tests every few days. 

### Tasks

- [x] Include bTesting = true to xASL_test_Flavors.m
- [x] Return all test directories back to a clean set after the test. (remove the derivatives or move files to a temp scratch location).
- [x] Change the output of test scrips to both .tsv and .mat
- [x] Concatenate all failed test result files to either a pdf or a summary table. 
- [x] Change the output of the test scripts to include date-time (ISO8601)
- [x] Change xALS_test_IgnoreFiles to xASL_test_IgnoreFiles
- [x] Separate xASL_test_ExploreASL into functions xASL_Test_SPM, xASL_Test_CompareReference and xASL_Summarize
- [x] Change the input to be a seperate JSON file
 
### How to test

tba.

### Release notes

#1247 Standardized Testing Script Results, Added extra fail saves to Testing scripts, added a test script that periodically runs all tests and logs the outcome.

**Comment by maartenhammer** [comment]
Move WeeklyTest to Testing repository and change Readme to show this.

**Comment by maartenhammer** [comment]
closed by #1443
