### ISSUE TITLE
Flavor test issues

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1256]
### Description

Some flavors do not import correctly now.

### Tasks

- [x] Incorrect recognition of Siemens_PCASL_VD13D_2 as FME Hadamard time encoded.
- [x] False reporting of temp/dcm2niiCatchedErrors.json and temp/dcm2niiCatchedErrors.mat
- [x] Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1 - correctly read as Hadamard
### Release notes

Required: summarize the changes for the release notes here
