### ISSUE TITLE
Fix bug in atlas names in NativeSpaceAnalysis

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1259]
### Description

The Native space analysis in the population module was rewritten and now it doesn't work - the problem seems to be that the local atlases in the native space are correctly created but when running the ROIanalysis, an incorrect name is being passed on.

### Tasks

- [x] Atlases are named `AtlasPop` instead of the normal name `Atlas`. It is obvious that all atlases are population atlases and the Pop post-fix is superfluous. However, I understand that this will make a clear distinction that this is Pop and not individual. However, the current implementation that defines a list of atlases and creates names with Pop suffix is crazy. This pop has to be added automatically in an automatic fashion. Horrible coding practice that needs to be fixed. e60aa1e5
- [x] Automatically detect if a mask is binary or multi-label. 1a9e7a4
- [x] Don't transform all atlases but only those that will be needed = those in the atlas list. This still makes it modular, but there's really no need to transform atlases to native space that won't ever be used when this information is at hand. e9abfefc

### Release notes

Fix native space analysis.
