### ISSUE TITLE
xASL_test_Flavors header

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1262]
### Description

Without `testConfig.json`, `xASL_test_Flavors` will crash without notifying why.

### Tasks

- [x] initialize parameters to avoid non-specific crash
- [x] improve Github clone command
- [x] avoid using `clear` if not necessary
- [x] Default flavor testing to no processing
- [x] Remove empty folders before flavor testing

### Release notes

Minor improvement of Flavors testing.
