### ISSUE TITLE
Include/Exclude flavors from testFlavorDatabase

### ISSUE THREAD

**Issue by maartenhammer** [ExploreASL/ExploreASL#1270]
### Description

Change the way to include the testing of flavors to run from the flavor Database. 

### Tasks

- [ ] Add a new keyword to flavors.json in FlavorDatabase
- [ ] Read the flavors.json in Test_flavor_database
- [ ] Replace the import check from testconfig.json to flavors.json

### How to test

- [ ] Run test_flavor_database.

### Release notes

- Added a bTesting keyword to flavors.json

**Comment by maartenhammer** [comment]
This has been completed alongside #1326
