### ISSUE TITLE
Master issue: parallelization of BIDS2LEGACY

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#1275]
### Description

Aggregates all revamping issues to allow parallelizing BIDS2Legacy, which has also reduced our code complexity a lot.

### List of issues
List all the new issues here, and remove them below until we clean it completely a have only this list here.
- [x] #1495 Cleaning code
Was part of this issue, but the commits have been cherry-picked already
from b13daab8d3b0e39ada3057808024c51f9449a6f8
until e251e26f8677c65451d16eb1e4ccf9fb014e42a6
- [x] #1506 Improve lock behavior
Was part of this issue, but the commits have been cherry-picked already
from cda98f7f349252dca80ed539c41fa3ad1cbcb954
until 8985da91e851d76f79b51bfca075515da593a59f
- [x] x.D.ROOT usage #1547 
Was part of this issue, but the commits have been cherry-picked already
from 13393d03efe68162f60b43997878c53e31c872e7
until 99ec9a830981bbfaf64f8cbb60fa711c890d4809

### ToDo / requests
- [x] Remove parameters from documentation: x.opts.bSkipBIDS2Legacy and x.dataset.TimePoint*
- [x] #1537
- [x] #1198 
- [x] #915 Closed as duplicate
- [x] #1037 Tested and closed as obsolete/outdated

### How to test
- [x] Test flavors
- [x] Test TestDataSets, which still have quite old data structures (from previous ExploreASL versions)
- [x] Test rerunning when locking other lock folders for the same subject
Slurm script for parallel running: (https://github.com/ExploreASL/CustomScripts/tree/main/flux)
Datafolder: /home/user/lood_storage/divi/Projects/ExploreASL/Insight46/04062023/test_HenkJan/
Code (for parallel run): `ExploreASL('/home/user/lood_storage/divi/Projects/ExploreASL/Insight46/04062023/test_HenkJan/',0,[1 1 0],0,x,y)`

### Release notes

Improved BIDS2Legacy behavior, allow parallelization
