### ISSUE TITLE
Master xASL DEBBIE issue

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#1282]
### Description

This issue contains all ExploreASL DEBBIE goals, to be achieved by the end of January + the Automated DEBBIE pipeline to be achieved by the end of February.

### Tasks
- [x] Merge all multi/single PLD functions @jan-petr  (#1002 )
- [x] Check Amnah's processing of Dresden BBB data (Jan's) step by step and check if it matches with our images (#1344)
- [x] First fix BASIL #1301 
- [x] Correct output of TI #1386
- [x] Merge all BASIL and FABBER functions @jan-petr (#1181 )
- [x] Fix T2 times of blood and tissue #1408
- [x] xASL_wrp_ProcessM0: Warning discrepancy M0 nVolumes ~ JSON nTE #1512
- [x] Prepare a proper PWI4D #997
- [x] Automating the BBB processing pipeline (#1096)
- [x] Allow low-quality BASIL/FABBER for testing #1549
- [x] Hadamard motion correction bug #1513
- [x] Weighted-average PWI creation for registration (#1539)
- [x] Check #1122 
- [x] Automated BBB processing follow-up (#1543)
- [x] Full merging of 3 issues in a special branch #1551 
- [x] #1726 
- [x] #1836 
- [x] Solve open BASIL issues #1468 
- [x] #1800 
- [x] Solve open BASIL issues #1471
- [x] Motion issues #1525 
- [x] #1834 
- [ ] TOP-UP applied during merging (if not applied before merging)
- [ ] Once the basic automated processing is done on a single-click without manual intervention, we will need to put in a DEBBIE example into test-dataset
- [ ] Revise the M0 quantification procedure and verify all T1 times and masking etc.
- [ ] For tumors, fit subject-specific T2 maps – from M0 or b.supp control image (incorporate option that activates this) + use T2 maps and call Basil with maps or ROIs – to create these clusters might be tricky). **[discussed with Amnah]**
- [ ] Calculate T2 of blood -> with shortest PLD -> automatically delineate clusters with higher values, and then we run T2 fitting -> single number per subject for quantification (we need a QC procedure -> stop it, look at the masks and modify manually if needed) **[discussed with Amnah]**
- [ ] Boundary based motion correction to work with different TEs and PLDs
- [ ] B1-inhomogeneity fix affecting refocusing to improve homogeneity
- [ ] B1-inhomogeneity and M0 differences between HAD4 and HAD8
- [ ] Smoothing before fitting, better adapting smoothing to consider tissue differences

### Release notes
A master issue, no release notes.
