### ISSUE TITLE
SuperGzip Rust implementation update

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#1285]
### Description

Noticed that gzipping runs after every BIDS2Legacy run. Knew it could be faster since the original was written in Python. Indeed, it is superior by all metrics if re-written in Rust:

- 2.5x faster on a single thread
- Orders faster on multithread, depending on the system
- Slower than native find + grep + gzip on Unix on single thread b/c it validates that a filepath still exists. I'd argue this potentially  makes it safer than find + grep + gzip if multiple ExploreASL workers are simultaneously trying to access similar Nifti files that may or may not exist by the time one of the workers is done gzipping.
- Faster than find + grep + gzip on Unix when --num-threads = 3 or greater. 
- Executable size is ~9x smaller (~1.1MB vs Python implementation being ~10MB)

All major desktop releases available here: https://github.com/MauricePasternak/SuperGZip/releases/tag/v0.2.0

### Tasks

- [ ] Make adjustments to `xASL_adm_GzipAllFiles.m`
- [x] Test on macOS:
        HENK: with 8 cores on macbook Pro intel, zipping `/ExploreASL/External/TestDataSet` takes 2.6 s, unzipping 0.5 s.
        Using `find | grep` zipping takes 2.7 s.
        When I clone `/ExploreASL/External/TestDataSet/rawdata` 8 times, unzipping takes 2.7 s, zipping 7.4 s.
        Using `find | grep` zipping takes 2.9 s (but it skipped foldernames with spaces).
        Removing the spaces in foldernames:
        Using `find | grep` zipping takes 21.6 s (but it skipped foldernames with spaces).
        
        So for macOS: 3-fold increase in performance, is more flexible with foldernames, only downside is that we have yet 
        another mac application that needs approval when ran first time (but that's fine I would say)
- [x] Test on Windows server (28 cores; 32 files)
        zipping 16.2 s
        Windows Matlab method: 81.5 s
        so 5-fold increase (because of parallelization probably)

        Advantage: we don't need to use WSL for fast zipping, eases the code.

- [ ] Test on old Linux server (28 cores): gives an error, can you include these libraries in the compilation?

>> /scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux)
/scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux)
/scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux)
/scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux)
/scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux)
/scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /scratch/hjmutsaerts/ExploreASL/External/SuperGZip/super-gzip_linux)

Only disadvantage of SuperGzip (but `find | grep` has the same) is that we don't have a progress tracker, @MauricePasternak would this be possible to print on the screen? Or only when we select the non-verbose mode?

Minor spelling mistakes:
Deompressing -> Decompressing

Also: our imaging IT specialist Paul Groot asks if SuperGzip is faster than pigz?

### How to test

```matlab
glob_pat = join(['"' ROOT '/**/*.nii"']);
command = [PathToSuperGzip ' gzip ' glob_pat ' -n ' num2str(numCores) ' --verbose' ];
[exit_code, system_result] = system(command);
```

### Release notes

Required: Updated SuperGzip to use the newer Rust implementation.

**Comment by MauricePasternak** [comment]
Regarding progressbar feedback: it would be a deterimental feature to include in terms of performance. Current implementation's glob iterates over filepaths without waiting as the os system provides them in arbitary order. A progressbar would necessitate first storing all the filepaths in memory, then iterating over them. I not surprised `gzip` and other such tools also don't provide a progressbar for this reason.

Regarding GLIBC version, this is probably the result of Github Actions being asked to compile on `ubuntu-latest`. I can dial it down to the server's version (18.04???) and the lower & compatible GLIBC version should be included instead. [No guarentees though](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/).

No idea if it is faster than pigz. I'd wager no; I think on average Rust is 10% slower than C, plus the devs of pigz probably do a couple of additional low-level optimizations.

**Comment by HenkMutsaerts** [comment]
Then why don't we use `pigz` instead? Always better not to reinvent the wheel ;)
Jan should be able to compile `pigz` for all OSes.

**Comment by MauricePasternak** [comment]
If you can compile a `pigz` executable for all OSes, I'd probably go with that as well. If not, then this implementation is already compiled for all modern OS released within the last 4 years.

**Comment by HenkMutsaerts** [comment]
Let's do that then. I would recommend in general "not reinventing the wheel", "never change a winning team". We have too much work already :)

@maartenhammer can you check how easy it is for us to include `pigz` for all OSes in ExploreASL? I know that some OSes may already have it, but I'm talking specifically about including it without having to run `sudo`. This would require it being compiled on a relatively old distribution so it's both backward and future compatible. If this is not doable, we could stay with supergzip.
