### ISSUE TITLE
xASL_wrp_CreateBiasfield crashes with multiple sites

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1287]
### Description

`xASL_wrp_CreateBiasfield` crashes with multiple sites

### Tasks

- [x] Replace `xASL_wrp_CreateBiasfield` line 267 `iNext = [1 1 1];` by `iNext = ones(1,nSites);`
- [x] Add a test example with more than 2 sites to `TestDataSets`, that is already processed & only tests the Population module:  #1291. `xASL_wrp_CreatePopulationTemplates` does not seem to need more than 2 subjects per site (although we may need to check how the outlier exclusion works that I wrote)

### How to test

- [x] Run the population modules with a single site - Jan will run TestDataSets.
- [x] Run the population modules with more than 3 sites - Victor will try this on a real example.

### Release notes

Fixed site-biasfield correction for more than 3 sites.
