### ISSUE TITLE
Incorrectly import and BIDS2Legacy of multiple anatomical images.

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1288]
### Description

Dataset that imports anatomical images as duplicates first creates two anatomical runs in rawdata, and then when doing BIDS2Legacy it messes up the order of the multiple-runs. We fix both errors, while fixing one of them would have been sufficient for this dataset.

`xASL_bids_BIDS2Legacy_ParseModality` line 43 sorts the table `reference`.
Indices (e.g., `TypeRunIndex`) are then created according to the sorted `reference` table.
But `ModalityFields` (and perhaps others?) does not get sorted accordingly, so `xASL_bids_BIDS2Legacy_CompilePathsForCopying` line 70 had unmatched `TypeRunIndex` and `ModalityFields` in the case of multiple ASL or anatomical runs.

### Tasks

- [x] Fix the sorting from `xASL_bids_BIDS2Legacy_ParseModality`
- [x] Add a final filename check before copying in `xASL_bids_BIDS2Legacy_ParseScanType`
- [x] Some minor warning improvements in `xASL_bids_parseM0` & `xASL_imp_UpdateDatasetRoot`
- [x] Default output when `SessionID` is empty in `xASL_wrp_BIDS2Legacy` (tricky to default to 1 as this may be incorrect, so just added "unknown" as default)
- [x] If multiple anatomical files are converted to NII, but they are not assigned a specific run-label, then covert only the non-labeled one from the first run.
- [x] Inform Mervin about merging.

### Release notes

Correct import and BIDS2Legacy with duplicate anatomical scans.
