### ISSUE TITLE
Minor GE flavor bugs

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1294]
### Description

Some minor issues I discovered when importing and processing the DV25.0 GE at 1.5T.

@jan-petr I have prepared this for you, just rebased with develop March 5th 2023, so should be easy for you to process.
The automatic splitting is now moved to #1331, for now I will just split the DICOMs and manually add the PostLabelingDelay.

### Tasks

- [x] HENK: Automatically discard a CBF volume in BIDS2Legacy (like we do with dummy volumes)? JAN: I would keep this in BIDS2Legacy and just make sure that it's copied correctly. And then when splitting ASL to ASL + ASL_source + M0, we get rid of CBF if we see we have M0 and ASL as well (so at the same time when we throw of dummy scans. See below
HENK: This now works with the correct parameters in `studyPar.json`, but this doesn't lead to correct BIDS rawdata, but it works. I thought is was very confusing that `xASL_module_ASL` line 266 > `xASL_io_SplitASL` uses `x.modules.asl.DummyScanPositionInASL4D`, but this wasn't initialized anywhere. I now see this is dealt with in BIDS2Legacy and have added a comment to acknowledge this.
- [x] GE vendor warning when sequence parameter exists and set to 3D spiral
- [x] Create import check for number of tokens in `folderHierarchy` and `tokenOrdering`, these should be the same, otherwise the import will continue but create wrong outputs (in my case it called the `ASL4D.nii` the `SubjectName.nii`)
- [x] `xASL_imp_DCM2NII_Subject_StartConversion` line 33 contains iSubject iVisit iSession iScan which are not defined (probably a copy-pasting issue).

### Release notes

Minor bug fixing for importing GE scans.
