### ISSUE TITLE
Use Matlab internal json-encode functions instead of SPM routines

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1311]
### Description
Stop using `SPM_JSONREAD` as this tends to crash with certain illegal JSON formats. We'll switch to Matlab I/O and `JSONDECODE` and `JSONENCODE`

>> fileID = fopen('xxx.json','r');
txt = fscanf(fileID,"%s");
j = jsondecode(txt);
fclose(fileID);

I've tested that both functions run the same time, so time-wise we won't loose anything.

HENK: won't we have as side-effect that if something crashes in between `fopen` & `fclose`, this will be pain? The file would be locked, so you cannot easily remove e.g., the derivatives folder and rerun. You don't seem to have this issue with the current `spm_jsonread` MEX? But that is perhaps a small price to pay.

Or perhaps we can immediately close the fileID after reading it; same for writing.

JAN: We of course close it immediately, but the issue is not in doing it fast, but about catching potential issues. So all that's inbetween opening and closing of a file is in a try-catch and if something fails, we first close the file and then report an error. So there isn't really a possibility of keeping a file open. Besides - this is mainly a Windows problem.

>> fileID = fopen('xxx.json','r');
txt = fscanf(fileID,"%s");
fclose(fileID);
j = jsondecode(txt);

### Tasks

- [x] Write a new function `xASL_io_jsonread`
- [x] Write a new function `xASL_io_jsonwrite`
- [x] Replace all spm_readjson
- [x] Replace all spm_writejson
- [x] Write a UT function with one correct and one incorrect JSON

### How to test

- [x] Henk checks code
- [x] Unit testing with this new test runs through
- [x] Check flavors in develop
- [x] Flavors are still running fine in this branch?
- [x] Issues with the last flavor - Siemens_PCASL_3DGRASE_VB17A_TopUp_2
- [x] Should we remove this from the last lines of `xASL_mex_compileAll` about `spm_jsonread`. JAN: This is already removed!

### Release notes

Use Matlab functions instead of SPM for I/O of JSON files.

**Comment by HenkMutsaerts** [comment]
My issue with closing fast is not that pipeline stuff can go wrong, but rather that if the user voluntarily crashes ExploreASL to restart, if a file is still open, this is annoying. That was my only reason to `fclose` asap.

**Comment by jan-petr** [comment]
> My issue with closing fast is not that pipeline stuff can go wrong, but rather that if the user voluntarily crashes ExploreASL to restart, if a file is still open, this is annoying. That was my only reason to `fclose` asap.

Sure. And this is now fixed. Both against crashing in code and crashing by user ;) 

HENK: Yes I see now, looks good!

**Comment by HenkMutsaerts** [comment]
@jan-petr did you adapt `xASL_mex_compileAll` line 77 accordingly?
>> mex -O -largeArrayDims spm_jsonread.c jsmn.c -DJSMN_PARENT_LINKS
