### ISSUE TITLE
Reference atlases, Mindboggle, xASL_stat_GetROIstats

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1314]
### Description

Adds 3 population-based atlases, based on the ExploreASL paper.
Registers the MindBoggle atlas.
Adds bWMH boolean for (de-)activating WMH exclusion from WM mask
And a few minor fixes.

### Tasks

- [x] Add SD maps to ExploreASL for populations shown in ExploreASL paper (NOVICE, Sleep, EPAD) and add license (per ExploreASL paper). Start with EPAD only. The between-subject CoV doesn't appear smooth though, so it could be helpful to smooth individual images before creating the bs-CoV template; or to do this in a PVC-way.
- [x] Add license for these atlases
- [x] Register MindBoggle atlas to CAT12-IXI space
- [x] Fix warnings for xASL_spm_affine & xASL_vis_CreateVisualFig
- [x] Bugfixes xASL_stat_GetROIstatistics: ROI visualization
- [x] Improve printing which masks are used
- [x] Add bWMH boolean for (de-)activating WMH exclusion from WM mask
-> see #1745 for the explanation regarding the bWMH

HENK PM: if registering Mindboggle still needs improvement (I don't think so) we could try the following:
       Mindboggle is registered with ICBM152 (e.g., http://www.bic.mni.mcgill.ca/ServicesAtlases/ICBM152NLin2009)
       & we are registered with CAT12s slightly different MNI atlas.
       a. Solution is to affine transform Mindboggle to our CAT12 MNI atlas, using the templates from ICBM152 to 
       CAT12:
       mni_icbm152_nlin_sym_09c_nifti/mni_icbm152_nlin_sym_09c/mni_icbm152_(gm|wm|csf)_tal_nlin_sym_09c.nii
        /ExploreASL/External/SPMmodified/MapsAdded/rc1T1.nii (OR /SPMmodified/toolbox/CAT12/templates/last iteration

### Release notes

#1314 Adds 3 population-based atlases, based on the ExploreASL paper.
#1314 Registers the MindBoggle atlas.
#1314 Adds bWMH boolean for (de-)activating WMH exclusion from WM mask
