### ISSUE TITLE
Multi-PLD Look-Locker analysis

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#1323]
### Description

Current BASIL implementation does not allow for Look-Locker processing. 

### Tasks

- [x] Check automatic label-control order
- [x] Calculate PWI correctly for look-locker order (check if programmed already). 
- [x] Fix #1301 
- [x] Fix import of second sessions #1318 
- [x] Fix Philips Look-Locker import #1366 
- [x] Rebase this branch once all the above is merged.
- [x] Run BIDS validator
       One error, couple of warnings in rawdata.
- [x] Check if M0 is input in BASIL quantification
- [ ] Check if PWI4D without averaging works better
- [x] BASIL M0 quantification `xASL_quant_M0` for look-locker (asl_calib) https://asl-docs.readthedocs.io/en/latest/aslcalib.html 
    - [x] Create M0, based on WM, using asl_calib (FSL)
    - [x] Create .json for that as well
    - [ ] Put in nice function
    - [ ] Keep code, but use control image as M0 instead of constructed one
           - [ ] Check GM and WM ratio in signal per PLD
- [x] Check where to put the extraction of all control images in the ASL module for Look-Locker/ASL_calib use.
       - [x] cite in the code
- [x] Check motion correction
       Currently skipped
- [x] Check what to skip in `xASL_processM0`
       - 1. register M0 -> can be skipped for the datasets where a new M0 is created via asl_calib -> look for folder and skip?
       - 2. Quantify M0 -> skip as asl_calib already does that.
       - 3. Masking & smoothing -> not sure?
- [ ] `UseControlAsM0` automatically added in ASL4D, but should not in this case.
- [ ] Comment from Jeroen 1: in the new Basil (oxford_asl in the new fsl 6.0.6.4) there is a -fa option to presumably correct for the Look Look-Locker readout (small flip angle than 90 deg). Currently, we correct the multiPLD label/control images and M0 image signals beforehand. The correction factor per PLD is then based on the PLD value and the flip angle used - inspired by Gunther et al MRM 2001 (https://onlinelibrary.wiley.com/doi/10.1002/mrm.1284) and Petr et al MRM 2013 (https://onlinelibrary.wiley.com/doi/10.1002/mrm.24601). This works remarkebly well, as validated against a single (simple) PLD scan CBF map. 
     - [x] Discussed with Jan, correction factors is: `PWIcor = PWI / cos ^(n-1) * (flip angle)` with n is PLD number according to formula 5 of https://onlinelibrary.wiley.com/doi/10.1002/mrm.1284.
     - [x] cite in the code
- [ ] the oxasl code for the Look Look-Locker data - as I also need the option there to set the --aifleadscale (set to very small)  otherwise we get a 'funny' looking slice in the arterial arrival time output. According to Martin Craig this apparently has to do with making the model for arterial bolus, normally a boxcar function, a bit less discontinuous at the edges, and help to go smoothly through the inference process for ATT.
- [ ] Check single-PLD vs Look-Locker on a composite dataset (Jan will put it to flavors).
- [x] Look-Locker import at the moment creates wrong number of averages
     280 acquired pairs, what should be 560/8/2=35
- [ ] Printing stats error
      
    'Index in position 1 exceeds array bounds (must not exceed 132).
     
     Error in xASL_stat_PrintStats>xASL_stat_PrintStats_FillStatCellArray (line 390)
             statCell{rowNum,iCell} = xASL_num2str(x.S.DAT(iSubjectSession_DAT, iPrint));
     

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by MDijsselhof** [comment]
![image](https://user-images.githubusercontent.com/75380250/220128530-098d1f46-94a5-421f-9b4d-0945c4e3c665.png)

Just saw this when going through the code and this is incorrect for this dataset.

**Comment by MDijsselhof** [comment]
![image](https://user-images.githubusercontent.com/75380250/220149214-e231df64-219e-4453-a238-798ef9140831.png)

Initial post labelling delay is not correct. Either all single values should be duplicated or checked for look-locker and adjusted accordingly.

**Comment by MDijsselhof** [comment]
x.Q.FlipAngle does not exist and is not created anywhere in the code as far as I can tell

**Comment by MDijsselhof** [comment]
asl_calib just 'calibrates' the relative perfusion map to absolute perfusion: https://asl-docs.readthedocs.io/en/latest/aslcalib.html#asl-calib-usage. We could do that ourselves if we have inversion recovery M0 processing. We can provide the perfusion image to calculate absolute perfusion (not sure if voxelwise) or use it to obtain an estimate of M0 of arterial blood. 

Otherwise we can use:
`asl_calib -c M0_image -s T1w_image -t ASLtoT1w_transformation_matrix --mode satrecov --tissref csf --te TE_M0_image -i Perfusion_Image -o qCBF_image --M0 M0_value_file`

If we choose SatRecov, we need to provide a list of inversion times in the data, the flip angle for look-locker readouts. The previous line of code would then be:

`asl_calib -c M0_image -s T1w_image -t ASLtoT1w_transformation_matrix --mode satrecov --tis ListofTIs --tissref csf --te TE_M0_image -i Perfusion_Image -o qCBF_image --M0 M0_value_file `

There are more options if preferred:
`--t1r T1_reference_tissue_value --t2r T2_reference_tissue_value -- t22b T2_blood_value`

**Comment by MDijsselhof** [comment]
Code used at 07-03-2023: `asl_calib -c /home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/ExcersionVCI/16012023/testing/test_ASL_Calib/test_conversion_single_subject_multiPLD_look_locker/derivatives/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_2/ControlImages.nii.gz --mode satrecov --tissref csf --te  13.894  -m /home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/ExcersionVCI/16012023/testing/test_conversion_single_subject_multiPLD_look_locker/derivatives/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_2/PVcsf.nii --tis 0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4 --fa 30 -o /home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/ExcersionVCI/16012023/testing/test_ASL_Calib/test_conversion_single_subject_multiPLD_look_locker/derivatives/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_2/`

**Comment by MDijsselhof** [comment]
Try PV WM map, threshold above 0.7 and try ASL calib again. Put tissue ref to WM.
Check rM0, looks strange.

**Comment by MDijsselhof** [comment]
GetMeanControl already has extraction for LL, I just need to put the intensity correction there!
