### ISSUE TITLE
xASL_test_Flavors.m fails file comparison test, zipping of nifti's not completed after import.

### ISSUE THREAD

**Issue by maartenhammer** [ExploreASL/ExploreASL#1334]
### Description

For 28 flavors (somehow not all), files are saves at <nifti>.nii instead of <nifti>.nii.gz
This is probably caused by the commit in #1320.
Attached are the differences measured by the flavor test.
[Missing Files.xlsx](https://github.com/ExploreASL/ExploreASL/files/10896578/Missing.Files.xlsx)

### Tasks

- [x] After running import, zip contents `rawdata` (.nii->.nii.gz): 
- [x] After running processing, zip contents `rawdata` (.nii->.nii.gz): this was already done at the end of the population module

### How to test

- [x] Run xASL_test_Flavors.m without errors.

### Changes log
Always zipping derivatives .nii -> .nii.gz after processing when not parallelized.
Report together with #1320
