### ISSUE TITLE
Implementation BaMoS in ExploreASL

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1335]
### Description

BaMoS is Carole Sudre's WMH segmentation, which works quite a bit better than the LST one ExploreASL uses by default. It would be great if we can incorporate Carole's code in ExploreASL. @Carole perhaps you can comment on the needed steps below?

### Tasks
- [ ] Carole checks with Jorge: check end April
- [ ] Find student for the testing
- [ ] Implementing with programmer/Carole/Jan/us
- [ ] Add the atlases that BaMoS uses (@Carole probably wants to make a "light" version of BaMoS for ExploreASL?
- [ ] API between BaMoS and ExploreASL, in the ExploreASL Structural module `040_LST_Segment_FLAIR_WMH` (how to call BaMoS through bash, first for Linux, then macOS, then also Windows), add a boolean setting bBaMoS that will run BaMoS instead of LST; renaming files in between the software packages
- [ ] Test running BaMoS separately and in ExploreASL, does it give the same results?
- [ ] Also, test for the subsequent lesion filling in the T1w & volumetrics
- [ ] Compile BaMoS for OSes & include in ExploreASL?
- [ ] Add a short manual/description with the basic settings of BaMoS that can be tweaked for different use cases
- [ ] Add licenses & referencing guidelines
- [ ] PM: add coalescence/shape parameters

Should we get a student to compare BaMoS light with the original BaMoS? 
juxtacortical regions -> important for MS. So “BaMoS-light” should be tested with MS,
and with subjects where it won’t matter (e.g., Twins)

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
