### ISSUE TITLE
Fix Hadamard decoding

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1344]
### Description

Hadamard import and decoding doesn't work for some datasets.
With our current version of develop:

- [x] Dresden data -> "Walsh" creates a correct HAD4 PWI + a bad HAD8 PWI. Also tried "Hadamard" for HAD8 and does not work. JAN: Now in flavors and both HAD8 and HAD4 works.
- [x] Flavor Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1 -> "Walsh" creates a good HAD4 PWI and good HAD8 PWI!! (n.b. but this HAD8 has only 1 repetition, so 7 volumes after decoding). JAN: Works for me as well, though it doesn't look too awesome.
- [x] One Singapore subject -> "Walsh" also creates a good HAD4 PWI, but bad HAD8 PWI. Tried running "Hadamard" for ASL_2 only to see if HAD8 PWI improves. It doesn't. JAN: Works for me in 1.11.0_BETA. Same as for Dresden data - it works and is equal in comparison to the scanner-created substractions.
- [x] Esin/Gulce data -> "Hadamard" creates a PWI HAD4 with all PLDs together for each TE + nonsense HAD8 PWI
- [x] Flavor Philips_PCASL_2DEPI_5.6.1.2_Hadamard_1 -> "Hadamard" creates a good HAD8. doesn't have HAD4, only HAD8 (with only 1 repetiton) but it works.
- [x] Flavor Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1 -> "Walsh" works for HAD4 PWI, but for HAD8 it is in the correct order I think, but one of two volumes of the last PLDs seem to be switched (2 repetitions). JAN: This works great - great subtraction and looks visually good.
- [x] One LCBC subject -> "Walsh" creates a good HAD4 PWI, but bad HAD8 PWI. Tried running "Hadamard" for ASL_2 only to see if HAD8 PWI improves. It doesn't.
### Tasks

- [x] Fix import for Dresden data to match Amnah's version.
- [x] Fix Dresden scalings according to Amnah
- [x] Add Dresden to flavors
- [x] Fix Walsh decoding for HAD4 and HAD8 for Dresden to match Amnah's version.
- [x] Fix Walsh import and decoding for Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1
- [x] Fix Walsh import and decoding for Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1
- [x] Fix Walsh import and decoding for LCBC
- [x] Fix Walsh import and decoding for Singapore
- [x] Check if Philips_PCASL_2DEPI_5.6.1.2_Hadamard_1 still works
- [x] Add Turkish data to flavors
- [x] Test FABBER quantification HAD4/HAD8 (Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1)
- [x] Test FABBER quantification HAD4/HAD8 (Siemens_PCASL_3DGRASE_VE11C_DEBBIE_2)
- [x] Test FABBER quantification HAD4/HAD8 (Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1)
- [x] Test FABBER quantification HAD4/HAD8 (Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1)

### Release notes

Nothing to release. Just verification of functionality.

**Comment by jan-petr** [comment]
OLDER CODE BY AMNAH:
function [ Decoded_ASL ] = HadamardDecoding( HadamardSize, sec )
% decides if Walsh or Natural Hadamard Matrix
% for different sizes of matrices

if sec == 1 %natural ordering
    
    if HadamardSize == 4
        
        ASL_im = xASL_io_Nifti2Im('C:path to\ASL4D.nii.gz'); % Load time-series nifti
        dim4 = size(ASL_im, 4); %just to check the size dim4 (no. of volumes = 64)
        HadamardSize = 4;
        nTE=8;
        rep=2;
        decoded_ASL_size = (HadamardSize-1)*nTE*rep; %just to check size of decoded data
        
        %decoding scheme HAD-4
        %abs(a-b+c-d) = TI-1
        %abs(a-b-c+d) = TI-2
        %abs(a+b-c-d) = TI-3
        
        j=1;
        for x = 1:HadamardSize:dim4
            
            Decoded_ASL(:,:,:,j) = ASL_im(:,:,:,(x)) - ASL_im(:,:,:,(x+1)) + ASL_im(:,:,:,(x+2)) - ASL_im(:,:,:,(x+3));
            Decoded_ASL(:,:,:,j+1) = ASL_im(:,:,:,(x)) - ASL_im(:,:,:,(x+1)) - ASL_im(:,:,:,(x+2)) + ASL_im(:,:,:,(x+3));
            Decoded_ASL(:,:,:,j+2) = ASL_im(:,:,:,(x)) + ASL_im(:,:,:,(x+1)) - ASL_im(:,:,:,(x+2)) - ASL_im(:,:,:,(x+3));
            
            j=j+(HadamardSize-1);
        end
        
        figure %for visualization
        image(Decoded_ASL(:,:,12,1));
        
        % write the 4D nifti file
        Decoded_ASL_nii = make_nii(Decoded_ASL)
        save_nii(Decoded_ASL_nii, 'path to...\example_decoding_had_4.nii.gz')
        
    elseif HadamardSize == 8
        
        %decoding scheme HAD-8
        %abs(a-b+c-d+e-f+g-h) = TI-1
        %abs(a-b+c-d-e+f-g+h) = TI-2
        %abs(a-b-c+d-e+f+g-h) = TI-3
        %abs(a-b-c+d+e-f-g+h) = TI-4
        %abs(a+b-c-d+e+f-g-h) = TI-5
        %abs(a+b-c-d-e-f+g+h) = TI-6
        %abs(a+b+c+d-e-f-g-h) = TI-7
        
        ASL_im = xASL_io_Nifti2Im('path to...\had_8_multite_encoded.nii.gz'); % Load time-series nifti
        dim4 = size(ASL_im, 4); %just to check the size dim4 (no. of volumes = 64)
        HadamardSize = 8;
        nTE=8;
        rep=1;
        decoded_ASL_size = (HadamardSize-1)*nTE*rep;
        
        j=1;
        for x = 1:HadamardSize:dim4
            
            Decoded_ASL(:,:,:,j) = ASL_im(:,:,:,(x)) - ASL_im(:,:,:,(x+1)) + ASL_im(:,:,:,(x+2)) - ASL_im(:,:,:,(x+3)) + ASL_im(:,:,:,(x+4)) - ASL_im(:,:,:,(x+5)) + ASL_im(:,:,:,(x+6)) - ASL_im(:,:,:,(x+7));
            Decoded_ASL(:,:,:,j+1) = ASL_im(:,:,:,(x)) - ASL_im(:,:,:,(x+1)) + ASL_im(:,:,:,(x+2)) - ASL_im(:,:,:,(x+3)) - ASL_im(:,:,:,(x+4)) + ASL_im(:,:,:,(x+5)) - ASL_im(:,:,:,(x+6)) + ASL_im(:,:,:,(x+7));
            Decoded_ASL(:,:,:,j+2) = ASL_im(:,:,:,(x)) - ASL_im(:,:,:,(x+1)) - ASL_im(:,:,:,(x+2)) + ASL_im(:,:,:,(x+3)) - ASL_im(:,:,:,(x+4)) + ASL_im(:,:,:,(x+5)) + ASL_im(:,:,:,(x+6)) - ASL_im(:,:,:,(x+7));
            Decoded_ASL(:,:,:,j+3) = ASL_im(:,:,:,(x)) - ASL_im(:,:,:,(x+1)) - ASL_im(:,:,:,(x+2)) + ASL_im(:,:,:,(x+3)) + ASL_im(:,:,:,(x+4)) - ASL_im(:,:,:,(x+5)) - ASL_im(:,:,:,(x+6)) + ASL_im(:,:,:,(x+7));
            Decoded_ASL(:,:,:,j+4) = ASL_im(:,:,:,(x)) + ASL_im(:,:,:,(x+1)) - ASL_im(:,:,:,(x+2)) - ASL_im(:,:,:,(x+3)) + ASL_im(:,:,:,(x+4)) + ASL_im(:,:,:,(x+5)) - ASL_im(:,:,:,(x+6)) - ASL_im(:,:,:,(x+7));
            Decoded_ASL(:,:,:,j+5) = ASL_im(:,:,:,(x)) + ASL_im(:,:,:,(x+1)) - ASL_im(:,:,:,(x+2)) - ASL_im(:,:,:,(x+3)) - ASL_im(:,:,:,(x+4)) - ASL_im(:,:,:,(x+5)) + ASL_im(:,:,:,(x+6)) + ASL_im(:,:,:,(x+7));
            Decoded_ASL(:,:,:,j+6) = ASL_im(:,:,:,(x)) + ASL_im(:,:,:,(x+1)) + ASL_im(:,:,:,(x+2)) + ASL_im(:,:,:,(x+3)) - ASL_im(:,:,:,(x+4)) - ASL_im(:,:,:,(x+5)) - ASL_im(:,:,:,(x+6)) - ASL_im(:,:,:,(x+7));

            j=j+(HadamardSize-1);
        end
        
        figure %for visualization
        image(Decoded_ASL(:,:,12,40));
        
        % write the 4D nifti file
        Decoded_ASL_nii = make_nii(Decoded_ASL)
        save_nii(Decoded_ASL_nii, 'path to...\example_decoding_had_8.nii.gz')
        
    else
        
        %output = decoding scheme for hadamard-12;
        
    end
    
elseif asl == 2 % walsh ordered
    
    if HadamardSize == 4
        
        %output = decoding scheme for hadamard-4;
        
    elseif HadamardSize == 8
        
        %output = decoding scheme for hadamard-8;
        
    else
        
        %output = decoding scheme for hadamard-12;
        
    end
    
end
