### ISSUE TITLE
xASL_io_jsonwrite 'PrettyPrint' = true does not work in Matlab versions before 2021a

### ISSUE THREAD

**Issue by maartenhammer** [ExploreASL/ExploreASL#1348]
### Description

Required: insert bug description here

### Tasks

- [x] Implement verLessThan('matlab', '9.10')
- [x] Run with PrettyPrint if version >= 2021a. 

### How to test

- [x] RunTestDataSets on v2019a
- [x] RunTestDataSets on v2021a
- [x] 'Siemens_PCASL_3DGRASE_Vida_XA31_SingleMultiPLD_1' crashes
- [x] 'Siemens_PCASL_3DGRASE_XA31_multiPLD_2' crashes
- [x] 'Siemens_PCASL_3DGRASE_VE11E_DEBBIE_1'  not on flavors.json
- [x] PARREC_1 problem with 3T
- [x] Run UnitTest on v2021a

### Release notes

Own version of  'PrettyPrint' for jsonencode. Repoert with #1311

**Comment by maartenhammer** [comment]
I've made the changes locally already on the weeklyTesting branch, Currently running TestFlavors without pretty print to see if the results are still correct. 
If PrettyPrint cannot be turned off, this is a bigger issue though. But as far as I know, Pretty print doesnt change anything for the processing of the Json, just the readability. 
We could add the formatting manually for versions before 2021a.

**Comment by maartenhammer** [comment]
Quick meeting with Jan:
- Add a subfunction that lookst for ``` ", or }, or ],``` and add a newline to it to manually "PrettyPrint" the jsons.
- Standardize naming of subfunction to xASL_sub_xxxxx
- Decide wether to implement prettyprint at for v2021b, vectors become very long and ugly.

**Comment by maartenhammer** [comment]
With Flavor Database an issue arises with these flavors: 

```
    {'Siemens_PCASL_3DGRASE_Vida_XA31_SingleMultiPLD_1'}
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'           }
```

Also     {'Siemens_PCASL_3DGRASE_VE11E_DEBBIE_1'            } seems to be missing/incorrectly named from flavors.json.


```
Please check the sub_regexp in your Data Parameter File.
This should match with the subject folders inside the ROOT folder.
This was /scratch/radv/mshammer/FlavorDatabase/Siemens_PCASL_3DGRASE_XA31_multiPLD_2/derivatives/ExploreASL ...

Error using xASL_init_DefineStudyData (line 141)
No subjects defined, x.SUBJECTS was empty...

Error in xASL_init_DataLoading (line 69)
        x = xASL_init_DefineStudyData(x);

Error in ExploreASL_Process (line 100)
		x = xASL_init_DataLoading(x);

Error in ExploreASL (line 97)
        x = ExploreASL_Process(x);

Error in xASL_test_Flavors_BIDS2LEGACY (line 27)
            ExploreASL(currentFlavor);

Error in xASL_test_Flavors (line 180)
xASL_test_Flavors_BIDS2LEGACY(testConfig);
```
