### ISSUE TITLE
Improve vascular masking using SD image (Dealing with 3D GRASE artifacts)

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1355]
### Description

Many 3D GRASE sequences have similar vascular artifacts arising from the carotids or CoW, that streak fully through the whole image. Our first requirement is to improve the masking, so this artifact is not taken into our ROI stats, and the second requirement would be cleaning (single-PLD).

Q: do we optimize the vascular voxel exclusion (this would mean that excluding vascular/artifactual voxels will e.g., work better for sequences with time series than those without)

### Tasks

- [ ] Add single-PLD example cases from different 3D GRASE sequences and artifact magnitudes, also without the artifact, to facilitate testing the effect of the masking
-> added for Insight46 here: /surfdrive/HolidayPics/TestVascularArtifact, now still need to add a few example cases from EPAD

#### For masking:
- [ ] Add SD image interpretation to the vascular mask, with similar distribution-based selection of high-SD voxels as with negative and positive extremes
       - [ ] Create voxel distribution of mean-median, and exclude outliers
       - [ ] Voxels need to be spatially connected
- [ ] Test this with the Insight46 3D GRaSE scans, but also with Philips fat saturation artifacts
- [ ] Create boolean for SD-based masking

#### Signal correction (perhaps move this to another future issue)
- [ ] Get extracerebral vascular signal (i.e., carotid, CoW) and remove temporal correlations from the cerebral signal
- [ ] Use ICA/PCA?
- [ ] Could use PC-MRA or pseudo-MRA from T1w to see where the vessels are #1354
- [ ] Feedback to:
Thomas, David <d.thomas@ucl.ac.uk>; j.petr <j.petr@hzdr.de>; Michael Chappell <Michael.Chappell@nottingham.ac.uk>
Kuijer, J.P.A. (Joost) <jpa.kuijer@amsterdamumc.nl>; Dijsselhof, M.B.J. (Mathijs) <m.b.dijsselhof@amsterdamumc.nl>; Matthias Guenther <matthias.guenther@mevis.fraunhofer.de>

### How to test
```
No artefact - little
/home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/insight46/derivatives/ExploreASL/sub-11030012_2/ASL_1/PWI.nii.gz
Less artefact
/home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/insight46/derivatives/ExploreASL/sub-10015124_1/ASL_1/PWI.nii.gz
/home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/insight46/derivatives/ExploreASL/sub-10024822_1/ASL_1/PWI.nii.gz
Middle artefact
/home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/insight46/derivatives/ExploreASL/sub-10015124_2/ASL_1/PWI.nii.gz
/home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/insight46/derivatives/ExploreASL/sub-10371425_2/ASL_1/PWI.nii.gz
/home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/insight46/derivatives/ExploreASL/sub-11320529_1/ASL_1/PWI.nii.gz
More artefact
/home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/insight46/derivatives/ExploreASL/sub-12025125_1/ASL_1/PWI.nii.gz
/home/mdijsselhof/lood_storage/divi/Projects/ExploreASL/insight46/derivatives/ExploreASL/sub-10075012_2/ASL_1/PWI.nii.gz
```
### Release notes

#1355 Improve vascular masking using the SD image

**Comment by HenkMutsaerts** [comment]
Michael Chappell:

It is an interesting challenge. I think the multi-PLD and single-PLD are different because you have hope of separating vascular contributions in modelling with multi-PLD. This work routinely with a lot of multi-PLD (for example it seems fine with the GRASE in the UK Biobank ASL), but of course relies on the separability of the kinetic data present in multi-PLD. The contribution is inherently not separable in single-PLD. It feels like the best bet might be masking, but defining the mask in an individual will be tricky - you can make a good guess where the artefact will appear (but will be a bit variable) and what the effect of GRASE blurring will be. Trying to separate based on time series in single-PLD, e.g. using correlation or ICA/PCA, sounds nice. But the majority of the macrovascular signal will not be fluctuating -  thus any component you might be able to remove will only be part of the contribution. You might hope to identify a spatial component that corresponds to the vascular artefact and thus build your mask - but not sure about that.
 
Michael

**Comment by HenkMutsaerts** [comment]
Dave Thomas:

For context – as well as the direct intravascular contamination that really needs multi-PLD to identify (as Michael mentioned), for a multi-shot 3D GRASE acquisition in which segmentation has been done along the partition encoding (head-foot) direction, we also have a more ‘classic’ flow effect due to phase inconsistencies of the IV signal between shots, which appears as smeared signal (can be bright or dark) in the partition encoding direction. This varies a lot from average to average, depending on where in the cardiac cycle the different partitions for each average have been acquired, and so this is the part we thought might be identifiable by looking at the voxelwise single-PLD SD, and then either deriving a mask from high SD voxels or trying to estimate the ‘constant’ signal contribution in those voxels and using that…
 
We have a few studies where this artefact appears in many subjects. One way to avoid it of course is to segment along the EPI PE direction only, but segmenting along the partition encoding direction has the advantage of reducing the number of refocusing pulses and so is more effective at reducing the overall echo train length. So that was our original reason/motivation for doing that.
