### ISSUE TITLE
Fix import for Philips Look-Locker

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1366]
### Description

Two things are not imported correctly in Philips Look-Locker.

### Tasks

- [x] Fix import of Flavors Philips_PASL_2DEPI_3.2.2.0_LookLocker_1 and Philips_PASL_2DEPI_5.1.7.2_LookLocker_1. These two things below are not fixed in flavors.
- [x] TR should be not taken as the shorter TR from DICOM - as this is TR for each volume and not the Cycle duration (ms) =		4150; (I put it to studyPar.json, but it should be read automatically)
- [x] TR for M0 are not correct, again, not 300 in total, but 300 ms is each step. Moreover, M0 seems to be an inversion recovery, so that has to be considered as well and somehow saved in BIDS (this is currently ignored completely).

### Release notes

Fix TR import for Philips Look-Locker ASL.
