### ISSUE TITLE
xASL_fopen & xASL_fclose

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1371]
### Description

`xASL_io_ReadJson` performs `fopen` and `fclose`.

The usual `fopen` and `fclose` will give an unidentifiable error that has too little specific information, when a file is read-only. Easiest fix is just to add a permission check, and give an error or warning that tells the user to fix the read/write permissions.

Alternatively, should we perform a permission check on the full folder-subfolders of a studyPath?

### Tasks

- [ ] Create `xASL_fopen` that does a read/write permissions check before creating/touching a file
- [ ] The same for `xASL_fclose`
- [ ] Alternatively, if we only use fopen/fclose rarely (e.g., inside `xASL_io_ReadJson` only), we could add this permission check & warning to `xASL_io_ReadJson` only.

### How to test

* Make a `dataPar.json` read-only, and run ExploreASL.
* Make a studyPath and all subdirectories read-only and run ExploreASL.

### Release notes

Required: summarize the changes for the release notes here
