### ISSUE TITLE
Motion Threshold for outlier exclusion 

### ISSUE THREAD

**Issue by anoukschrantee** [ExploreASL/ExploreASL#1375]
### Description

To incude the possibility to choose a fixed threshold for the exclusion of motion spikes (as alternative to the threshold-free spike removal method). 

### Tasks

- [x] Implement removal of spike frames from PWI using a chosen NDV threshold in function xASL_wrp_RealignASL(x, bASL).
- [x] Write the excluded frames per scan to matfile  -> HENK: was already fixed before
- [x] Provide mean NDV before and after exclusion of the scrubbed frames -> HENK: was already fixed before
- [x] Add new parameter to `https://github.com/ExploreASL/Documentation/blob/master/source/ProcessingParameters.md`

### How to test

Add `x.modules.asl.SpikeRemovalAbsoluteThreshold` to `dataPar.json` (e.g., 0.05 mm)

### Release notes

Add an option for absolute threshold on motion spike removal.

**Comment by HenkMutsaerts** [comment]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/27774254/231361626-031aeb84-9afb-4d47-9f8b-d848e120208c.png">
Why did you remove this check?
