### ISSUE TITLE
`xASL_bids_Add2ParticipantsTSV` crashes

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1376]
### Description

`xASL_bids_Add2ParticipantsTSV` crashes

### Tasks

- [x] `xASL_bids_Add2ParticipantsTSV` `x.SESSIONS` & `tempSessionNames` were transposed
- [x] `xASL_module_Population`: improve template warning
- [x] `xASL_bids_BIDSifyASLJSON`: studyPar instead of dataPar: warning needs improvement

### How to test

Very minor issue, no testing required

### Release notes

#1376: Fix bug `xASL_bids_Add2ParticipantsTSV`
