### ISSUE TITLE
Compilation dcmTK MEX on Apple

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1379]
### Description

Both for Apple Intel and the new Silicon processor architecture, we still need to recompile dcmtk's MEX. We got quite far but need to recompile two static libraries to fully enable compiling dcmtk MEX.

### Tasks

- [x] Compiling residual static libraries using MacPort on Silicon Mac M1 by Jan
- [x] Use DCMTK 3.6.9 library without ICU lib. Copy the setup from Luna/Flux.
- [x] Compile MEX for Intel Mac - this works already using HZDR servers. There might be some minor issues with extra warnings etc. But we have compiled the newest MEX version in #1516 and this should work everywhere.
- [x] Merge #1446 first
- [x] Compile all Mac version (intel+silicon) based on CPP from #1516 
- [x] Henk will test if the Mex file runs on his computer - just to read a single DICOM file without crashing or skipping to SPM_dicom_read

### Release notes

dcmTK MEX for Apple Silicon

**Comment by HenkMutsaerts** [comment]
See previous discussions:

```
Error using mex
clang: error: no such file or directory: '/opt/homebrew/Cellar/dcmtk/3.6.7/lib/libiconv.a'
clang: error: no such file or directory: '/opt/homebrew/Cellar/dcmtk/3.6.7/lib/libz.a'
clang: error: no such file or directory: '/opt/homebrew/Cellar/dcmtk/3.6.7/lib/libxml2.a'
```

OR

```
9 warnings generated.

/usr/bin/xcrun -sdk macosx13.1 clang++ -c -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   -DMATLAB_MEX_FILE  -I"/Applications/MATLAB_R2022b_Beta.app/extern/include" -I"/opt/homebrew/Cellar/dcmtk/3.6.7/include/" -I"/Applications/MATLAB_R2022b_Beta.app/simulink/include" -fno-common -arch arm64 -mmacosx-version-min=13.1 -fexceptions -v -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fobjc-arc -std=c++11 -stdlib=libc++  -O2 -fwrapv -DNDEBUG "/Applications/MATLAB_R2022b_Beta.app/extern/version/cpp_mexapi_version.cpp" -o /var/folders/4j/1yvbsnc91nq2kr_p2295_7yc0000gn/T/mex_22403587796556_70939/cpp_mexapi_version.o
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple arm64-apple-macosx13.1.0 -Wundef-prefix=TARGET_OS_ -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name cpp_mexapi_version.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -fno-strict-return -fno-rounding-math -funwind-tables=2 -fobjc-msgsend-selector-stubs -target-sdk-version=13.1 -fvisibility-inlines-hidden-static-local-var -target-cpu apple-m1 -target-feature +v8.5a -target-feature +fp-armv8 -target-feature +neon -target-feature +crc -target-feature +crypto -target-feature +dotprod -target-feature +fp16fml -target-feature +ras -target-feature +lse -target-feature +rdm -target-feature +rcpc -target-feature +zcm -target-feature +zcz -target-feature +fullfp16 -target-feature +sm4 -target-feature +sha3 -target-feature +sha2 -target-feature +aes -target-abi darwinpcs -fallow-half-arguments-and-returns -debugger-tuning=lldb -target-linker-version 820.1 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -D MATLAB_DEFAULT_RELEASE=R2017b -D USE_MEX_CMD -D MATLAB_MEX_FILE -I /Applications/MATLAB_R2022b_Beta.app/extern/include -I /opt/homebrew/Cellar/dcmtk/3.6.7/include/ -I /Applications/MATLAB_R2022b_Beta.app/simulink/include -D NDEBUG -stdlib=libc++ -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/local/include -internal-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -O2 -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -Wno-reserved-identifier -Wno-gnu-folding-constant -Wno-cast-function-type -Wno-bitwise-instead-of-logical -std=c++11 -fdeprecated-macro -fdebug-compilation-dir=/Users/hjmutsaerts/ExploreASL/ExploreASL/External/DCMTK -ferror-limit 19 -fwrapv -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fno-cxx-modules -fobjc-arc -fobjc-arc-exceptions -fcxx-exceptions -fexceptions -fmax-type-align=16 -vectorize-loops -vectorize-slp -clang-vendor-feature=+messageToSelfInClassMethodIdReturnType -clang-vendor-feature=+disableInferNewAvailabilityFromInit -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -clang-vendor-feature=+enableAggressiveVLAFolding -clang-vendor-feature=+revert09abecef7bbf -clang-vendor-feature=+thisNoAlignAttr -clang-vendor-feature=+thisNoNullAttr -mllvm -disable-aligned-alloc-awareness=1 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /var/folders/4j/1yvbsnc91nq2kr_p2295_7yc0000gn/T/mex_22403587796556_70939/cpp_mexapi_version.o -x c++ /Applications/MATLAB_R2022b_Beta.app/extern/version/cpp_mexapi_version.cpp
clang -cc1 version 14.0.0 (clang-1400.0.29.202) default target arm64-apple-darwin22.3.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/MATLAB_R2022b_Beta.app/extern/include
 /opt/homebrew/Cellar/dcmtk/3.6.7/include
 /Applications/MATLAB_R2022b_Beta.app/simulink/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks (framework directory)
End of search list.

/usr/bin/xcrun -sdk macosx13.1 clang++ -static -Wl,-twolevel_namespace -undefined error -arch arm64 -mmacosx-version-min=13.1 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -framework Cocoa   -shared -O -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b_Beta.app/extern/lib/maca64/mexFunction.map" -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b_Beta.app/extern/lib/maca64/c_exportsmexfileversion.map" -Wl,-U,_mexCreateMexFunction -Wl,-U,_mexDestroyMexFunction -Wl,-U,_mexFunctionAdapter -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b_Beta.app/extern/lib/maca64/cppMexFunction.map" /var/folders/4j/1yvbsnc91nq2kr_p2295_7yc0000gn/T/mex_22403587796556_70939/xASL_mex_DcmtkRead.o /var/folders/4j/1yvbsnc91nq2kr_p2295_7yc0000gn/T/mex_22403587796556_70939/cpp_mexapi_version.o   -L"/Applications/MATLAB_R2022b_Beta.app/bin/maca64" /opt/homebrew/Cellar/dcmtk/3.6.7/lib/libdcmdata.a /opt/homebrew/Cellar/dcmtk/3.6.7/lib/libofstd.a /opt/homebrew/Cellar/dcmtk/3.6.7/lib/liboflog.a -lm -lpthread -lmx -lmex -Bstatic -lmat -lstdc++ -L"/Applications/MATLAB_R2022b_Beta.app/extern/bin/maca64"  -lMatlabDataArray -lMatlabEngine -o xASL_mex_DcmtkRead.mexmaca64
Error using mex
Undefined symbols for architecture arm64:
  "_deflate", referenced from:
      DcmZLibOutputFilter::compress(void const*, long long, bool) in
      libdcmdata.a(dcostrmz.cc.o)
  "_deflateEnd", referenced from:
      DcmZLibOutputFilter::~DcmZLibOutputFilter() in libdcmdata.a(dcostrmz.cc.o)
  "_deflateInit2_", referenced from:
      DcmZLibOutputFilter::DcmZLibOutputFilter() in libdcmdata.a(dcostrmz.cc.o)
  "_iconv", referenced from:
      OFCharacterEncoding::Implementation::convert(OFString&, char const*, unsigned long) in
      libofstd.a(ofchrenc.cc.o)
  "_iconv_close", referenced from:
      OFCharacterEncoding::Implementation::~Implementation() in libofstd.a(ofchrenc.cc.o)
  "_iconv_open", referenced from:
      OFCharacterEncoding::Implementation::create(OFString const&, OFString const&,
      OFCondition&) in libofstd.a(ofchrenc.cc.o)
  "_iconvctl", referenced from:
      OFCharacterEncoding::Implementation::getConversionFlags() const in
      libofstd.a(ofchrenc.cc.o)
      OFCharacterEncoding::Implementation::setConversionFlags(unsigned int) in
      libofstd.a(ofchrenc.cc.o)
  "_inflate", referenced from:
      DcmZLibInputFilter::decompress(void const*, long long) in libdcmdata.a(dcistrmz.cc.o)
  "_inflateEnd", referenced from:
      DcmZLibInputFilter::~DcmZLibInputFilter() in libdcmdata.a(dcistrmz.cc.o)
  "_inflateInit2_", referenced from:
      DcmZLibInputFilter::DcmZLibInputFilter() in libdcmdata.a(dcistrmz.cc.o)
  "_inflateInit_", referenced from:
      DcmZLibInputFilter::DcmZLibInputFilter() in libdcmdata.a(dcistrmz.cc.o)
  "_locale_charset", referenced from:
      OFCharacterEncoding::Implementation::getLocaleEncoding() in libofstd.a(ofchrenc.cc.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

BY MAARTEN:
I tried a rerun with the latest change (changed to User/maartenhammer/... ) from user/Henkjan, but I seem to still be missing some library.

````
/usr/bin/xcrun -sdk macosx13.1 clang++ -static -Wl,-twolevel_namespace -undefined error -arch arm64 -mmacosx-version-min=13.1 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -framework Cocoa   -shared -O -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b_Beta.app/extern/lib/maca64/mexFunction.map" -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b_Beta.app/extern/lib/maca64/c_exportsmexfileversion.map" -Wl,-U,_mexCreateMexFunction -Wl,-U,_mexDestroyMexFunction -Wl,-U,_mexFunctionAdapter -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b_Beta.app/extern/lib/maca64/cppMexFunction.map" /var/folders/ng/z294vt5n3459lpps67pg8f9c0000gn/T/mex_281597047940_1054/xASL_mex_DcmtkRead.o /var/folders/ng/z294vt5n3459lpps67pg8f9c0000gn/T/mex_281597047940_1054/cpp_mexapi_version.o   -L"/Applications/MATLAB_R2022b_Beta.app/bin/maca64" /opt/homebrew/Cellar/dcmtk/3.6.7/lib/libdcmdata.a /opt/homebrew/Cellar/dcmtk/3.6.7/lib/libofstd.a /opt/homebrew/Cellar/dcmtk/3.6.7/lib/liboflog.a /opt/homebrew/opt/libiconv/lib/libiconv.a -lm /opt/homebrew/opt/zlib/lib/libz.a /Users/maartenhammer/Documents/libxml2/libxml2.a -lpthread -lmx -lmex -Bstatic -lmat -lstdc++ -L"/Applications/MATLAB_R2022b_Beta.app/extern/bin/maca64"  -lMatlabDataArray -lMatlabEngine -o xASL_mex_DcmtkRead.mexmaca64
Error using mex
Undefined symbols for architecture arm64:
  "_iconv", referenced from:
      OFCharacterEncoding::Implementation::convert(OFString&, char const*, unsigned long) in
      libofstd.a(ofchrenc.cc.o)
  "_iconv_close", referenced from:
      OFCharacterEncoding::Implementation::~Implementation() in libofstd.a(ofchrenc.cc.o)
  "_iconv_open", referenced from:
      OFCharacterEncoding::Implementation::create(OFString const&, OFString const&, OFCondition&) in
      libofstd.a(ofchrenc.cc.o)
  "_iconvctl", referenced from:
      OFCharacterEncoding::Implementation::getConversionFlags() const in libofstd.a(ofchrenc.cc.o)
      OFCharacterEncoding::Implementation::setConversionFlags(unsigned int) in libofstd.a(ofchrenc.cc.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

https://github.com/QIICR/dcmqi/issues/395
A comparable github issue for other people trying to compile DCMTK

BY HENK final attempt:

```
/usr/bin/xcrun -sdk macosx13.1 clang++ -c -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   -DMATLAB_MEX_FILE  -I"/Applications/MATLAB_R2022b_Beta.app/extern/include" -I"/opt/homebrew/Cellar/dcmtk/3.6.7/include/" -I"/Applications/MATLAB_R2022b_Beta.app/simulink/include" -fno-common -arch arm64 -mmacosx-version-min=13.1 -fexceptions -v -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fobjc-arc -std=c++11 -stdlib=libc++  -O2 -fwrapv -DNDEBUG "/Applications/MATLAB_R2022b_Beta.app/extern/version/cpp_mexapi_version.cpp" -o /var/folders/4j/1yvbsnc91nq2kr_p2295_7yc0000gn/T/mex_22629675273958_12223/cpp_mexapi_version.o
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple arm64-apple-macosx13.1.0 -Wundef-prefix=TARGET_OS_ -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name cpp_mexapi_version.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -fno-strict-return -fno-rounding-math -funwind-tables=2 -fobjc-msgsend-selector-stubs -target-sdk-version=13.1 -fvisibility-inlines-hidden-static-local-var -target-cpu apple-m1 -target-feature +v8.5a -target-feature +fp-armv8 -target-feature +neon -target-feature +crc -target-feature +crypto -target-feature +dotprod -target-feature +fp16fml -target-feature +ras -target-feature +lse -target-feature +rdm -target-feature +rcpc -target-feature +zcm -target-feature +zcz -target-feature +fullfp16 -target-feature +sm4 -target-feature +sha3 -target-feature +sha2 -target-feature +aes -target-abi darwinpcs -fallow-half-arguments-and-returns -debugger-tuning=lldb -target-linker-version 820.1 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -D MATLAB_DEFAULT_RELEASE=R2017b -D USE_MEX_CMD -D MATLAB_MEX_FILE -I /Applications/MATLAB_R2022b_Beta.app/extern/include -I /opt/homebrew/Cellar/dcmtk/3.6.7/include/ -I /Applications/MATLAB_R2022b_Beta.app/simulink/include -D NDEBUG -stdlib=libc++ -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/local/include -internal-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -O2 -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -Wno-reserved-identifier -Wno-gnu-folding-constant -Wno-cast-function-type -Wno-bitwise-instead-of-logical -std=c++11 -fdeprecated-macro -fdebug-compilation-dir=/Users/hjmutsaerts/ExploreASL/ExploreASL/External/DCMTK -ferror-limit 19 -fwrapv -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fno-cxx-modules -fobjc-arc -fobjc-arc-exceptions -fcxx-exceptions -fexceptions -fmax-type-align=16 -vectorize-loops -vectorize-slp -clang-vendor-feature=+messageToSelfInClassMethodIdReturnType -clang-vendor-feature=+disableInferNewAvailabilityFromInit -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -clang-vendor-feature=+enableAggressiveVLAFolding -clang-vendor-feature=+revert09abecef7bbf -clang-vendor-feature=+thisNoAlignAttr -clang-vendor-feature=+thisNoNullAttr -mllvm -disable-aligned-alloc-awareness=1 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /var/folders/4j/1yvbsnc91nq2kr_p2295_7yc0000gn/T/mex_22629675273958_12223/cpp_mexapi_version.o -x c++ /Applications/MATLAB_R2022b_Beta.app/extern/version/cpp_mexapi_version.cpp
clang -cc1 version 14.0.0 (clang-1400.0.29.202) default target arm64-apple-darwin22.3.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/MATLAB_R2022b_Beta.app/extern/include
 /opt/homebrew/Cellar/dcmtk/3.6.7/include
 /Applications/MATLAB_R2022b_Beta.app/simulink/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks (framework directory)
End of search list.

/usr/bin/xcrun -sdk macosx13.1 clang++ -static -Wl,-twolevel_namespace -undefined error -arch arm64 -mmacosx-version-min=13.1 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -framework Cocoa   -shared -O -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b_Beta.app/extern/lib/maca64/mexFunction.map" -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b_Beta.app/extern/lib/maca64/c_exportsmexfileversion.map" -Wl,-U,_mexCreateMexFunction -Wl,-U,_mexDestroyMexFunction -Wl,-U,_mexFunctionAdapter -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b_Beta.app/extern/lib/maca64/cppMexFunction.map" /var/folders/4j/1yvbsnc91nq2kr_p2295_7yc0000gn/T/mex_22629675273958_12223/xASL_mex_DcmtkRead.o /var/folders/4j/1yvbsnc91nq2kr_p2295_7yc0000gn/T/mex_22629675273958_12223/cpp_mexapi_version.o   -L"/Applications/MATLAB_R2022b_Beta.app/bin/maca64" /opt/homebrew/Cellar/dcmtk/3.6.7/lib/libdcmdata.a /opt/homebrew/Cellar/dcmtk/3.6.7/lib/libofstd.a /opt/homebrew/Cellar/dcmtk/3.6.7/lib/liboflog.a /opt/homebrew/opt/libiconv/lib/libiconv.a -lm /opt/homebrew/opt/zlib/lib/libz.a /Users/hjmutsaerts/ExploreASL/libxml2/libxml2.a -lpthread -lmx -lmex -Bstatic -lmat -lstdc++ -L"/Applications/MATLAB_R2022b_Beta.app/extern/bin/maca64"  -lMatlabDataArray -lMatlabEngine -o xASL_mex_DcmtkRead.mexmaca64
Error using mex
Undefined symbols for architecture arm64:
  "_iconv", referenced from:
      OFCharacterEncoding::Implementation::convert(OFString&, char const*, unsigned long) in
      libofstd.a(ofchrenc.cc.o)
  "_iconv_close", referenced from:
      OFCharacterEncoding::Implementation::~Implementation() in libofstd.a(ofchrenc.cc.o)
  "_iconv_open", referenced from:
      OFCharacterEncoding::Implementation::create(OFString const&, OFString const&,
      OFCondition&) in libofstd.a(ofchrenc.cc.o)
  "_iconvctl", referenced from:
      OFCharacterEncoding::Implementation::getConversionFlags() const in
      libofstd.a(ofchrenc.cc.o)
      OFCharacterEncoding::Implementation::setConversionFlags(unsigned int) in
      libofstd.a(ofchrenc.cc.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by HenkMutsaerts** [comment]
Pieper says:

It's an interesting issue here - it seems to me this isn't just a mac issue, but anytime someone has a system-installed dcmtk but wants to build locally they may end up getting similar errors if some other package's headers (sndfile in this case) are in the same include directory with the system dcmtk.

So perhaps indeed it is a version issue, and that it takes the wrong `iconv` (the macOS default but not the one needed for dcmtk)?
