### ISSUE TITLE
Visit importing goes wrong

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1384]
### Description

Visit importing goes wrong in `xASL_imp_DetermineStructureFromSourcedata`. This function is also a mess to read, so I will revamp it. One part of the revamp is that visit/session (legacy) vs. session/run (BIDS) is not chosen. Because we use legacy in `sourceStructure.json`, I will move all to legacy (we can tweak later).

JAN: I agree that a single terminology should be used. But to facilitate future conversion, can you use BIDS notation where it's already in BIDS and make comments like Legacy notation/BIDS notation - just an idea to save time for future, but keep stuff clean. Especially since by changing it here, you'll have to change it in many many other functions. So we shouldn't loose time cleaning stuff there and back (comments will solve that at a reasonable time investment). One last argument - while processing is in Legacy, a large part of import is very close to BIDS, so we shouldn't get it more far if not absolutely necessary. Though again - I agree that stuff needs to be comprehensible.

HENK: Sure, but sourceStructure is clearly in legacy. So I would keep all in legacy until we simply rename sessions->runs and visits->sessions.

For the current bug, see Flavor branch bug-#1384_VisitImportFailing. This needs fixing in `xASL_imp_DetermineStructureFromSourcedata` and when comparing how we do this for sessions and others, you'll anticipate that this code is a bit of a maze and difficult to read, hence why I wanted to fix the readability to make the token regexp functionality equal.
WHY WE NEED REGEXP in token definition? We need the token to be flexible (depending also perhaps on how we decide in our previous discussion in #1388.

### Tasks
- [ ] Revamp 1: the "v" stands for vector, and the difference between e.g., vVisitIDs & VisitIDs OR vSubjectIDs & SubjectIDs is unclear; this is used interchangeably

- [ ] Function is unreadable, add comments
- [ ] Revamp part I: session -> visit
- [ ] Revamp part II: run -> session
- [x] Add visit example to FlavorDatabase. 
- [x]  Regexp for visitToken - xASL_imp_DetermineStructureFromSourcedata - line 220. #1345 
- [ ]  Check and fix all sourcestructure.jsons in flavors
- [ ]  Allow empty tokens, but set visits/sessions to 1 for empty or unrecognized tokens
- [ ]  Don't allow empty tokens for scans - exit with an error
- [ ]  Run Flavors test
- [ ] Should xASL_imp_Initialize line 146 -> token checks go to xASL_imp_CheckImportSettings?
- [ ] Should xASL_imp_ReadSourceData line 74 also be moved to xASL_imp_CheckImportSettings?

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by jan-petr** [comment]
HENK:
For DEBBIE LCBC:

```
{"folderHierarchy":["^(sub-\\d*)$","^.*(ASL-M0protocal|M0|Hd4|Hd8).*(caipi.*\\.01|_dir-RL_MEM.*\\.013)$"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["ASL-M0protocal|Hd4|M0","ASL_1","Hd8","ASL_2"], 
"tokenScanAliases":["^(perf_DEBBIE|debbie)","ASL4D","^(perf_fme|fmap_debbie)","M0"],
"bMatchDirectories":true}
```
becomes:
```
{"folderHierarchy":["^(sub-\\d*)$","^.*(Hd4|Hd8).*(caipi.*\\.01|M0_dir-RL_MEM.*\\.013|M0_dir-LR_MEM.*\\.013)$"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["Hd4","ASL_1","Hd8","ASL_2"], 
"tokenScanAliases":["caipi.*\\.01","ASL4D","M0_dir-RL_MEM.*\\.013","M0","M0_dir-LR_MEM.*\\.013","M0_RevPE"],
"bMatchDirectories":true}

**Comment by jan-petr** [comment]
HENK:
And the following for DEBBIE HZDR:
```
{"folderHierarchy":["^(sub\\d)$","^(HAD4|HAD8|M0|T1)"],
"tokenOrdering":[1,0,2,2],
"tokenSessionAliases":["HAD4|M0|T1","ASL_1","HAD8","ASL_2"],
"tokenScanAliases":["^HAD4|HAD8","ASL4D","^T1$","T1w","^M0$","M0"],
"bMatchDirectories":true}
```
becomes
```
{"folderHierarchy":["^(sub\\d)$","^(HAD|M0|T1)(4|8)"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["4","ASL_1","8","ASL_2"],
"tokenScanAliases":["^HAD","ASL4D","^T1$","T1w","^M0$","M0"],
"bMatchDirectories":true}
```
Note how tokens are not reused and the design is much simpler and easier to understand.

**Comment by jan-petr** [comment]
HENK:
Just checked with Bea, and she agreed with me to change the following (Neuro-BMC Singapore):

```
{"folderHierarchy":["(\\d{3})$","scans","\\d{1,2}.*(SAG|T2|Encoded_Images|-ss).*(Had04|Had08|TE00_TI2000|MPRAGE|FLAIR)","^resources","^DICOM","^files"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["MPRAGE","","FLAIR","","Had04","ASL_1","TE00_TI2000","ASL_1","Had08","ASL_2"], 
"tokenScanAliases":["(Encoded_Images)","ASL4D","(-ss)","M0", "(T2)","FLAIR","(SAG)","T1w"],
"bMatchDirectories":true}
```
to
```
{"folderHierarchy":["^NEURO-(\\d{3})$","scans","^\\d+.*(MPRAGE|FLAIR|Encoded_Images|-ss.*TI2000).*(Had04|Had08)","resources","^DICOM","^files"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["^Had04$","ASL_1","^Had08$","ASL_2"],
"tokenScanAliases":["^Encoded_Images$","ASL4D","^-ss_.*TI2000$","M0", "^FLAIR","FLAIR","MPRAGE$","T1w"],
"bMatchDirectories":true}
```
* Note that the M0, MPRAGE, and FLAIR are now more specifically defined
* Only HAD04 & HAD08 have a session, others are defaulted to session 1 (and if they are anatomical, they are not put into an ASL_1 subfolder by import)
* Note that the lower sourceStructure is easier to interpret, for the one above you need to try to think of all possible combinations, use scan tokens as session tokens
