### ISSUE TITLE
Token order error in flavors import

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1388]
### Description

An error crashing several flavors probably related to merging some NII files.

The issues was the number of tokens in token order having to match the number of brackets in folderHierarchy. In regexp, ( ) is not reserved for tokens only and is also used for grouping. Therefore the number of tokens in tokenOrder must by equal or smaller than number of brackets, but not necessarily equal.

HENK: it should in our use be reserved for tokens only, otherwise it becomes tricky to interpret which brackets are tokens, and which brackets are used for grouping.

Either we switch the type of brackets, or we use the grouping bracket in the token definition, not in `folderHierarchy`. Let's discuss. But please provide the examples here that crash so I can check as well.

-> ALSO: we need to copy (can be empty) folders from the clinical scan sessions that we are not interested in, to ensure also that our `sourceStructure.json` works in those cases.

### Tasks

- [x] Fix bugs in previous commits
- [x] Add missing tags to the SPM version of DICOM read
- [x] Allow unused tokens, but print a warning
- [x] Allow token reusing, but print a warning
- [x] Allow missing tokenSessionAlias in sourcestructure.json

### Release notes

Allow unused and reused tokens in sourcestructure.

**Comment by jan-petr** [comment]
COMPARISON TABLE:
                            flavor                                 dataset                   name                                                message                                  
    _______________________________________________________    _______________    __________________________    __________________________________________________________________________

    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-ICAD0771/anat/sub-ICAD0771_T1w.json'                              }
    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-ICAD0771/anat/sub-ICAD0771_T1w.nii.gz'                            }
    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-ICAD0771/perf/sub-ICAD0771_m0scan.json'                           }
    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-ICAD0771/perf/sub-ICAD0771_m0scan.nii.gz'                         }
    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-ICAD0771/perf/sub-ICAD0771_asl.json'      }
    {'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'               }    {'rawdata'    }    {'Missing file'          }    {'/sub-P01/perf/sub-P01_m0scan.json'                                     }
    {'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'               }    {'rawdata'    }    {'Missing file'          }    {'/sub-P01/perf/sub-P01_m0scan.nii.gz'                                   }
    {'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-P01/perf/sub-P01_asl.json'                }
    {'Philips_PCASL_2DEPI_3.2.2.1_1'                      }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_m0scan.json'                                   }
    {'Philips_PCASL_2DEPI_3.2.2.1_1'                      }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_m0scan.nii.gz'                                 }
    {'Philips_PCASL_2DEPI_3.2.2.1_1'                      }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'              }
    {'Philips_PCASL_2DEPI_5.1.9.1_GBM_1'                  }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub0004/anat/sub-Sub0004_T1w.json'                                }
    {'Philips_PCASL_2DEPI_5.1.9.1_GBM_1'                  }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub0004/anat/sub-Sub0004_T1w.nii.gz'                              }
    {'Philips_PCASL_2DEPI_5.1.9.1_GBM_1'                  }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub0004/perf/sub-Sub0004_asl.json'        }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/anat/sub-sub1_FLAIR.json'                                    }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/anat/sub-sub1_FLAIR.nii.gz'                                  }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/anat/sub-sub1_T1w.json'                                      }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/anat/sub-sub1_T1w.nii.gz'                                    }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_m0scan.json'                                   }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_m0scan.nii.gz'                                 }
    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-ICAD0771_1/ASL_1/M0.json'                              }
    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-ICAD0771_1/ASL_1/M0.nii.gz'                            }
    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-ICAD0771_1/T1.json'                                    }
    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-ICAD0771_1/T1.nii.gz'                                  }
    {'Philips_PASL_2DEPI_5.4.0.2_LookLocker_1'            }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-ICAD0771_1/ASL_1/ASL4D.json'   }
    {'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-P01_1/ASL_1/M0.json'                                   }
    {'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-P01_1/ASL_1/M0.nii.gz'                                 }
    {'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-P01_1/ASL_1/ASL4D.json'        }
    {'Philips_PCASL_2DEPI_3.2.2.1_1'                      }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                                  }
    {'Philips_PCASL_2DEPI_3.2.2.1_1'                      }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                                }
    {'Philips_PCASL_2DEPI_3.2.2.1_1'                      }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'       }
    {'Philips_PCASL_2DEPI_5.1.9.1_GBM_1'                  }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub0004_1/T1.json'                                     }
    {'Philips_PCASL_2DEPI_5.1.9.1_GBM_1'                  }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub0004_1/T1.nii.gz'                                   }
    {'Philips_PCASL_2DEPI_5.1.9.1_GBM_1'                  }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub0004_1/ASL_1/ASL4D.json'    }
    {'Philips_PCASL_2DEPI_PARREC_2'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataPar.json'                                              }
    {'Philips_PCASL_2DEPI_PARREC_2'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataset_description.json'                                  }
    {'Philips_PCASL_2DEPI_PARREC_2'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub01_1/ASL_1/ASL4D.json'                              }
    {'Philips_PCASL_2DEPI_PARREC_2'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub01_1/ASL_1/ASL4D.nii.gz'                            }
    {'Philips_PCASL_2DEPI_PARREC_2'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub01_1/ASL_1/ASL4Dcontext.tsv'                        }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/FLAIR.json'                                     }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/FLAIR.nii.gz'                                   }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/T1.json'                                        }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/T1.nii.gz'                                      }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/M0.json'          }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'            }    {'Both'       }    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-sub1_1/ASL_1/M0.nii.gz'}
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataPar.json'                                              }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataset_description.json'                                  }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/ASL_1/ASL4D.json'                           }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/ASL_1/ASL4D.nii.gz'                         }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/ASL_1/ASL4Dcontext.tsv'                     }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/FLAIR.json'                                 }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/FLAIR.nii.gz'                               }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/T1.json'                                    }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/T1.nii.gz'                                  }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/ASL_1/ASL4D.json'                           }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/ASL_1/ASL4D.nii.gz'                         }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/ASL_1/ASL4Dcontext.tsv'                     }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/FLAIR.json'                                 }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/FLAIR.nii.gz'                               }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/T1.json'                                    }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/T1.nii.gz'                                  }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/ASL_1/ASL4D.json'                           }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/ASL_1/ASL4D.nii.gz'                         }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/ASL_1/ASL4Dcontext.tsv'                     }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/FLAIR.json'                                 }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/FLAIR.nii.gz'                               }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/T1.json'                                    }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/T1.nii.gz'                                  }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataPar.json'                                              }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataset_description.json'                                  }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_1/ASL4D.json'                         }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_1/ASL4D.nii.gz'                       }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_1/ASL4Dcontext.tsv'                   }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_1/M0.json'                            }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_1/M0.nii.gz'                          }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_1/M0_RevPE.json'                      }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_1/M0_RevPE.nii.gz'                    }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_2/ASL4D.json'                         }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_2/ASL4D.nii.gz'                       }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1100189_1/ASL_2/ASL4Dcontext.tsv'                   }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataPar.json'                                              }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataset_description.json'                                  }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/ASL4D.json'                               }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/ASL4D.nii.gz'                             }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/ASL4Dcontext.tsv'                         }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/M0.json'                                  }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/M0.nii.gz'                                }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_2/ASL4D.json'                               }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_2/ASL4D.nii.gz'                             }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_2/ASL4Dcontext.tsv'                         }
    {'Siemens_VE11_NiftiOnly_1'                           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataPar.json'                                              }
    {'Siemens_VE11_NiftiOnly_1'                           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/dataset_description.json'                                  }
    {'Siemens_VE11_NiftiOnly_1'                           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-D40210_1/FLAIR.json'                                   }
    {'Siemens_VE11_NiftiOnly_1'                           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-D40210_1/FLAIR.nii.gz'                                 }
    {'Siemens_VE11_NiftiOnly_1'                           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-D40210_1/T1.json'                                      }
    {'Siemens_VE11_NiftiOnly_1'                           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-D40210_1/T1.nii.gz'                                    }

**Comment by HenkMutsaerts** [comment]
You still need to convince me unfortunately, because allowing a token to be multi-interpretable is potentially unnecessarily complicated. But if we have a clear use case, I agree with you, and we would need to document this.

`/FlavorDatabase/Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1/sourceStructure.json`

uses for `folderHierarchy`:

"^(perf_DEBBIE|perf_fme|debbie|fmap_debbie).*(ASL-M0protocal|M0|Hd4|Hd8).*(caipi.*\\.01|_dir-RL_MEM.*\\.013|_dir-LR_MEM.*\\.013)$"],

which can be replaced by, and we don't need brackets other than tokens

"^.*(Hd4|Hd8).*(caipi|M0_dir-RL|M0_dir-LR).*$"],

(note how much easier and less potentially confusing for a user)

Also, tokenScanAliases is now: 

`["^caipi","ASL4D","dir-RL","M0","dir-LR","M0PERev"]`

which can be improved for readability by

`["^caipi","ASL4D","^M0_dir-RL$","M0","^M0_dir-LR$","M0PERev"]`

(so adding M0 as prefix for the directionality)

And you don't need to say that M0 belongs to session ASL_1 (it is default that if a token doesn't have a specific session, it is session 1, like anatomical scans). I do agree that this is perhaps less clear.

**Comment by jan-petr** [comment]
/sourcedata/sub-1100131/debbie_Hd4-caipi-8TE_MEMC3.04.01
/sourcedata/sub-1100131/debbie_Hd4-caipi-8TE_MEMC3.04.012
/sourcedata/sub-1100131/debbie_Hd4-caipi-8TE_MEMC3.04.013
/sourcedata/sub-1100131/debbie_Hd4-caipi-8TE_MEMC3.04.014
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.01
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.0110
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.0111
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.0112
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.0113
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.0114
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.0115
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.012
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.013
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.014
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.015
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.016
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.017
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.018
/sourcedata/sub-1100131/debbie_Hd8-caipi_MEMC3.04.019
/sourcedata/sub-1100131/fmap_debbie_M0_dir-LR_MEMC3.04.01
/sourcedata/sub-1100131/fmap_debbie_M0_dir-LR_MEMC3.04.012
/sourcedata/sub-1100131/fmap_debbie_M0_dir-LR_MEMC3.04.013
/sourcedata/sub-1100131/fmap_debbie_M0_dir-RL_MEMC3.04.01
/sourcedata/sub-1100131/fmap_debbie_M0_dir-RL_MEMC3.04.012
/sourcedata/sub-1100131/fmap_debbie_M0_dir-RL_MEMC3.04.013

{"folderHierarchy":["^(sub-\\d*)$","^(perf_DEBBIE|perf_fme|debbie|fmap_debbie).*(ASL-M0protocal|M0|Hd4|Hd8).*(caipi.*\\.01|_dir-RL_MEM.*\\.013)$"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["ASL-M0protocal|Hd4|M0","ASL_1","Hd8","ASL_2"], 
"tokenScanAliases":["^(perf_DEBBIE|debbie)","ASL4D","^(perf_fme|fmap_debbie)","M0"],
"bMatchDirectories":true}

**Comment by jan-petr** [comment]
Regardig your comment - yes, that works for this single flavor. But in reality, there are more directories than in the flavor. And there are several subjects with different names. So all that extra tokens are designed so that it works in a whole population

**Comment by BeatrizPadrela** [comment]
I found this error
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/73699072/232238599-1e69fddf-d529-4159-a7aa-dc1ba3650c9e.png">

**Comment by HenkMutsaerts** [comment]
Just checked with Bea, and she agreed with me to change the following (Neuro-BMC Singapore):

```
{"folderHierarchy":["(\\d{3})$","scans","\\d{1,2}.*(SAG|T2|Encoded_Images|-ss).*(Had04|Had08|TE00_TI2000|MPRAGE|FLAIR)","^resources","^DICOM","^files"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["MPRAGE","","FLAIR","","Had04","ASL_1","TE00_TI2000","ASL_1","Had08","ASL_2"], 
"tokenScanAliases":["(Encoded_Images)","ASL4D","(-ss)","M0", "(T2)","FLAIR","(SAG)","T1w"],
"bMatchDirectories":true}
```
to
```
{"folderHierarchy":["^NEURO-(\\d{3})$","scans","^\\d+.*(MPRAGE|FLAIR|Encoded_Images|-ss.*TI2000).*(Had04|Had08)","resources","^DICOM","^files"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["^Had04$","ASL_1","^Had08$","ASL_2"],
"tokenScanAliases":["^Encoded_Images$","ASL4D","^-ss_.*TI2000$","M0", "^FLAIR","FLAIR","MPRAGE$","T1w"],
"bMatchDirectories":true}
```
* Note that the M0, MPRAGE, and FLAIR are now more specifically defined
* Only HAD04 & HAD08 have a session, others are defaulted to session 1 (and if they are anatomical, they are not put into an ASL_1 subfolder by import)
* Note that the lower sourceStructure is easier to interpret, for the one above you need to try to think of all possible combinations, use scan tokens as session tokens




├── 36-Encoded_Images_Had04_03_TIs_08_TEs
├── 37-Perfusion_Images_Had04_TI_1500_0ms_08_TEs
├── 38-Perfusion_Images_Had04_TI_2500_0ms_08_TEs
├── 39-Perfusion_Images_Had04_TI_3500_0ms_08_TEs
├── 40-ss_TE00_TI1700
├── 41-Encoded_Images_Had08_14_TIs_01_TEs
├── 42-Perfusion_Images_Had08_TI_1000_0ms_01_TEs
├── 43-Perfusion_Images_Had08_TI_1400_0ms_01_TEs
├── 44-Perfusion_Images_Had08_TI_1800_0ms_01_TEs
├── 45-Perfusion_Images_Had08_TI_2200_0ms_01_TEs
├── 46-Perfusion_Images_Had08_TI_2600_0ms_01_TEs
├── 47-Perfusion_Images_Had08_TI_3000_0ms_01_TEs
├── 48-Perfusion_Images_Had08_TI_3400_0ms_01_TEs
├── 49-Perfusion_Images_Had08_TI_1200_0ms_01_TEs
├── 50-Perfusion_Images_Had08_TI_1600_0ms_01_TEs
├── 51-Perfusion_Images_Had08_TI_2000_0ms_01_TEs
├── 52-Perfusion_Images_Had08_TI_2400_0ms_01_TEs
├── 53-Perfusion_Images_Had08_TI_2800_0ms_01_TEs
├── 54-Perfusion_Images_Had08_TI_3200_0ms_01_TEs
├── 55-Perfusion_Images_Had08_TI_3600_0ms_01_TEs
├── 56-ss_TE00_TI1700
├── 57-ss_TE00_TI2000
├── 6-SAG_MPRAGE_p2_NON_SS
└── 9-T2_TSE_FLAIR_AX

**Comment by HenkMutsaerts** [comment]
And the following for DEBBIE HZDR:
```
{"folderHierarchy":["^(sub\\d)$","^(HAD4|HAD8|M0|T1)"],
"tokenOrdering":[1,0,2,2],
"tokenSessionAliases":["HAD4|M0|T1","ASL_1","HAD8","ASL_2"],
"tokenScanAliases":["^HAD4|HAD8","ASL4D","^T1$","T1w","^M0$","M0"],
"bMatchDirectories":true}
```
becomes
```
{"folderHierarchy":["^(sub\\d)$","^(HAD|M0|T1)(4|8)"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["4","ASL_1","8","ASL_2"],
"tokenScanAliases":["^HAD","ASL4D","^T1$","T1w","^M0$","M0"],
"bMatchDirectories":true}
```
Note how tokens are not reused and the design is much simpler and easier to understand.

.
├── HAD4
├── HAD8
├── M0
└── T1

**Comment by HenkMutsaerts** [comment]
For DEBBIE LCBC:

```
{"folderHierarchy":["^(sub-\\d*)$","^.*(ASL-M0protocal|M0|Hd4|Hd8).*(caipi.*\\.01|_dir-RL_MEM.*\\.013)$"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["ASL-M0protocal|Hd4|M0","ASL_1","Hd8","ASL_2"], 
"tokenScanAliases":["^(perf_DEBBIE|debbie)","ASL4D","^(perf_fme|fmap_debbie)","M0"],
"bMatchDirectories":true}
```
becomes:
```
{"folderHierarchy":["^(sub-\\d*)$","^.*(Hd4|Hd8).*(caipi.*\\.01|M0_dir-RL_MEM.*\\.013|M0_dir-LR_MEM.*\\.013)$"],
"tokenOrdering":[1,0,3,2],
"tokenSessionAliases":["Hd4","ASL_1","Hd8","ASL_2"], 
"tokenScanAliases":["caipi.*\\.01","ASL4D","M0_dir-RL_MEM.*\\.013","M0","M0_dir-LR_MEM.*\\.013","M0_RevPE"],
"bMatchDirectories":true}
```


.
├── debbie_Hd4-caipi-8TE_MEMC3.04.01
├── debbie_Hd4-caipi-8TE_MEMC3.04.012
├── debbie_Hd4-caipi-8TE_MEMC3.04.013
├── debbie_Hd4-caipi-8TE_MEMC3.04.014
├── debbie_Hd8-caipi_MEMC3.04.01
├── debbie_Hd8-caipi_MEMC3.04.0110
├── debbie_Hd8-caipi_MEMC3.04.0111
├── debbie_Hd8-caipi_MEMC3.04.0112
├── debbie_Hd8-caipi_MEMC3.04.0113
├── debbie_Hd8-caipi_MEMC3.04.0114
├── debbie_Hd8-caipi_MEMC3.04.0115
├── debbie_Hd8-caipi_MEMC3.04.012
├── debbie_Hd8-caipi_MEMC3.04.013
├── debbie_Hd8-caipi_MEMC3.04.014
├── debbie_Hd8-caipi_MEMC3.04.015
├── debbie_Hd8-caipi_MEMC3.04.016
├── debbie_Hd8-caipi_MEMC3.04.017
├── debbie_Hd8-caipi_MEMC3.04.018
├── debbie_Hd8-caipi_MEMC3.04.019
├── fmap_debbie_M0_dir-LR_MEMC3.04.01
├── fmap_debbie_M0_dir-LR_MEMC3.04.012
├── fmap_debbie_M0_dir-LR_MEMC3.04.013
├── fmap_debbie_M0_dir-RL_MEMC3.04.01
├── fmap_debbie_M0_dir-RL_MEMC3.04.012
└── fmap_debbie_M0_dir-RL_MEMC3.04.013
