### ISSUE TITLE
Zenodo has wrong license and wrong authors

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1403]
### Description

Maarten just noticed a wrong author order in Zenodo. I can go to record https://zenodo.org/record/7702237 (which is our general ExploreASL record) and press the edit button, but it will tell me that I'm doing something from May 1st onward.

![image](https://user-images.githubusercontent.com/27774254/235128436-6568c9ea-bb4d-42a5-869a-7b171bee5db2.png)
![image](https://user-images.githubusercontent.com/27774254/235128504-79aa3d96-9647-4168-ba69-efc80a7ef6a2.png)

### Tasks

- [x] Is there a way for Zenodo to follow our `CITATION.cff` ? No
- [x] Add .zenodo.json with creators

### How to test

Check author order at https://zenodo.org/record/7702237

### Release notes

#1403 Fixed Zenodo citation

**Comment by maartenhammer** [comment]
Zenodo follows: 

> JSON Export
> Zenodo automatically extracts metadata about your repository from GitHub APIs. For example, the authors are determined from the repository's contributor statistics. The automatic extraction is solely a best guess. Add a .zenodo.json file the root of your repository to explicit define the metadata. The format of file is the same as for our [REST API](https://developers.zenodo.org/) (use e.g. below JSON to get started).

This is the automatically generated JSON from the zenodo page:

``` json
{
    "description": "ExploreASL v1.10.1\nVersions included software\n<p>Versions included &amp; used third-party tools (see <code>/External/README_SPM.txt</code>):</p>\n<ul>\n<li>SPM12 7219 </li>\n<li>CAT12 r1615 </li>\n<li>LST 2.0.15 </li>\n<li>dcm2niix 20220720</li>\n</ul>\nHot fixes\n<ul>\n<li>Bug #1276: Fix too time-demanding BIDS2Legacy conversion</li>\n</ul>", 
    "license": "other-open", 
    "title": "ExploreASL/ExploreASL: ExploreASL v1.10.1", 
    "version": "v1.10.1", 
    "upload_type": "software", 
    "publication_date": "2023-01-05", 
    "creators": [
        {
            "name": "Michael Stritt"
        }, 
        {
            "affiliation": "Amsterdam University Medical Centers", 
            "name": "Henk Mutsaerts"
        }, 
        {
            "name": "Jan Petr"
        }, 
        {
            "name": "Beatriz Padrela"
        }, 
        {
            "affiliation": "Amsterdam UMC, VUmc", 
            "name": "Mathijs Dijsselhof"
        }, 
        {
            "affiliation": "University of Toronto", 
            "name": "MauricePasternak"
        }, 
        {
            "name": "luislorenzini"
        }, 
        {
            "affiliation": "Ghent University", 
            "name": "Pieter Vandemaele"
        }, 
        {
            "name": "yevap"
        }, 
        {
            "affiliation": "Amsterdam UMC - locatie AMC", 
            "name": "Paul Groot"
        }
    ], 
    "access_right": "open", 
    "related_identifiers": [
        {
            "scheme": "url", 
            "identifier": "https://github.com/ExploreASL/ExploreASL/tree/v1.10.1", 
            "relation": "isSupplementTo"
        }, 
        {
            "scheme": "doi", 
            "identifier": "10.5281/zenodo.3905262", 
            "relation": "isVersionOf"
        }
    ]
}
``` 

This produces the following citation file: 

```BibTex
@software{michael_stritt_2023_7702237,
  author       = {Michael Stritt and
                  Henk Mutsaerts and
                  Jan Petr and
                  Beatriz Padrela and
                  Mathijs Dijsselhof and
                  MauricePasternak and
                  luislorenzini and
                  Pieter Vandemaele and
                  yevap and
                  Paul Groot},
  title        = {ExploreASL/ExploreASL: ExploreASL v1.10.1},
  month        = jan,
  year         = 2023,
  publisher    = {Zenodo},
  version      = {v1.10.1},
  doi          = {10.5281/zenodo.7702237},
  url          = {https://doi.org/10.5281/zenodo.7702237}
}
```

**Comment by maartenhammer** [comment]
- [x] Change Acces to restricted
- [x] Link HTML to License file in exploreasl
- [x] Citation.cff only has Jan & Henk-Jan should we change this there + zenodo?
