### ISSUE TITLE
Fix NOMARED flavor

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1409]
### Description

Fix quantification and parameters of NOMARED data to make CBF values reasonable, especially across subjects.

### Tasks

- [ ] Check M0-ASL scale factor, should be turned off as we use Backgroudn suppression for M0 calculation
- [ ] Fix BS correction of mean control with new BS timings (668, 1629)
- [ ] x.Q.BASIL.bInrefArt = true - probably true
- [ ] Fix PLD : 0.25:0.25:2.5
- [ ] set dispersion to true
- [ ] Check what happens with BS - correction. Which PLD it uses for mean control, how this is corrected - correct TR used?
- [ ] See if we can get BS timings from DICOMs - once we have all of them.

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
