### ISSUE TITLE
Fix multi-TE M0 processing

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1411]
### Description

For multi-TE M0s, we should take only the first shortest TE to be used for ASL scaling.
### Tasks

- [x] Identify multi-TE are being used.
- [x] Take only the shortest TE and calculate M0 image only from that TE.
- [x] Make sure that in the subsequent calculation, only that TE is used. line 250 in xASL_wrp_Quantify.
- [x] Test that DEBBIE HAD04 works now.
- [x] Take TE closest to ASL - this actually doesn't make sense as ASL and M0 are designed with short TEs. And the only reason to have longer TEs is when mutli-TE is done. So there's no reason to have M0 with multi-TE and having another TE than the shortest to be the closes to ASL. So this option is superfluous as it will always be fulfilled with shortest TE.
- [x] Make a warning that TEs are being stripped
- [x] Check that DEBBIE HAD04 CBF looks good.

### Release notes

Fix multi-TE M0 quantification by selecting shortest TE.
