### ISSUE TITLE
Warning dcm2BIDS for incomplete session/run combinations

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1413]
### Description

If we have runs >1 and sessions >1, but not all subjects have the same number of runs/sessions, then the reporting table is incomplete, this throws a warning (before #1405 this crashed). No need to prioritize this issue but it could be helpful to see why it doesn't fill up these tables.

### Tasks

- [ ] First fix other issues that are more urgent or important
- [ ] Create a flavor with one subject that has runs >1 and sessions >1 where one run (the last run) is missing in session 2 (the last session).
- [ ] Try to see where the warning comes from, for `thisSubject.globalCounts.(missing|skipped)_scans`

### How to test

Second above is the testing case.

### Release notes

Required: summarize the changes for the release notes here
