### ISSUE TITLE
Identify PERev directions correctly

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1415]
### Description

Once PERev M0 with inverted phase-encoding direction is found it assigns it automatically j and j- directions and calls in AP-PA. But sometimes, we have i an i- and LR and RL directions!!!

### Tasks

- [x] If directions are known from the DICOM, then don't change them.
- [x] If directions are j and j- - call it AP-PA, otherwise for i i-, call it LR, RL.
- [x] Test if all flavors still run

### Release notes

Correct import of PE-polar directions for M0.
