### ISSUE TITLE
Add BIDS validator to tutorials/manuals

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1434]
### Description

Running the BIDS validator should be mentioned here:

https://exploreasl.github.io/Documentation/1.10.0/Tutorials-Import/

and perhaps at other locations. If users don't run the BIDS validator, there are opportunities for errors.

### Tasks

- [x] Remove BIDS2Legacy from import tutorial
- [x] Mention BIDS validator after import and before processing in both tutorial md files
- [x] Jan: review this one:
https://github.com/ExploreASL/Documentation/pull/3
Are you able to approve my changes and implement them?

### Release notes

#1434 Improved Import Tutorial and added BIDS validator explanation

**Comment by jan-petr** [comment]
Yes. Please write what text should be added. And I'll add it to the documentaiton.
