### ISSUE TITLE
WMH alignment in rerunning ExploreASL

### ISSUE THREAD

**Issue by mervinTEE** [ExploreASL/ExploreASL#1439]
### Description

When the structural module is repeated without removing the derivatives folder, the WMH_SEGM becomes misaligned because ExploreASL assumes that it is aligned with FLAIR if provided by someone else, but ExploreASL's structural module aligns it with the T1w.

### Tasks
- [x] 1. Create a function that detects if two NIfTIs have the same dimensions, and then the same orientation (outputting if this is mat or mat0): `xASL_im_IsEqualOrientations`
- [X] Ensure that we don't revert to nii.mat0
    -> we actually do revert to nii.mat0 in several instances, if the orientation matrix nii.mat is corrupt (e.g., contains NaNs), 
         then we issue a warning.
- [X] 2. xASL_adm_CleanUpBeforeRerun: line 198 (restore back-upped ORI files):
This doesn't take anything from mat0
- [x] 3. xASL_im_CenterOfMass: add a warning when defaulting to mat0
- [x] 4. xASL_wrp_LinearReg_FLAIR2T1w: add ROI's to registration list
- [x] 5. xASL_wrp_LST_Segment_FLAIR_WMH: correct mat0 behavior
- [x] 6. Disable changeMat0 warning in xASL_wrp_LST_Segment_FLAIR_WMH

### How to test

1. Run the structural module with a T1w & FLAIR but not WMH_SEGM; check registration WMH_SEGM with T1w & FLAIR at the end of the structural module
2. Rerun the structural module after deleting the structural lock files (but keeping the BIDS2Legacy lock files); check registration WMH_SEGM with T1w & FLAIR at the end of the structural module
3. Run the structural module with a T1w & FLAIR and WMH_SEGM registered to the FLAIR (e.g., Twins population, with FLAIR from Carole); check registration WMH_SEGM with T1w & FLAIR at the end of the structural module
4. Run the structural module with a T1w & FLAIR and Lesion_T1_1.nii & Lesion_T1_2.nii

(add these examples to the TestDataSet examples)

Example by Mervin: `/Users/hjmutsaerts/ExploreASL/ASL/Structural_Registration_Test_HJM`

### Release notes

Fix WMH realignment issues after rerunning ExploreASL. Note that this doesn't fix rerunning datasets that were already processed before this fix.

**Comment by mervinTEE** [comment]
I have recently tried the following steps.

1) Rerun structural module for just one subject.
- Registration works and did not have any issues.

2) Rerun the structural module for all subjects at one go by removing lock folders of those subjects with registration issues for the structural model. 
- the registration now works for some and there are specific subjects that still have issues with registration. 

3) Rerun those subjects with issues for the third time registration issues still persist.

**Comment by mervinTEE** [comment]
/lood_storage/divi/Projects/ExploreASL/Singapore/Structural_Registration_Test/

You can find the subject here, you will find the same subject in two different folders. They are labelled by the folders names on which was processed in which manner.
