### ISSUE TITLE
DCMTK compilation on Flux

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1446]
### Description

Optimize DCMTK Linux compilation for Luna/Flux

### Tasks

- [x] Create a compilation script for HZDR and Luna
- [x] Make sure the correct script is called for each machine
- [x] Adapt Flux compilation options
- [x] Add the Flux-compiled version to GitHub
- [x] Check if the same version works on all servers
- [x] Run full testing on Flux
- [x] Close #1390 as duplicate

### Release notes

Nothing to report. Fix DCMTK-MEX compilation on Luna for older software versions.
