### ISSUE TITLE
Bug in DEBBIE data - wrong order of PLDs in FSLOptions.txt

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#1449]
### Description

For HAD8, the BasilOptions.txt has the PLD order like this "0.6, 0.8, 1, 1.2 , etc", instead of "0.6, 1, 1.4 .... 0.8, 1.2, 1.6 ..." as the order of the PWI4D nifti for HAD8.

Here, in the xASL_quant_FSL function, if we don't invert the index matrix we'll be fine:
<img width="1188" alt="image" src="https://github.com/ExploreASL/ExploreASL/assets/73699072/5fedbe63-5436-4e51-a242-e3f26f3aa14e">

NB: I was testing the sessions the other way around to be able to automatize the concatenation (ASL_1 = HAD8, ASL_2 = HAD4). I don't know if that might have influenced the bug...

### Tasks Jan

- [x] Fix PLD order in function `xASL_quant_FSL`
- [x] Check Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1
- [x] Check Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1
- [x] Check Siemens_PCASL_3DGRASE_VE11C_DEBBIE_2
- [x] Check Siemens_PCASL_3DGRASE_VE11E_DEBBIE_1
- [x] Check Siemens_PCASL_3DGRASE_XA30_DEBBIE_1

### Tasks Bea

- [x] Check Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1 --> running
                   -> 1 rep only for HAD8, but PLDs are fine + nifti PLDs order also fine
                   -> CBF map (HAD8):
                   ->Tex map (concatenated):
- [x] Check Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1 --> running
                   -> 2 reps for HAD8, but PLDs are fine + nifti PLDs order also fine
- [x] Check Siemens_PCASL_3DGRASE_VE11C_DEBBIE_2 --> runnning
- [x] Check Siemens_PCASL_3DGRASE_VE11E_DEBBIE_1 --> running
- [x] Check Siemens_PCASL_3DGRASE_XA30_DEBBIE_1 --> running

### Release note

Minor fix in PLD ordering for FSL.
