### ISSUE TITLE
Add dummy field to ASLContext

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1456]
### Description

The dummy scan position option is not working correctly. E.g., for FlavorDatabase/Siemens_PCASL_multi_VE11C_1/rawdataReference/sub-101/ses-1/perf/sub-101_ses-1_run-1_asl.json this is done incorrectly, as DummyScanPositionInASL4D is added to studyPar.json instead of dataPar.json, and thus ends up in the ASL sidecar (which is not according to BIDS).

And we want to add a dummy scan already in import to BIDS!!! The Northeastern group doing TBI was also interested in that.

### Tasks

- [ ] Make sure that M0 and dummy parameters are correctly read from the ASL context in `xASL_io_SplitASL`.
- [ ] Having dummy in JSON, m0scan in context, it doesn't split both and M0 is ignored during the processing.
- [ ] Make sure that the splitting is always run from `xASL_bids_parseM0` and only inside check if it is necessary based on ASLcontext etc.
- [ ] Make sure that M0 and dummy parameters are correctly saved to the ASLContext and not elsewhere. And start phasing out to save them inside the JSON parameters, but only save them in ASLContext.tsv.
- [ ] Allow import to BIDS with a `dummy` scan in ASLcontext in `DCM2NII` and `NII2BIDS`.
- [ ] Update dummy in BIDS specification. Yes, you create an issue on https://github.com/bids-standard/bids-specification and if you want to solve it yourself, you fork the repository, create a branch, and do a PR from this branch to the original repository, and link it to this issue.
- [ ] Fix #748 
- [ ] Correct splitting of dummy scans from ASLcontext in BIDS2Legacy.
- [ ] Check adding and splitting dummy here: `xASL_bids_BIDSifyASLJSON`, `xASL_bids_parseM0`, `xASL_bids_BIDSifyASLNII`, `xASL_bids_MergeNifti`
- [ ] Adding `DummyScanPositionInASL4D` to studyPar.json shouldn't result in adding it to ASL.json (not according to BIDS) but instead adding it to the dataPar.json. See `Siemens_PCASL_multi_VE11C_1/rawdataReference/sub-101/ses-1/perf/sub-101_ses-1_run-1_asl.json` - this won't work for multi-sequence studies, so we really need to add that to the ASL4D.json and ASLContext.
- [ ] Inform Northeastern group about adding the dummy scan as a an extra entry.
- [ ] Properly link ASLContext and JSONs
- [ ] Explain in BIDS that TotalAcquiredPairs is only control/labels.

### How to test

- [ ] Update `Siemens_PCASL_multi_VE11C_1` flavor.
- [ ] RUn flavors test.
- [ ] Do final flavor updates.

### Release notes

Required: summarize the changes for the release notes here
