### ISSUE TITLE
CBF quantification scaling in FABBER

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1468]
### Description

There might be an issue with FABBER quantification of CBF. Specifically, our M0 division and CBF scaling seems to work for BASIL, but FABBER probably behaves differently resulting in incorrect scaling of CBF data processed by FABBER.

We have to investigate if this is because we do BASIL/FABBER scalings differently. Or if there's a difference in FSL that we don't take into account. 

Compared to Amnah's niftis:
-> Decoded images look the same
-> ftiss (after Fabber with HAD4+HAD8 concatenated) look the same
-> Only CBF of the concatenation processing (after dividing ftiss by M0) differ...

### Tasks

- [x] Fix TEs for single-TE for FABBER - @jan-petr 
- [x] Compare BASIL with FABBER of HAD8 and HAD4-singleTE in Amnah's version - @jan-petr 
- [x] Compare Amnah's FABBER of HAD8, HAD4-multiTE, HAD4-singleTE - @jan-petr 
- [x] Compare Amnah's FABBER of HAD8, HAD4-multiTE, HAD4-singleTE - @BeatrizPadrela 
- [x] Final comparison of concatenated DEBBIE with Amnah's results including Tex - @jan-petr 
- [x] Final comparison of concatenated DEBBIE with Amnah's results including Tex - @BeatrizPadrela 

### Release notes

Report together with #1471 and #1469.

**Comment by BeatrizPadrela** [comment]
This is how the CBF map after quantification with Basil looks like:

<img width="934" alt="Screenshot 2023-08-07 at 21 29 09" src="https://github.com/ExploreASL/ExploreASL/assets/73699072/836ace4e-bc38-4005-a6ed-3837628ceeb8">


Then I check the CBF map after quantification with Fabber, with this FSL_ModelOptions.txt:
[FSL_ModelOptions_FabberForHAD8Only.txt](https://github.com/ExploreASL/ExploreASL/files/12284687/FSL_ModelOptions_FabberForHAD8Only.txt)

and the CBF map created after the quantification was the same:
<img width="999" alt="Screenshot 2023-08-07 at 21 28 23" src="https://github.com/ExploreASL/ExploreASL/assets/73699072/bcff43ca-35df-49a6-9af8-c976d9cb628f">


Conclusion: the problem might be with the M0 division when we have concatenated ftiss

**Comment by BeatrizPadrela** [comment]
ASL_1 -> multi-TE HAD4
ASL_2 -> HAD8 with BASIL
ASL_3 -> HAD4 single TE with BASIL
ASL_4 -> HAD8 with Fabber
ASL_5 -> HAD4 single TE with Fabber

<img width="119" alt="image" src="https://github.com/ExploreASL/ExploreASL/assets/73699072/06f63676-5499-4c40-9fd3-bb52fcf4df16">

**Comment by BeatrizPadrela** [comment]
Conclusions:
1. BASIL/FABBER slightly differs (Fabber produces slight higher CBF) 
2. standard FABBER and Amnah's FABBER in single-TE is identical 
3. HAD4-multi-TE, HAD4-singleTE, HAD8 in FABBER are very very similar. 
4. Amnah's results and our results with her code slightly differ in CBF - but this must be attributable to differences in T1b (1.73 vs 1.65) and T1-tissue (1.33 vs 1.25) and our handling of M0.
