### ISSUE TITLE
Import and processing of Thijs's BBB ASL

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1474]
### Description

Import PAR/REC BBB ASL data from Thijs. Make sure that the parameters are right and that all is set correctly for processing.

### Tasks

- [x] Add a flavor to a branch BBB-Thijs @HenkMutsaerts 
- [x] Create a new issue for XML/REC import #1510 
- [x] Insert everything into Flavors with XML/REC import deactivated for the moment
- [x] Adapt reading PAR parameters to new names
- [x] Add reading of `Scan Type` PAR tag
- [x] Import all data
- [x] Set all parameters
- [x] Make TE import work 
- [x] Fix a correct import of BBB PAR/REC to rawdata
- [x] dcm2nii reads each TE as a separate NII, so we need to interleave TEs again.
- [x] T2prep - repeat TEs correctly.
- [x] T2prep - make sure we have the correct number of totalacquired pairs
- [x] T2prep - create a correct PLD and TE and repetition ordering - change order TE/repetition/PLD to TE/PLD/repetition. Or make sure that this is correctly reorganized in the quantification. So we might need to move this for later.
- [x] Make sure the decoding goes well for Hadamard 4
- [x] Had8 is encoded with hadamard(8) from Matlab
- [x] check if old had8 from Philips still work
- [x] T2prep seems to interleave control/label in import and thus skipping the TE dimension - we have to avoid that.
- [x] T2prep looks like multi-TE, but acquired in a standard control/label fashion.
- [x] Special quantification of T2prep - any other parameters to read? The two sequences need to be added to the import
- [x] Make quantification work
- [x] Fix flavors:
- [x] 'Philips_PCASL_2DEPI_PARREC_1', 
- [x] 'Philips_PCASL_2DEPI_PARREC_2', 
- [x] Philips_PCASL_3DGRASE_DEBBIE_PARREC_1
- [x] 'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1', 
- [x] 'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1', 
- [x] 'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_2' 
- [x] 'Siemens_PCASL_3DGRASE_VE11E_DEBBIE_1' 
- [x] 'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1' 
- [x] Final test of Flavors

### How to test

Two flavors added `Philips_PCASL_3DGRASE_DEBBIE_PARREC_1` and `Philips_PCASL_3DGRASE_DEBBIE_XMLREC_1`, but the XML will only be fixed later.

ASL1 - T1, First HAD4_multiTE, M0
ASL2 - first T2prepHAD4
ASL3 - second T2prepHAD4
ASL4 - second HAD4_multiTE
ASL5 - HAD8 

For Multi-Echo:
The data dimensions will be: xdim ydim zdim 4 8 (I think it’s 4 and 8 or else 8 and 4, but you will see it). The ‘4’ denotes the hadamard4 matrix that was used to encode the data so these are four raw images needed to get 3 PLDs. The ‘8’ denotes the eight echoes that were obtained in the multi-echo GraSE readout.

For T2prep: The data dimensions will be: xdim ydim zdim 8 4. The ‘4’ denotes the hadamard4 matrix that was used to encode the data so these are four raw images needed to get 3 PLDs. The ‘8’ here denotes the dynamics which were used to acquire two rounds of T2preps: so [0, 40, 80, 160, 0, 40, 80, 160].

To perform Hadamard-4 decoding you shouldn’t use the Matlab hadamard(4) function because although it is a Hadamard-4 matrix, it isn’t exactly the same as what was implemented on our Philips scanner for encoding. You will need this one (and the first column is disregarded):
Hadamard4 = [1     1     1     1
             1     1    -1    -1
             1    -1     1    -1
             1    -1    -1     1];

Hadamard-8 is using Matlab's hadamard(8)

% Perform Hadamard decoding to subtract the data:   
      had_cnt =4;
echo_cnt =4;
Decoded=zeros(x_dim, y_dim, z_dim, echo_cnt, had_cnt-1); % assign empty variable for decoded ASL data
    for i=1:had_cnt-1
        for j=1:had_cnt
            Decoded(:,:,:,:,i)= Decoded(:,:,:,:,i)-(H(i+1,j)*inputdata(:,:,:,:,j));
        end
    end

It should look like perfusion data for three timepoints and over four echoes now.
The PLDs were 600, 1600, 2600
The LDs were 1000, 1000, 1000

### Release notes

Add new Philips Hadamard multi-TE flavor.
