### ISSUE TITLE
xASL_test_TestExploreASL

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1489]
### Description

Several things need to be improved, which I found out when running this without first cloning the test dataset.

### Tasks

- [ ] If the testdataset is not present, issue a warning and clone the testdataset
- [ ] The function names of test functions needs to be self-explanatory, they all test ExploreASL (this one should rather be `xASL_test_ImageProcessing`
- [ ] input parameter `testDataUsed` should be renamed to `testDataUsedForSPM`. If this parameter defaults to zero, it should take the first dataset it finds, not the current hardcoded path

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
