### ISSUE TITLE
Code simplification for BIDS2Legacy parallelization

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1495]
### Description

Simplification of code, used for revamping the BIDS2Legacy parallelization

### Tasks

- [x] `xASL_wrp_BIDS2Legacy`: instead of running all subject-session combinations from the BIDS table, process a single subject

- [x] Check what the clean-up does, should this move elsewhere? -> I checked this, was obsolete. This fixed the saving of log files at incorrect locations, but the log files are now already saved at the appropriate location in the import.
- [x] Move non-subject specific code from `xASL_wrp_BIDS2Legacy` to `xASL_init_BIDS2Legacy`. Added benefit is that variables go in `x.modules.bids2legacy`, which helps with provenance.
- [x] Code simplification: unlike other modules, `xASL_module_BIDS2Legacy` doesn't have multiple steps so there is no need for a separate wrapper, `xASL_wrp_BIDS2Legacy` could be fully embedded/wrapped in `xASL_module_BIDS2Legacy`.

- [x] Simplify ExploreASL_Initialize:
sorted subfunctions
improved comments
integrate separate xASL_init_*.m functions that are only used by ExploreASL_Initialize: 
  xASL_init_printSettings, 
  xASL_init_checkDatasetRoot, xASL_init_DetermineRequiredPaths
  xASL_init_DefineIndependentSettings
merge inside ExploreASL_Initialize:
xASL_init_DeployedModeHandling->xASL_init_GetMasterScript
xASL_init_GetMasterScript & xASL_init_GetMyPath -> xASL_init_GetMainExploreASLFolder

- [x] Simplify xASL_init_DataLoading
integrate separate xASL_init_*.m functions that are only used by ExploreASL_Initialize: 
xASL_init_DefineDataDependentSettings
xASL_init_LoadDataParameterFile.m
xASL_init_DefineStudyData -> THIS IS A BIG ONE
xASL_init_RemoveLockDirs.m
xASL_init_PrintCheckSettings.m
merged inside xASL_init_DataLoading:
xASL_init_DefinePaths.m -> xASL_init_DefineDataDependentSettings.m
xASL_init_Toolboxes.m -> xASL_init_DefineDataDependentSettings.m
PM: xASL_init_Toolboxes only loads SPM, and may go elsewhere as it is not data-dependent

- [x] Separate processing initialization functions:
It boils down to the addition of the import module, there is now a lot in common between the processing modules but not with import (and it shouldn't, to avoid bugs). The functionality of the processing and import modules are very different.
So I would propose to structure:
/Modules/Import
/Modules/Processing/Structural
/Modules/Processing/ASL
/Modules/Processing/Population
Because this allows to have initialization functions that are processing only, in the processing folder.

- [x] `xASL_imp_DetermineSubjectStructure` sort of creates a list of subjects and is used for both import and processing:
* import DICOM2NIFTI: `xASL_imp_DetermineStructureFromSourceData`
* import NIFTI2BIDS: `xASL_imp_DetermineStructureFromTempData`
* import BIDS2LEGACY: `xASL_imp_DetermineStructureFromRawData`

I have now moved the processing part out of this function.

* `xASL_imp_DetermineStructureFromRawData` -> replaces `xASL_imp_DetermineSubjectStructure` in `xASL_init_Process`

- [x] Move processing initialization functions to `/Modules/Module_Processing/`
* For BIDS2Legacy (run within ExploreASL_Process)
xASL_init_BIDS2Legacy.m
* For processing (run within ExploreASL_Process)
xASL_init_Process.m
* xASL_init_DataLoading & xASL_init_DefineStudyData
* xASL_init_LoadMetadata.m (in xASL_init_DefineStudyData & xASL_module_Population)
xASL_init_FileSystem.m
* xASL_init_LongitudinalRegistration.m
* xASL_init_MapsAndAtlases.m
xASL_init_VisualizationSettings.m
xASL_init_DefaultEffectiveResolution.m
xASL_init_LabelColors.mat (in Population module)

### Release notes

Report with #1275. Allow parallelization of BIDS2Legacy.
