### ISSUE TITLE
ROI/lesion statistics creates too many tsv files

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1503]
### Description

When there are ROI/lesion NIfTI files, instead of a single TSV file with ROI statistics, multiple TSV files will be created, once for every participant. We need to create one TSV per Lesion|ROI.

So `xASL_im_Lesion2Mask` takes `(ROI|Lesion)_(T1|FLAIR).nii` and creates several ROIs: 1. Intralesional, 2. Perilesional, 3. Rest of the hemisphere minus (1) and (2). 4—6 the same as 1—3 but then in the contralateral hemisphere.

These are then stored in the Population folder, for each subject. And they go to the `xASL_wrp_GetROIStatistics` which considers them as atlases/ROIs. This function iterates over all subjects, so for each ROI/lesion, a TSV file is created for all subjects.

The easiest would be to create a separate function that merges these TSV files afterwards. More difficult, but perhaps cleaner, would be to have a subject-specific masking option in `xASL_stat_GetROIStatistics`, which would then read the atlas name for a subject-ID, and searches the data-list for the same subject-ID. The latter would require changing `xASL_stat_AtlasForStats` to iterate over subjects as well.

Jan & Henk agreed:
1. xASL_stat_AtlasForStats into a xASL_stat_LesionForStats
2. xASL_stat_GetROIStatistics is called once for each subject with the specific lesion

### Tasks
- [x] Remove xASL_adm_OutputDifferentAtlasResults as we don't use it (Michael created this)
- [x] Create a testing scenario
- [x] Modify xASL_stat_AtlasForStats instead of create new xASL_stat_LesionForStats. xASL_stat_AtlasForStats has many functions and it would be very difficult to maintain two functions. So instead, we modify this function that it is either called as 'default' - map a new atlas. Or 'update' which doesn't run the overhead, but it replaces the current lesion atlas with new Lesion for the given subject.
HENK: I would instead have a subject-specific atlas option, where it reads 1 atlas per subject in the 4rd dimension (currently the 4rd dim are the different ROIs) or 5th dimension (so 4rd dim can stay intra/peri/etc) -> 5th dim is perhaps easiest
- [x] xASL_stat_AtlasForStats is run only once for all subjects. But for Lesions, we will update xASL_stat_AtlasForStats 
       for each subject -> see modif above.
- [x] So xASL_wrp_GetROIstatistics can stay virtually unchanged
- [x] xASL_stat_GetROIstatistics will be modified for Lesions|ROIs to always update the atlas for each subject (or report 
       zero if an atlas is missing).
-> do we need a bSubjectSpecificROIs boolean also here? Would be good to have the same boolean throughout the 
       population module (or in xASL_wrp_GetROIstatistics at least)
- [x] name of the ROI should be "intralesional" instead of "intratumoral" V
- [x] values should not be only GM, but also WM -> yes the whole ROI
        BTW: somebody made an x.S.bMasking, I cannot remember this. I like the idea, but I need to check if it is 
        implemented well with the way I set it up
- [x] Use ROI names from xASL_im_Lesion2Mask
- [x] Skip missing ROI for P03 in T1
- [x] Find differences in Lesion_T1 P01 and P02 - why are most ROIs 0? Something wrong with left-sided ROIs??
- [x] Lesion by default doesn't use GM, ROIs do.
- [x] Use proper Lesion_FLAIR name

### How to test

- [x] Test & fix this for a single lesion
- [x] Test & fix this for multiple lesion/ROIs

### Release notes

ROI/Lesion masks produce a single stat-file per mask.
