### ISSUE TITLE
GE enhanced ASL 7 PLDs check

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1516]
### Description

Figure out correct parameter reading for GE eASL. We have an example flavor here, and we know the correct PLD and labeling duration from a sequence description file. But this doesn't match the DICOM information at all.

See example here. The flavor is added and working, but automatic DICOM parameter parsing not.
GE_PCASL_3Dspiral_DV29.1_eASLPLD7_1

### Tasks

- [x] Read GE private fields 015387a0
- [x] distinguish eASL and normal ASL GE version 015387a0
- [x] Convert correctly GE private fields to PLD values 015387a0
- [x] GE and DICOM fields for labeling duration and PLD are a mess and do not correspond to the real values at all. But there's no clear way how to recalculate this. 015387a0
- [x] NII2BIDS crashes without ASLcontext, which it should be able to detect automatically with latest GE scans? (M0 is always at the end and the rest is just deltaM). See if we can extract this also for eASL GE. 015387a0
- [x] First do GE special tags and only then merge dcm2nii and studyPar.json
- [x] Empty x.S added to dataPar during BIDS2Legacy
- [x] Compile FLUX version
- [x] Compile DCMTK windows
- [x] Compile DCMTK MacOS
- [x] Update flavors
- [x] test flavors for old DCMTK - GE_PCASL_3Dspiral_DV25.0_eASL_1 generates 1 PLD instead of adding 0 to m0scan.
- [x] test flavors for new DCMTK (both should work as we still provide studyPar.json info until all is recompiled)

### Release notes

Read GE private fields.

**Comment by jan-petr** [comment]
{'GE_PCASL_3Dspiral_DV22.0_1'                         }    {'Both'}    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'                }
    {'GE_PCASL_3Dspiral_DV23.1_1'                         }    {'Both'}    {'Different file content'}    {'Different file content: /sub-11/perf/sub-11_asl.json'                    }
    {'GE_PCASL_3Dspiral_DV24.0_1'                         }    {'Both'}    {'Different file content'}    {'Different file content: /sub-Sub103/perf/sub-Sub103_asl.json'            }
    {'GE_PCASL_3Dspiral_DV25.0_1.5T_1'                    }    {'Both'}    {'Different file content'}    {'Different file content: /sub-D21002/perf/sub-D21002_asl.json'            }
    {'GE_PCASL_3Dspiral_DV25.0_eASL_1'                    }    {'Both'}    {'Different file content'}    {'Different file content: /sub-001/perf/sub-001_asl.json'                  }
    {'GE_PCASL_3Dspiral_DV25.0_eASLPLD3_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /sub-001/perf/sub-001_asl.json'                  }
    {'GE_PCASL_3Dspiral_DV25.0_eASLPLD7_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /sub-001/perf/sub-001_asl.json'                  }
    {'GE_PCASL_3Dspiral_DV29.1_1'                         }    {'Both'}    {'Different file content'}    {'Different file content: /sub-sub01/perf/sub-sub01_asl.json'              }
    {'GE_PCASL_3Dspiral_RX28.02_1'                        }    {'Both'}    {'Different file content'}    {'Different file content: /sub-Sub124/perf/sub-Sub124_asl.json'            }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-1_asl.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-2_asl.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-3_asl.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-4_asl.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-5_asl.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-6_asl.json'          }
    {'Philips_PCASL_3DGRASE_5.4.1.0_TopUp_1'              }    {'Both'}    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'                }
    {'GE_PCASL_3Dspiral_DV25.0_1.5T_1'                    }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-D21002_1/ASL_1/ASL4D_Source.json'}
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'        }    {'Both'}    {'Different file content'}    {'Different fi

{'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'        }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'        }    {'Both'}    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-001_1/ASL_1/ASL4D.nii.gz'}
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'        }    {'Both'}    {'Different file content'}    {'RMSE of NIFTIs above threshold: /ExploreASL/sub-001_1/ASL_1/M0.nii.gz'   }
    {'GE_PCASL_3Dspiral_DV25.0_eASL_1'                    }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_DV25.0_eASL_1'                    }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-001_1/ASL_1/ASL4D_Source.json'   }
    {'GE_PCASL_3Dspiral_DV25.0_eASLPLD3_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_DV25.0_eASLPLD3_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-001_1/ASL_1/ASL4D.json'          }
    {'GE_PCASL_3Dspiral_DV25.0_eASLPLD3_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-001_1/ASL_1/ASL4D_Source.json'   }
    {'GE_PCASL_3Dspiral_DV25.0_eASLPLD7_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_DV25.0_eASLPLD7_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-001_1/ASL_1/ASL4D.json'          }
    {'GE_PCASL_3Dspiral_DV25.0_eASLPLD7_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-001_1/ASL_1/ASL4D_Source.json'   }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'                 }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_DV29.1_1'                         }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_DV29.1_1'                         }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub01_1/ASL_1/ASL4D_Source.json' }
    {'GE_PCASL_3Dspiral_DV29.1_eASLPLD7_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_HD14.0_WIP_1'                     }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_HD15.0_WIP_1'                     }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_RX28.02_1'                        }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_RX28.02_1'                        }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub124_1/ASL_1/ASL4D_Source.json'}
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                        }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D.json'         }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D_Source.json'  }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_2/ASL4D_Source.json'  }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_3/ASL4D_Source.json'  }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_4/ASL4D_Source.json'  }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_5/ASL4D_Source.json'  }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_6/ASL4D.json'         }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'                }    {'Both'}    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_6/ASL4D_Source.json'  }
