### ISSUE TITLE
Chris Rorden's Siemens flavors

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1528]
### Description

Check Chris Rorden's PASL Siemens flavors are in Flavors/Siemens_PCASL_multiSequence_VE11C_2

https://github.com/neurolabusc/dcm_qa_asl/tree/master

### Tasks
- [x] https://users.fmrib.ox.ac.uk/~chappell/asl_primer/data/index.html 2D EPI multi-PLD PCASL has its full ASL BIDS example here: https://osf.io/yru2q/ (example asl_004)
- [x] PASL3D - create flavor and inform Chris. DONE by @jan-petr 
- [x] PCASL2D from JJ Wang
- [x] PCASL 3D from JJ Wang
- [x] 2 vessel-encoded scans cannot be made into BIDS yet afaik
- [x] Make sure Flavors are added, with proper JSONs and that the flavor reference is created and fully integrated
- [ ] Check #1130 as a related issue.
- [ ] PASL2D - make sure the flavor is correctly recognized and parsed according to the Siemens_PCASL_multiSequence_VE11C_2_Oxford protocols_VEPCASL PDF and Product_Wang_Protocols.pdf. Add also to flavors table. Check code of Chris if everything is OK https://github.com/rordenlab/dcm2niix/blob/master/console/nii_dicom_batch.cpp at line 17
- [ ] https://github.com/rordenlab/dcm2niix/blob/master/BIDS/README.md add NumRFBLocks, MeanGzx10 and other Phoenix Tags and test them on the specific datasets
- [ ] Make sure that the following is properly added to our code for PASL3D
"PostLabelingDelay":1.99 - For most Siemens PASL sequences, this is equivalent to your tag "InversionTime": 1.99, which can be removed. Alternatively, for this specific implementation of PASL on Siemens by Danny Wang, you can alternatively get this parameter from Siemens protocol at "alTI[2] = 1990000" or at <ParamLong.""TI2_us""> {1990000}. These tags are valid for this particular software version and can be slightly different in the newest eASL sequence by Danny. And it will be different in Siemens software by other labs. Checking a consistency of these three tags might be a good way to recognize this particular sequence.
"BolusCutOffFlag":true,
"BolusCutOffDelayTime":0.7, - In PASL, there is in practice no labeling duration. The labeling is nearly instantaneous and the RF pulse duration is not really the labeling duration in the sense of temporal length of the bolus. The decision of all collaborators of ASL-BIDS extension was then to avoid calling this parameter LabelingDuration for PASL and instead call it what it really is - BolusCutOffDelayTime while setting the flag BolusCutOffFlag to true. The value is equivalent to your parameter "BolusDuration":0.7, which can be removed. Similar to above, you can find the value alternatively in Phoenix in the following fields "alTI[0] = 700000" or  <ParamLong.""TI1_us"">  { 700000  }
"BolusCutOffTechnique":"QUIPSSII" - Related to above. Knowing that bolus saturation is ON - as the alTI[0] = 0.7, we can fill in the type of the saturation pulse as QUIPSSII. I can obtain that info from the protocol PDF and also from the fact that we have a single cutoff time. I think that this info is recorded in "sAsl.ulSuppressionMode     =     2", but that's something I do not know for certain. 

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
