### ISSUE TITLE
Weighted-average PWI for improved registration

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1539]
### Description

Currently, the PWI is the average of all PLDs, labeling durations, for the first echo time only.
Instead, I propose that we do a weighted sum.
So, we compute the SNR contribution of the TEs, which is an exponential contribution.

Likewise, we can compute the SNR contribution based on PLD and LD, but the location of the label needs to be taken into account so we could simply do a linear weighting where the earliest PLD counts the lowest and the latest PLD the most.

How to compute single PWI for registration purposes.
For this we still need to reach consensus. **JAN** Agree with 5 as the best option. And use 1-4 as input for the weighting.
1) we take longest PLD because it has most CBF weighting **JAN** Not really, PLD=3500 is pretty bad. 
2) we take longest LD because it has most SNR **JAN** Good idea if there are multiple LDs, then we first go for the longest LD and then select PLDs. Cause longest LD will probably also have the longest PLD.
3) we take the PLD closest to 2000 ms (Look Locker example) **JAN** Yes for Look-Locker
4) We take a combination
5) We take a weighted average (my preference) **JAN** Agree

### Proposal weighted-average
The goal of PWI is a CBF registration reference, but a very noisy CBF might be worse than a higher SNR combination between vascular and CBF, etc.

based on Alsop MRM 2014
https://pubmed.ncbi.nlm.nih.gov/24715426/

nsrPLD = exp(PLD/T1b) / (1-exp(-LD/T1b)) (nsr == 1/snr)
Single-compartment model uses this assuming that the label remains in the blood compartment.

nsrTE = exp(TE/T2(*))
-> this is T2 for 3D spiral & T2* for 3D GRASE or 2D EPI.

For CBF vs vascular weighting: we could say that a PLD > 2500 ms has 100% CBF weighting (2000 for 2D EPI because of multi-slice) and anything below 1000 ms has 1% CBF weighting, and that goes linearly.

pwiPLD =  max((min(PLD, 2500) - 1000) / 15,1); % how much perfusion-weighting we have in the image

So the contribution per volume would then be:

contribution = pwiPLD / (nsrTE * nsrPLD)

This gives a contribution sum for all volumes, which we scale linearly to 100%.

### Tasks

- [x] Base this branch of feature-#1551_RevampedSubtractionTempBranch
- [x] xASL_im_ASLSubtractionAveraging: Compute a weightings vector for all volumes that sums to 1
- [x] Test with DEBBIE (@jan-petr for some reason I couldn't test my DEBBIE sequence anymore, I got bugs in xASL_quant_HadamardDecoding) - **JAN** DEBBIE needs more fixes that are already done in develop. I will retest all once merging and rebasing all.
- [x] Move quantification parameter copy to start of xASL_module_ASL (blood T1, T2, etc) as separate function
- [x] What do we do for look-locker? Couldn't we do the same? **JAN** Mathijs has his Look-Locker issue where this is done. We'll fix that in that issue.

### How to test

- [x] Jan tests with DEBBIE sequence before merging (this gave Henk `xASL_quant_HadamardDecoding` bugs so he couldn't test it) **JAN** DEBBIE shouldn't be affected by this issue. All DEBBIE errors are related to previous errors - so we need to merge+rebase all previous issues that have likely fixed all the troubles.

### Release notes

Calculate mean PWI for registration as a weighted sum.
