### ISSUE TITLE
Update PDF report for new x.output format

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1552]
### Description

PDF report has been revamped. But we have now also changed the way the QC is created. After merging #1225 , 
Basically, we don't now have info inside x.output.ASL, but there are subfields based on sessions.
Same for structural.
And we have to be careful that all from x,output.ASL is now deleted what is not inserted in these subfields - so that could apply to sub fields inserted by the PDF report.

Basically, we are synchronizing edits made in #1225 and #1514. Both were already merged. #1551 is also already merged.

### Tasks

- [x] Change the way x.output and x.output_im is used in xASL_qc_ParsePdfConfig.m
- [x] Manage default number of floating points (digits after floating point)
- [x] Change the way x.output and x.output_im is used in xASL_qc_ParsePdfConfig.m - line 90, we create the PDF - but do we create it for each ASL session? Or once per subject? Each has its disadvantages as we either have the structural module multiple times or we need to detect the last ASL session and call it for all previous ASL sessions. But maybe a re-creation for all ASL sessions will work with some extra overhead.
- [x] xASL_qc_ParsePdfConfig.m/xASL_sub_createModuleContent - For ASL module, we use an extra subfield session. x.Output.ASL.ASL_1 and x.Output_im.ASL.ASL_1.
- [x] xASL_qc_ParsePdfConfig.m - take the current ASL session into account. Add the session name to the PDF filename.
- [x] Update Docs to explain the changes

HENK: 31-12-2024
- [x] bugfix: for 1:size() -> for 1:length()
- [x] convert pageIdentifier to identifier in /WorkInProgress/QualityControl/PDFGenerator.md
- [x] recreate the config file for each subject, because each subject can have different modules
- [x] move the config file location to the subject rather than derivatives root folder
- [x] do the crawling for creating the config file not module-specific, but based on having number of sessions (dwi & fmri can also have multiple sessions, but these modules are not really used)

### How to test

- [x] Unit Test
- [x] Henk: tested with 1. Structural + ASL_1 modules (TestDataSet) & 2. ASL_1 + ASL_2 FlavorDatabase/Siemens_PCASL_2DEPI_E11_1)
- [x] Henk: Checked the PDF

### Release notes

Generate PDF reports also for multiple ASL runs

**Comment by maartenhammer** [comment]
- [x]  Wait on #1551

**Comment by maartenhammer** [comment]
- [x] Added support to x.output.ASL.ASL_1 sessions. 
- [x] Changed Config Generator (default behaviour when no config is found) to support modules, will create a pdf for each ASL session and one for Structural module
- [x] Updated https://github.com/ExploreASL/Documentation/blob/master/source/Tutorials-Report.md 
- [x] Added support for Floating point Arrays
- [x] Added a bOverwrite that will replace the existsing configReportPDF.json with an automatically generated one in the derivatives folder (it would be wise to set this to true when running ExploreASL, as the pdf is generated at the end of every module, so with bOverwrite = false it would never update the config after the first module finished)
- [x] Tested on TestDataSets

**Comment by maartenhammer** [comment]
If you want to run it yourself you just do the standard

``` matlab
x = ExploreASL ('<root>' , 0, 1)
xASL_qc_GenerateReport(x)
```
It will default to the active subject in x, but you can specify the subject.  
If no configReportPDF.json exists in the derivatives root, one will be generated using all QC parameters of the subject. 

If you want to use the exampleConfigReportPDF.json you can copy it from `ExploreASL/Functions/QualityControl/exampleConfigReportPDF.json` to  `<dataset>/derivatives/ExploreASL/configReportPDF.json`

**Comment by maartenhammer** [comment]
If the structural module is changed in the future to also contain sessions, the most important (and probably only change) will be needed to be made in `Functions/QualityControl/xASL_qc_GeneratePdfConfig.m` .
The adjustments I have made for ASL in this [commit](https://github.com/ExploreASL/ExploreASL/commit/e181a56bf4a9ee5bb532288baf3fb7db2135b4de). should be mirrored to the Structural case as well in  `Functions/QualityControl/xASL_qc_GeneratePdfConfig.m` .
