### ISSUE TITLE
Processing and conversion error

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1563]
### Description

There are several errors related to #1547 that appeared after merging it with other commits to develop.

### Tasks

- [x] DataPar.json is not read when loading separate derivatives folder before loading subjects. GE_3Dspiral_T1prefilled_Cyst_M0_noFLAIR_2ndRun_LoQ crashes because it loads subjects before loading dataPar.json with the correct subjectRegexp first. Fixed in 11f00201
- [x] GE_PCASL_3Dspiral_DV25.0_1.5T_1 during BIDS2Legacy, the subjectRegexp is missing in dataPar.json. Previously, we created the automatic one. But we don't need to create this as it is automatically created later. So we don't need to create x.dataset either. Skipping this in 11f00201 and updating all flavors.
- [x] Associated to above -> update reference dataPar.json in flavors.
- [x] Fix non-working derivatives - adding _1 in flavors to the subject name in derivatives.
- [x] **HENK:** xASL_init_SubjectList on line 28 it says it will use a default folder. But it doesn't initialize `subjectFolder` and will eventually crash on line 37.
**ANSWER HENK**: yes fixed in 25a6e2b1eca9fadee52f988828cc667ad69eba00, by changing the order (because the default folder depends on rawdata vs derivatives as input).
- [x] **JAN:** Does this processing run? `Philips_2DEPI_FLAIR_Segm_PWI4D_Quant_Parameters_LoQ`. 
      Fix1 35313a54
      Fix2 xASL_io_CheckDeprecated fields that creates field x.modules.asl = 1 that later crashes the code. The reason is the the CheckDeprecated fields finds a field in x-struct that matches the first two columns and starts renaming even if it doesn't match the third column. So x.modules.asl. To test this behavior, I have added a new function to UT. 8a13cd60
- [x] Cleanup warning bug in `Philips_2DEPI_FLAIR_Segm_PWI4D_Quant_Parameters_LoQ` - reach consensus on the solution. See my comment in https://github.com/ExploreASL/ExploreASL/pull/1564/commits/25a6e2b1eca9fadee52f988828cc667ad69eba00
- [x] Parameter TC_M0_Registration not assigned in the TestDataSet. The reason is that 'noSmooth_M0_' or 'mean_control_' were compared with the M0 template afterwards by the testing function. But the testing fuction is run after the population modules and we delete both files in the cleanup. Now, we moved the creation of this TC to the end of xASL_module_ASL. Note that we compared an individual M0 with a pre-existing template from another study (coming with ExploreASL), so we don't need to worry that this template doesn't exist.

- [x] xASL_qc_CleanOldQC: Bug when rerunning ExploreASL without pre-existing data: 088fad3be8e86dcfdfa69204479941add8f95f29

### How to test

- [x] Test Flavors
- [x] Test UnitTest
- [x] Test 10-TestDataSets

### Release notes

Report with #1547 .

**Comment by jan-petr** [comment]
{'GE_PCASL_3Dspiral_DV25.0_1.5T_1'                    }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'        }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/ASL4D.nii.gz'            }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'                 }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'GE_PCASL_3Dspiral_RX28.02_1'                        }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Philips_PASL_2DEPI_5.4.1.0_ADNI3_006_S_6681_1'      }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/ASL4D.json'              }
    {'Philips_PCASL_2DEPI_3.2.2.1_2'                      }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Philips_PCASL_2DEPI_PARREC_1'                       }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/sub-Sub01_1/ASL_1/ASL4D.json'            }
    {'Philips_PCASL_3DGRASE_5.6.1.1_CBFonly_1'            }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PASL_2DEPI_VB19A_BSupN_1'                   }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PASL_3DGRASE_VB13A_multiPLD_1'              }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PASL_3DGRASE_VD13D_1'                       }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'                  }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'               }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PCASL_3DGRASE_VE11C_HadamardFME_1'          }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PCASL_3DGRASE_XA20_multiPLD_1'              }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'              }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/sub-1002_1/ASL_1/ASL4D.json'             }
    {'Siemens_VE11_NiftiOnly_1'                           }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'    }
