### ISSUE TITLE
Revamp xASL_wrp_Quantify & xASL_quant_*

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1572]
### Description

Currently, `xASL_quant_ASL` is a maze to know what happens for FSL and non-FSL quantification.

### Tasks
- [ ] Stuff that is equal for FSL and non-FSL, including scaleImage etc, we perform all those (could even be a subfunction). Including all (vendor) scale factors, M0 scaling etc, all that is equal between FSL and non-FSL, is already applied after this step.
- [ ] Either we run xASL_quant_FSL OR xASL_quant_xASL (which can be a subfunction)
- [ ] This way, it is clear which parameters are the same (they are all applied under A) or different, and how they are applied in both quantification versions. Easier to understand, and bugfix. Especially, because their output differs (xASL quantification doesn't do multi-PLD OR multi-TE). Also: this makes it easier for to change e.g. M0 separately from FSL yes/no, because all that scaling stuff is done separately. 
- [ ] Separation of scalar quantification values and ScaleImage. ScaleImage is only required for slice-wise change in PLD. This we make 4D, so we could potentially also do this for multi-PLD. Could potentially make the code simpler, depending on the outcome of (F).
- [ ] make sure dual and multi-echo quantification is skipped in quant_FSL when bMultiTEQuantification is OFF

- [ ] Another simplification would be:
1. load PWI4D
2. run BASIL or not
3. do the scalings
4. average the 4th dim (which would have no effect if it was already 1)

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
