### ISSUE TITLE
Philips DEBBIE follow-up

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1575]
### Description

Make sure that all Philips DEBBIE sequences can be quantified

### Tasks

- [x] Wait for merging #1543 and #1551 
- [x] Had8 is encoded with hadamard(8) from Matlab
- [x]  check if old had8 from Philips still work
- [x]  Make sure the decoding goes well for Hadamard 4
- [x] Check quantification Thijs's Hadamard flavors  - #1474 
- [x] T2prep - create a correct PLD and TE and repetition ordering - change order TE/repetition/PLD to TE/PLD/repetition. Or make sure that this is correctly reorganized in the quantification. So we might need to move this for later.

### Release notes

Nothing. All fixed by adjusting the import parameters.
