### ISSUE TITLE
Clean subtraction code and variable

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1576]
### Description

Required: insert bug description here

### Tasks

- [ ] x.Q.BASIL.bCleanUp -> bDeleteTemp
- [ ] ASL module settings should go to x.modules.asl, ASL quantification parameters to x.Q. Currently, this is a bit mixed up, e.g., we currently have x.Q.SaveCBF4D. Also, where should quantification settings go? E.g.,  x.Q.bUseBasilQuantification. Note also that x.Q won't contain quantification parameters anymore, which will reside in the ASL4D, PWI4D, PWI3D, PWI JSON sidecars.
- [ ] x.Q.NumberEchoTimes -> x.Q.nUniqueEchoTimes (and accordingly for other parameters)
- [ ] x.Q.Initial_PLD -> x.Q.InitialPLD
- [ ] x.Hematocrit -> x.Q.Hematocrit
- [ ] xASL_adm_CleanUpBeforeRerun: add newer files (need to add BASIL folders?)
- [ ] `SaveCBF4D` -> `bSaveCBF4D`
- [ ] DELETETEMP -> bDeleteTemp
- [ ] rename xASL_quant_HadamardDecoding -> xASL_im_HadamardDecoding
- [ ] remove xASL_io_PairwiseSubtraction (it seems obsolete now, or move to CustomScripts/Archive)

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
