### ISSUE TITLE
Errors in subtraction branch

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1581]
### Description

Required: insert bug description here

* Major error was a simple copy-paste one, where `xASL_im_ASLSubtractionAverage` erroneously computes PWI3D from Control4D. Fixed in b50714f023b6b28aaad2a412bea09818e58dd8ec
* Also, we forgot to create mean_control which is then probably skipped in `xASL_wrp_RegistrationASL`. Fixed in 3ecfa3bd87d0cd4edb250be068a4198f1786f87d & bugfixed in 57826cae612618041d6157e424430878820a4e60
* Further discovered but unrelated errors will be fixed in #1588 

### Tasks

- [x] GE_3Dspiral_T1prefilled_Cyst_M0_noFLAIR_2ndRun_LoQ	
- [x] Philips_2DEPI_FLAIR_DisabledQuantification_M0_LoQ	- OK
- [x] Philips_2DEPI_FLAIR_Segm_PWI4D_Quant_Parameters_LoQ	- minor error
- [x] Philips_3DGRASE_FLAIR_M0_2ndRun_HiQ	- large error
- [x] Philips_3DGRASE_MultiSessions_T1wAlreadyDone_LoQ	- large error 

### We need to fix despiked_ASL4D for the following to run - #1543
- [x] Philips_2DEPI_Segmentation_2D_T2_SPM_HiQ	- large error 100%
- [x] Philips_2DEPI_FEAST_Longitudinal_FLAIR_LGA_ASL_PartlyDone_HiQ
- [x] Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ
- [x] Siemens3DGRASE_Structural_AlreadyDone_HiQ
- [x] Siemens_2DEPI_noBsup_FLAIR_LoQ - #1543 despiked JSON

### How to test
- [x] Re-run the entire test again

### Release notes

Nothing. Report with #997
