### ISSUE TITLE
Save JSON along with NII

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1585]
### Description

Modify xASL_io_SaveNiftii to allow saving along the JSON.

### Tasks

- [x] 1. Add an additional optional parameter bCopyJson (default = false) that takes the json from the reference image (if it exists) and saves its entire content together with the new NII
- [x] 2. Add a second additional optional parameter newJson (default = empty) that contains a json structure to be saved along with the NII
- [x] 3. If none of the parameters are provided, no JSON is saved
- [x] 4. If both parameters are provided, then NewJSON fields overwrite the fields from the reference NII.JSON.
- [x] I also noticed a bug with the temporary name, fixed this.
- [x] And I noticed a bug that if a previous .mat or .json sidecar exists for the new file, but we don't create a new one, this file remained. Fixed this now.

### Release notes

xASL_io_SaveNifti can now copy the JSON sidecar.
