### ISSUE TITLE
Miscellaneous issues found in processing DDI

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1590]
### Description

Miscellaneous issues found in processing DDI

### Tasks

- [x] Warning about locked folders, should mention the path of the locked folder to help the user
- [x] When re-running modules, we want to see a % counter only, not repetitive mentioning of the module name -> improve for BIDS2Legacy mainly but also test with other modules
- [x] Printing of the quantification "Using single-compartment ... model" should be improved, also PLD = 2000 ms + slicetime
- [x] Update the checking for missing files: we removed "temporary files" from the population modules: 
`xASL_adm_CreateFileReport`
line 163 MNI_subject_prefix: rT1 rc1T1 rc2T1 rFLAIR
line 165 MNI_session_prefix: PWI SliceGradient

### Release notes

Minor fixes. Nothing to report as mostly related or contained in #1547
