### ISSUE TITLE
Follow-up on 1211

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1601]
### Description

After loading the ASL.json inside xASL_modules_ASL, the EchoTime was in x.EchoTime and the new function was looking for it inside x.Q.EchoTime.

We're now moving it there automatically by adding to the loading script that EchoTime belongs to the x.Q subfield.

Take this dataset as a testing case Philips_3DGRASE_MultiSessions_T1wAlreadyDone_LoQ

### Tasks

- [x] In Philips_3DGRASE_MultiSessions_T1wAlreadyDone_LoQ, ASL.JSON is somehow removed while executing. This was because saving to the same image as the reference image removed the JSON.
- [x] PWI3D and PWI4D.JSONs are all saved in Legacy format (ms) instead of BIDS format. Reading and writing of all JSONs have to go through our special conversion function.
- [x] Eventually, this JSON loading and saving messes up some TE, PLD or other parameters and screws up the quantification. To be fixed....

### How to test

- [x] Run TestDatSet on both Philips_3DGRASE datasets which were the two ones crashing due to this error.

### Release notes

Nothing. Report with #1585.
