### ISSUE TITLE
Import of multi-sequence GE data

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1624]
### Description

Import of GE data works automatically as long as data from a single sequence is provided per session. In case that DICOMs from multiple sequences are mixed in a single folder, ExploreASL won't be able to automatically merge them and get the PLDs and TRs etc. 

We have to use the MCW data for this case, mix them all together and read jointly all the data and make sure that a proper vector of PLDs and TRs and LabelingDurations is created and saved. Because deltaM/m0Scan differentiation works nicely even for multi-sequence merged data.

This has been configured and fixed in GE data from MCW. So we only need to verify that this works, check it and add to flavors.

### Tasks

- [x] Fix import for GE_PCASL_3Dspiral_RX28.0_multiPLD_1
- [x] Add to flavors
- [x] Update older flavors with a proper PLD vector 
- [x]   {'GE_PCASL_3Dspiral_DV22.0_1'     }    {'Both'}    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'                }
- [x]     {'GE_PCASL_3Dspiral_DV23.1_1'     }    {'Both'}    {'Different file content'}    {'Different file content: /sub-11/perf/sub-11_asl.json'                    }
- [x]     {'GE_PCASL_3Dspiral_DV24.0_1'     }    {'Both'}    {'Different file content'}    {'Different file content: /sub-Sub103/perf/sub-Sub103_asl.json'            }
- [x]     {'GE_PCASL_3Dspiral_DV25.0_1.5T_1'}    {'Both'}    {'Different file content'}    {'Different file content: /sub-D21002/perf/sub-D21002_asl.json'            }
- [x]     {'GE_PCASL_3Dspiral_RX28.02_1'    }    {'Both'}    {'Different file content'}    {'Different file content: /sub-Sub124/perf/sub-Sub124_asl.json'            }

### Release notes

Read GE mixture of single-PLDs as a multi-PLD sequence.
