### ISSUE TITLE
Correct DICOM-Phoenix parsing of a VEPCASL implementation

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1631]
### Description

Implement Phoenix parsing for Siemens VEPCASL sequence.

### Tasks

- [x] Remove unused BIDS tags that are not even defined in BIDS
- [x] Remove incorrectly named tags converted by dcm2nii that do not correspond to the correct BIDS tag names
- [x] Identify this sequence in Phoenix parsing and convert all tags
- [x] Fix Import summary bug
- [x] Locate all other similar sequences in Flavors
- [x] Make sure they all work
- [x] Add VEPCASL to flavors
- [x] Final flavor test

### Release notes

Phoenix-DICOM parsing for a sequence to_ep2d_vepcasl.
