### ISSUE TITLE
Remove the functionality _parms.mat

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1637]
### Description

Legacy _parms.mat is not really used already in several versions. So for several years, we haven't created a _parms.mat and it is only there for backwards compatibility. Currently, there is extremely small probability of having a dataset with _parms.mat.

### Tasks

- [ ] We convert the original _parms.mat files into json early in the ASL module, and then remove the _parms_mat. We issue a warning. 
- [ ] Then everywhere in the code, we remove the _parms.mat functionality so that any conversion will happen only once at the start and then only JSONs are used.
- [ ] in xASL_io_ASLSubtractionAveraging we will only use JSONs and we phase out LoadParmsMat as something we don't use anymore.
- [ ] DefineASLSequence is hidden inside xASL_module_ASL_ParseParameters -> LoadParms -> BIDS2Parms -> DefineASLSequence. Which makes it hard to follow. We need to simplify this while getting rid of the parms.mat reading.

HENK: I would remove the warning and do this in version 2.0.0, just as a clean up and not having backward compatibility. Anouk Schrantee is the only one who had this afaik, and also she is now using the new BIDS import, so we should be safe.
HENK2: Let's save the conversion code (parms.mat->json) though for old users. Or they can just take an older version and run xASL_bids_parms2BIDS or something.

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
