### ISSUE TITLE
Update VE-PCASL Phoenix to multi-PLD

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1645]
### Description

Update the VE-PCASL Phoenix flavor to the multi-PLD sequence. Which mainly means adding more PLD fields

### Tasks

- [x] Fix a bug, labeling duration is field 9, not 11
- [x] Add further PLD fields
- [x] Add 3D version
- [x] String parsing is messed up and %\to is parsed as %o in protocol name
- [x] Automatically match ASLcontext when PLD vector only covers PLDs read automatically and not covers M0
- [x] Update the reference of the older flavor
- [x] Check VE flavors
- [x] Make sure the non-Phoenix flavors work
- [x] Add new flavor - PCASL2D,PCASL3D
- [x] Add to the flavor list and mark
- [x] Find all other similar flavors and update their studyPars and Phoenix-flavor database.
- [x] Fix flavor differences

### Release notes

Parse Phoenix protocol of multi-PLD VEPCASL protocol.
