### ISSUE TITLE
Add Schaefer atlas

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#1651]
### Description

Add Schaefer atlas for analyses regarding functional network ROIs. Github: https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI and paper: https://people.csail.mit.edu/ythomas/publications/2018LocalGlobal-CerebCor.pdf 

MIT license: https://nilearn.github.io/dev/modules/description/schaefer_2018.html 

Ideally link 1mm or 1.5mm MNI 2009c asymetric

### Tasks

- [x] Add template .nii.gz's
- [x] Change template to 1.5 mm resolution
- [x] Add labels
- [x] Add license
     - [x] email to check for license
- [x] Fix template alignment
      - Take MNI2009c T1 template image (which is the corresponding template for your template) then you (using SPM) coregister non-linearly MNI2009c T1 template with the IXI512 T1 template, and you apply this transformation to yourschaefer atlas. and you use the result.
- [x] Add to readme
- [x] Fix documentation

It appears the template is not perfectly aligned with the ExploreASL MNI 1mm template. See below:

![image](https://github.com/ExploreASL/ExploreASL/assets/75380250/d0871cff-865b-47fa-8728-62881dd50786)

02-02-2026: For Jan:
MNI 100 parcels 1mm template NII: https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI/Schaefer2018_100Parcels_7Networks_order_FSLMNI152_1mm.nii.gz 
MNI 100 parcels 1mm labels: https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI/Centroid_coordinates/Schaefer2018_100Parcels_7Networks_order_FSLMNI152_1mm.Centroid_RAS.csv 

### Release notes

Add Schaefer atlas.
