### ISSUE TITLE
Automatic reading of TR for a built-in M0

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1652]
### Description

Flavors tgse_pcasl_ve11c with built-in M0 have a special problem. This particular sequence sets M0 TR to 2s, but the TR of ASL is around 4s. Either way, the import ignores the possibility toaumatically detect M0 posiitons and scaling.

This specifically concerns Flavors Siemens_PCASL_3DGRASE_VE11C_3, PCASL_multiSequence_VE11C_1, PCASL_multiSequence_VE11C_2 
And casl_818 sequences have TR 4s in Phoenix

### Tasks

- [x] Read and save TR for each volume
- [x] Test all flavors working
- [x] Read TR from Phoenix and save to the M0scan for casl818 nad pcasl_ve11c
- [x] Make sure that TR is correctly splitted in BIDS2Legacy
- [x] Implement TR reading for PCASL_VE11c
- [x] Fix GE-RX28 Image type
- [x] Test all flavors working
- [x] Inform Catherine Morgan upon merging

### Release notes

Import Siemens with built-in M0 with different TR.

**Comment by jan-petr** [comment]
COMPARISON TABLE:]
                       flavor                           dataset                   name                                                                    message                                                      
    ____________________________________________    _______________    __________________________    __________________________________________________________________________________________________________________

    {'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'}    {'Both'       }    {'Different file content'}    {'Different file content: /sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-2_asl.json'}
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub103/anat/sub-Sub103_T1w.json'                                                                          }
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub103/anat/sub-Sub103_T1w.nii.gz'                                                                        }
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub103/perf/sub-Sub103_m0scan.json'                                                                       }
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub103/perf/sub-Sub103_m0scan.nii.gz'                                                                     }
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub103/perf/sub-Sub103_asl.json'                                                  }
    {'Philips_PCASL_2DEPI_5.1.7.2_LookLocker_1'}    {'rawdata'    }    {'Missing file'          }    {'/sub-UE001BLB201604261112/perf/sub-UE001BLB201604261112_run-2_m0scan.json'                                     }
    {'Philips_PCASL_2DEPI_5.1.7.2_LookLocker_1'}    {'rawdata'    }    {'Missing file'          }    {'/sub-UE001BLB201604261112/perf/sub-UE001BLB201604261112_run-2_m0scan.nii.gz'                                   }
    {'Philips_PCASL_2DEPI_5.1.7.2_LookLocker_1'}    {'Both'       }    {'Different file content'}    {'Different file content: /sub-UE001BLB201604261112/perf/sub-UE001BLB201604261112_run-2_asl.json'                }
    {'Philips_PCASL_2DEPI_5.1.8.2_1'           }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'                                                      }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_1' }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub001/perf/sub-Sub001_asl.json'                                                  }
    {'Siemens_PCASL_2DEPI_E11_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-38/perf/sub-38_run-1_asl.json'                                                    }
    {'Siemens_PCASL_2DEPI_E11_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-38/perf/sub-38_run-2_asl.json'                                                    }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_1'       }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'                                                      }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T1w.json'                                                                              }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T1w.nii.gz'                                                                            }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T2w.json'                                                                              }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T2w.nii.gz'                                                                            }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'                                                      }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_3'       }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_asl.json'                                                      }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_3'       }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-sub2/perf/sub-sub2_asl.json'                                                      }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'    }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_run-1_asl.json'                                                }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'    }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_run-2_asl.json'                                                }
    {'Siemens_PCASL_3DGRASE_VD13D_2'           }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'                                                      }
    {'Siemens_PCASL_3DGRASE_VE11C_2'           }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub103/anat/sub-Sub103_T1w.json'                                                                          }
    {'Siemens_PCASL_3DGRASE_VE11C_2'           }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub103/anat/sub-Sub103_T1w.nii.gz'                                                                        }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'    }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-sub1100189/perf/sub-sub1100189_run-1_asl.json'                                    }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_2'    }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-1_asl.json'                                                }
    {'Siemens_PCASL_3DGRASE_VE11E_DEBBIE_1'    }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-1_asl.json'                                                }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-1_asl.json'                                                }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_1'   }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'                                                      }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'   }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-1002/ses-1/perf/sub-1002_ses-1_asl.json'                                          }
    {'Siemens_PCASL_multiSequence_VE11C_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-101/ses-1/perf/sub-101_ses-1_run-6_asl.json'                                      }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-4_asl.json'                                                                        }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-4_asl.nii.gz'                                                                      }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-4_aslcontext.tsv'                                                                  }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-5_asl.json'                                                                        }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-5_asl.nii.gz'                                                                      }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-5_aslcontext.tsv'                                                                  }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-6_asl.json'                                                                        }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-6_asl.nii.gz'                                                                      }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-6_aslcontext.tsv'                                                                  }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'Both'       }    {'Different file content'}    {'Different file content: /sub-sub1/perf/sub-sub1_run-3_asl.json'                                                }
    {'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'}    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_2/ASL4D.json'                       }
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/M0.json'                                                                        }
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/M0.nii.gz'                                                                      }
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/T1.json'                                                                              }
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/T1.nii.gz'                                                                            }
    {'Philips_PCASL_2DEPI_5.1.7.2_1'           }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub103_1/ASL_1/ASL4D.json'                                             }
    {'Philips_PCASL_2DEPI_5.1.7.2_LookLocker_1'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-UE001BLB201604261112_1/ASL_2/M0.json'                                                          }
    {'Philips_PCASL_2DEPI_5.1.7.2_LookLocker_1'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-UE001BLB201604261112_1/ASL_2/M0.nii.gz'                                                        }
    {'Philips_PCASL_2DEPI_5.1.7.2_LookLocker_1'}    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-UE001BLB201604261112_1/ASL_2/ASL4D.json'                               }
    {'Philips_PCASL_2DEPI_5.1.8.2_1'           }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                               }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_1' }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub001_1/ASL_1/ASL4D.json'                                             }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_1' }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub001_1/ASL_1/ASL4D_Source.json'                                      }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_1' }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub001_1/ASL_1/M0.json'                                                }
    {'Siemens_PCASL_2DEPI_E11_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-38_1/ASL_1/ASL4D.json'                                                 }
    {'Siemens_PCASL_2DEPI_E11_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-38_1/ASL_1/ASL4D_Source.json'                                          }
    {'Siemens_PCASL_2DEPI_E11_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-38_1/ASL_1/M0.json'                                                    }
    {'Siemens_PCASL_2DEPI_E11_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-38_1/ASL_2/ASL4D.json'                                                 }
    {'Siemens_PCASL_2DEPI_E11_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-38_1/ASL_2/ASL4D_Source.json'                                          }
    {'Siemens_PCASL_2DEPI_E11_1'               }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-38_1/ASL_2/M0.json'                                                    }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_1'       }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T1.json'                                                                                }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T1.nii.gz'                                                                              }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T2.json'                                                                                }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T2.nii.gz'                                                                              }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_2'       }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_3'       }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_2DEPI_VB17A_BSupN_3'       }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub2_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'    }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'    }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_2/ASL4D.json'                                               }
    {'Siemens_PCASL_3DGRASE_VD13D_2'           }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_3DGRASE_VE11C_2'           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/T1.json'                                                                              }
    {'Siemens_PCASL_3DGRASE_VE11C_2'           }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/T1.nii.gz'                                                                            }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'    }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1100189_1/ASL_1/ASL4D.json'                                         }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_2'    }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_3DGRASE_VE11E_DEBBIE_1'    }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_3DGRASE_XA30_DEBBIE_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_1'   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_1'   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'                                        }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_1'   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/M0.json'                                                  }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-1002_1/ASL_1/ASL4D.json'                                               }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-1002_1/ASL_1/ASL4D_Source.json'                                        }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-1002_1/ASL_1/M0.json'                                                  }
    {'Siemens_PCASL_multiSequence_VE11C_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-101_1/ASL_5/ASL4D.json'                                                }
    {'Siemens_PCASL_multiSequence_VE11C_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-101_1/ASL_6/ASL4D.json'                                                }
    {'Siemens_PCASL_multiSequence_VE11C_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-101_3/ASL_5/ASL4D.json'                                                }
    {'Siemens_PCASL_multiSequence_VE11C_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-101_3/ASL_6/ASL4D.json'                                                }
    {'Siemens_PCASL_multiSequence_VE11C_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-101_3/ASL_6/ASL4D_Source.json'                                         }
    {'Siemens_PCASL_multiSequence_VE11C_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-101_3/ASL_6/M0.json'                                                   }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_4/ASL4D.json'                                                                       }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_4/ASL4D.nii.gz'                                                                     }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_4/ASL4D_Source.json'                                                                }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_4/ASL4D_Source.nii.gz'                                                              }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_4/ASL4Dcontext.tsv'                                                                 }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_4/ASL4Dcontext_Source.tsv'                                                          }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_4/M0.json'                                                                          }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_4/M0.nii.gz'                                                                        }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_5/ASL4D.json'                                                                       }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_5/ASL4D.nii.gz'                                                                     }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_5/ASL4D_Source.json'                                                                }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_5/ASL4D_Source.nii.gz'                                                              }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_5/ASL4Dcontext.tsv'                                                                 }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_5/ASL4Dcontext_Source.tsv'                                                          }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_5/M0.json'                                                                          }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_5/M0.nii.gz'                                                                        }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_6/ASL4D.json'                                                                       }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_6/ASL4D.nii.gz'                                                                     }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_6/ASL4Dcontext.tsv'                                                                 }
    {'Siemens_PCASL_multiSequence_VE11C_2'     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_3/ASL4D.json'                                               }
