### ISSUE TITLE
Implement xASL_stats_isnear

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1655]
### Description

Implement an own version of isnear and replace all occurences.

### Tasks

- [x] Create a new function xASL_stat_Isnear
- [x] Replace all occurences
- [x] Remove isnear and all directories related

### Release notes

A new function for checking near equivalence of numerical arrays.
