### ISSUE TITLE
xASL_init_CreateParticipantsTSV does not check rawdata

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1658]
### Description

xASL_init_CreateParticipantsTSV does not check rawdata, only the studyroot and derivatives folders.
Just checking @jan-petr if I didn't fix this already in our revamp, otherwise I will fix this now.

Check also #1430 

### Tasks
- [x] Wait till #1551 and #1543 are merged to develop before creating this branch
- [ ] Create capital-insensitive list of datasetRoot, rawdata, derivatives participants.tsv
- [ ] By priority go 1) derivatives (if already existed), 2) rawdata (per BIDS), 3) datasetRoot
- [ ] Generate warnings if it was provided at the wrong location
- [ ] Generate warnings if multiple participants.tsv existed

#### Deal with participants.tsv conversion from BIDS sub-<NAME> to legacy sub-<NAME>_1
- [ ] Add sub- if missing
- [ ] Add ses- if missing in session_id column
- [ ] from participant_id and session_id columns, generate legacy subject-name including visit

#### Merging
- [ ] Do we want to merge in case of different participants.tsv?
- [ ] xASL_bids_Add2ParticipantsTSV already has some functionality for this, can we reuse this?

#### PM (pro memoria)
- [ ] We might want to change x.S.SetsID -> x.S.participantsTSV or something, to harmonize those

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
