### ISSUE TITLE
Simplifying subject loading to participants.tsv

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1669]
### Description

Our legacy derivatives folder loads subjects from the existing native space subject-folders. Then we have tricks like an exclusion list or forceInclusionList in dataPar.json to change this. I propose removing all this and just reading participants.tsv for the subject-names.

### Tasks

- [ ] Check that we always accurately create participants.tsv from the rawdata subject-list, in BIDS2Legacy
- [ ] The same for sessions/visits
- [ ] Change the subject-list definition if not loading subjects-list from rawdata but from derivatives, in this case we load it from participants.tsv. This makes it easy for the user to control which subjects are processed and not.

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
