### ISSUE TITLE
x.Q.Sequence revamp

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1674]
### Description

Use of x.Q.Sequence is an error-prone legacy thing. This is used in all processing although `Sequence` is complementary to the BIDS fields `PulseSequenceType` and `MRAcquisitionType`.

PulseSequenceType is actually a general BIDS field. This is read from DICOM and in case it is missing, I am correctly filling this based on other DICOM information. The correct BIDS approach is to have EPI/GRASE saved in PulseSequenceType and 2D/3D in a BIDS field MRAcquisitionType. 

### Tasks

I propose to make a new issue where we do the following:

- [x] Make sure that MRAcquisitionType and PulseSequenceType contain the correct information as specified above and that also these are always initialized. This will be done in import. 587b1973
- [x] parms2BIDS of BIDS2Legacy and Legacy2BIDS doesn't do anything to MRAcquisitionType+PulseSequence type and keep them as they are. Sequence and readoutDim are ignored. 4ced567c
- [x] parms2BIDS makes sure that Legacy to BIDS correctly transforms x.Q.Sequence to MRAcquisitionType+PulseSequenceType for old Legacy. And x.Q.readoutDim goes to MRAcquisitionType. This is a one way conversion for backwards compatibility. 4ced567c
- [x] Fix xASL_adm_DefineASLSequence 4ced567c
- [x] Make sure that all possible loading of dataPar/studyPar/ASL.json considers this
- [x] x.Q.Sequence field is removed everywhere and is replaced by the correct use of MRAcquisitionType+PulseSequenceType.
- [x] readoutDim field is removed from everywhere and replaced by MRAcquisitionType. 207ba233
- [x] Update the documentation.

### Testing
- [x] GE TestDataSet not finished
- [x] Unit-Test Check deprecated fields failed
- [x] Flavor Siemens_PCASL_multiSequence_VE11C_1 crashed
- [x] Minor flavor differences
- [x] Rerun flavor test
- [x] Rerun unit test

### Release notes

Stop using Legacy fields Sequence and readoutDim and replace them with BIDS fields MRAcquisitionType and PulseSequenceType

**Comment by jan-petr** [comment]
> ### Description
> Use of x.Q.Sequence is an error-prone legacy thing. This is used in all processing although `Sequence` is complementary to the BIDS fields `PulseSequenceType` and `MRAcquisitionType`.
> 
> PulseSequenceType is actually a general BIDS field. This is read from DICOM and in case it is missing, I am correctly filling this based on other DICOM information. The correct BIDS approach is to have EPI/GRASE saved in PulseSequenceType and 2D/3D in a BIDS field MRAcquisitionType.
> 
> ### Tasks
> I propose to make a new issue where we do the following:
> 
> * [ ]  Make sure that MRAcquisitionType and PulseSequenceType contain the correct information as specified above and that also these are always initialized. This will be done in import.
> * [ ]  parms2BIDS makes sure that Legacy to BIDS correctly transforms x.Q.Sequence to MRAcquisitionType+PulseSequenceType for old Legacy. In new Legacy, x.Q.Sequence won't be present and MRAcquisitionType and PulseSequenceType will be saved to BIDS without any change.
> * [ ]  parms2BIDS of BIDS to Legacy doesn't do anything to MRAcquisitionType+PulseSequence type and keep them as they are.
> * [ ]  x.Q.Sequence field is removed everywhere and is replaced by the correct use of MRAcquisitionType+PulseSequenceType.
> 
> ### How to test
> Optional: insert description about how to test the code changes here
> 
> ### Release notes
> Required: summarize the changes for the release notes here

**Comment by jan-petr** [comment]
{'GE_PCASL_3Dspiral_DV25.0_eASLPLD7_1'             }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-001_1/ASL_1/ASL4D_Source.json'           }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'              }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-001_1/ASL_1/ASL4D_Source.json'           }
    {'GE_PCASL_3Dspiral_DV29.1_1'                      }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub01_1/ASL_1/ASL4D_Source.json'         }
    {'GE_PCASL_3Dspiral_DV29.1_eASLPLD7_1'             }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-001_1/ASL_1/ASL4D_Source.json'           }
    {'GE_PCASL_3Dspiral_HD14.0_WIP_1'                  }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'          }
    {'GE_PCASL_3Dspiral_HD14.0_WIP_1'                  }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub2_1/ASL_1/ASL4D_Source.json'          }
    {'GE_PCASL_3Dspiral_RX28.02_1'                     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub124_1/ASL_1/ASL4D_Source.json'        }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'             }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D_Source.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'             }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_2/ASL4D_Source.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'             }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_3/ASL4D_Source.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'             }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_4/ASL4D_Source.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'             }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_5/ASL4D_Source.json'          }
    {'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'             }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_6/ASL4D_Source.json'          }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_1'         }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub001_1/ASL_1/ASL4D_Source.json'        }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'         }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'     }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PCASL_2DEPI_E11_1'                       }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-38_1/ASL_1/ASL4D_Source.json'            }
    {'Siemens_PCASL_2DEPI_E11_1'                       }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-38_1/ASL_2/ASL4D_Source.json'            }
    {'Siemens_PCASL_3DGRASE_VD13D_1'                   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PCASL_3DGRASE_VE11C_1'                   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub5_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PCASL_3DGRASE_VE11C_3'                   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PCASL_3DGRASE_VE11C_4'                   }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-HQCADPRC0002F0_1/ASL_1/ASL4D_Source.json'}
    {'Siemens_PCASL_3DGRASE_XA20_multiPLD_1'           }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_1'           }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'           }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-1002_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PCASL_3DGRASE_Vida_XA31_SingleMultiPLD_1'}    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'          }
    {'Siemens_PCASL_3DGRASE_Vida_XA31_SingleMultiPLD_1'}    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_2/ASL4D_Source.json'          }
