### ISSUE TITLE
Master issue Population revamp

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1675]
### Description

Fix, clean, and revamp the Population module and "Population" handling.

### Tasks in step 1 (all can be done in parallel)

- [x] Remove outdated x.Q.Sequence field #1674 
- [x] Allow any name for visits #1635 
- [ ] Fix template creation to be less memory demanding #1650

### Tasks in step 2 (all can be done in parallel)
- [x] Redo how PV-masks are used in the population module #1588 

### Tasks in step 3 (all can be done in parallel)
- [ ] Clean code of native space #58 and #1261 
- [ ] Make sure structural module is not partially re-run if not necessary #1634 
- [ ] 4D GetRoiStats #594 

### Tasks in step 4 (are independent of other tasks, can't be done in parallel)
- [ ] #1658 
- [ ] #1669 
- [x] #1680 

### Release notes

Nothing. A master issue.
