### ISSUE TITLE
Reading hematocrit from participants.tsv

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#1680]
### Description

When running ExploreASL('path', 0, 0) – after adding 'hematocrit' column to participants.tsv inside derivatives folder – a warning appears saying that it cannot read participants.tsv

We realized that is was due to this double quoting marks "" in the subject names in the 'participants_id' column

ANOTHER BUG [17-4-2024]:
![image](https://github.com/ExploreASL/ExploreASL/assets/73699072/dfeed2f9-8b6b-4763-b1e1-2d9dc1103127)

### Tasks

- [x] Ensure that the participants.tsv file in derivatives does not add double quotation marks in the participants_id column, when created.
- [x] Check if there are double quotation marks, and remove them if found.
- [x] read x.Q.Hematocrit(iSubjectSession) from x.Hematocrit (from SetsIDs from participants.tsv)

### Release notes

Fix bug in loading and using Hematocrit values.
