### ISSUE TITLE
MRAcquisition not defined for PWI4D.json

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1690]
### Description

PWI4D.json only contains PLD, LabDur, and other basic parameters. We avoid saving all parameters, cause not all JSON parameters for ASL4D are still valid for PWI4D. But the trouble is that when loading all JSON, we runs BIDS2Parms function which runs ASLDefineReadout. And this last function is then missing MRAcquisitionType, PulseSequenceType, and Vendor files. It therefore crashes. We have several options how to fix this.

1.⁠ ⁠Put defineASLReadout where it was initially -> at the start of the ASL module only and not inside BIDS2Legacy JSON conversion.
2.⁠ ⁠⁠Suppress all warnings of missing PulseSequenceType and MRAcquisitionType as these will be bothering us all the time.
3. For PWI4D etc, we will additionally save Vendor, MRAcquisitionType, PulseSequenceType as these are fields that should in theory be there and valid also for PWI4D.

Solution 3 is probably the most optimal as easy and without compromise. So probably my choice. Solution 1 would also work, but you didn't want that. Solution 2 - I don't really like.

HENK:Yes, solution 3 is the most future-proof and won't go wrong if merging different sequences. Ideally, all sequence-dependent parameters are copied from ASL4D.json to PWI4D.json etc. I would just implement this consistently for all relevant parameters that we use in the ASL module, it becomes messy when some parameters are read from ASL4D.json, some from memory, and some from PWI4D. Of course authors, site-name etc don't need copying.

JAN: Yes, lets consistently copy this from a single ASL4D.json location. Just check if in all cases, we provide a reference ASL4D.json to copy from or if we are sometimes saving just PLD/LabDur/TE from memory - then we have to add the reference.
Manufacturer
MagneticFieldStrength
PulseSequenceType
MRAcquisitionType
EchoTime
SliceTiming
FlipAngle
RepetitionTimePreparation
ArterialSpinLabelingType
PostLabelingDelay
BackgroundSuppression
LabelingDuration
### Tasks

- [x] In all cases of ASL subtraction - make sure that those fields above are saved (Manufacturer, MagneticFieldStrength, PulseSequenceType, MRAcquisitionType, ArterialSpinLabelingType)
- [x] Those were already saved (EchoTime, PostLabelingDelay, LabelingDuration)
- [x] These are tricky as they are given per slice and we can't give them per volume if they would differ between two merged sequences (SliceTiming)
- [x] These can in theory be given as vectors, but that would require a new issue (FlipAngle, RepetitionTimePreparation, BackgroundSuppression)

### Release notes

Nothing. Report with #1674
