### ISSUE TITLE
999 lock file always created?

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1693]
### Description

It seems that the 999 lock file is not really used anymore. I'm not sure, but this seemed at least the case for the import module. E.g., when you only run 001_dcm2nii, it also creates 999 at the end of the import module (skipping 002). Then what is the point of 999?

The original function of 999 is that you can skip all submodule checks, by only checking 999 at the start of each module. But the ability to only run submodules (i.e. the case for the import module) somehow makes this a moot point.

### Tasks
- [ ] Equalize modules: either within modules you cannot choose steps (e.g. as with the T1w & ASL modules), or we can choose steps for each module. This would e.g. work like this:

ExploreASL('path', Import [0 0 0], Structural [0 0 0 0 0 0 0 0 (n=9 submodules), ASL [0:n], Population [0:n])

with of course defaulting. This would make some other things easier as well, e.g. the boolean for motion correction would not be required as this would be ASL [1 0 1 1 1 1 1 n]. And the kids don't have to add breakpoints.

- [ ] Only creating 999 if all submodules were run.
- [ ] Skipping a module if 999 exists
- [ ] Running submodule n will remove lock file for submodule n+1 (we have this already)

This should 

HENK NEEDS TO CONTINUE HERE

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
