### ISSUE TITLE
Improve DICOM sorting script

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1696]
### Description

The script for sorting DICOMs to directories needs cleaning and improving (ConvertDICOMStructure_carefulSlow)

### Tasks

- [x] Add an option to dcmtk_Read to skip DCMTK. And use xASL_io_DcmtkRead directly. ad496dc
- [x] Rename the sorting function to a proper name. 3e2441c8
- [x] Clean DCMTK reading and let be errors handled inside the dcmtk_reading function. 3e2441c8
- [x] Add Acquisition Number. 49bdf8a
- [x] Make a recursive function for deleting directories. 49bdf8a
- [x] Allow converting several directories at once. 49bdf8a
- [x] Don't check for values in TE and TR - these are missing in report files. ImageType is present always though. 49bdf8a

### Release notes

Function for sorting DICOMs to directories based on series names.
