### ISSUE TITLE
Minor issues in import and processing

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1702]
### Description

Fix these small bugs in import and processing of the following

### Tasks

- [x] Processing of Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1 - line 366 of xASL_quant_FSL
- [x] Philips_PCASL_2DEPI_5.1.7.2_LookLocker_1 - line 366 of xASL_quant_FSL
- [x] GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1 - import flavor
- [x] Philips_PASL_2DEPI_5.4.1.0_ADNI3_006_S_6681_1 - import flavor
- [x] Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession - import flavor
- [x] Siemens_PCASL_3DGRASE_XA31_multiPLD_2 - import flavor
- [x] Siemens_PASL_2DEPI_VE12U_7T - import flavor
- [x] Siemens_PCASL_multiSequence_VE11C_2 - import flavor
- [x] tokenVisitAliases defined as only empty in sourcestructure.json are ignored.

### Release notes

Nothing. Report with #997
