### ISSUE TITLE
Tumor population analysis

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1705]
### Description

Making sure that the population analysis runs correctly for Ivar with Lesion_T1_1.nii

### Tasks

- [x] Incorrect removal of temporary data.
- [x] Make sure the standard space analysis runs.
- [x] Native space analysis has issues with MRAcquisitionType not found.
- [x] Make sure the native space analysis runs.
- [x] Check that Lesion files are created in native space
- [x] Run stats also on Lesion files -> or create a new issue for that. Will be done in #58 

### Release notes

Transform Lesion and ROI - T1 files into ASL space.
