### ISSUE TITLE
Siemens MOSAIC incorrectly imported

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1707]
### Description

dcm2niix is struggling with import of Siemens MOSAIC images. The worst issue is when the Phoenix field is missing. When at the same time is the ImageOrientationPatient expecting superior to inferior orientation, the output is incorrectly rendered, mirroring the brain above the top of the head.

This special case needs to be detected and mirrored back manually after dcm2niix.

Example is:
Siemens_PCASL_3DGRASE_VE11C_5

### Tasks

- [x] Identify the special case
- [x] Flip the orientation and matrix manually
- [x] Finalize and add the flavor
- [x] Run flavor testing

### Release notes

Deal with mirrored Siemens MOSAIC DICOMs.
