### ISSUE TITLE
Set zeroes outside 3D spiral FoV to NaN

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1711]
### Description

Torstein Torgan (ASL in CO intoxication, Oslo) had a single GE 3D PCASL scan that was acquired misoriented, see below slice. While most of the cortex is still in the FoV, he noticed that there were some negatives included from interpolation artifacts at the edges, which when divided by in M0 division became extreme large values. These originated from artificial zeroes from the GE 3D spiral FoV which is round, not Cartesian, as the FoV stopped there. Usually this is not a concern because those zeroes are well outside the brain but when they are close to the brain, it is essential that they are set to NaN to be masked out. Like SPM ensures that everything outside the original FoV is set to NaN when moving to a different space.

Henk requested the T1w for this example as well, to check if this influences #1039. It did not.

For Henk to check:
/Users/hjmutsaerts/ExploreASL/TestDataSets/GE_3Dspiral_misaligned_LoQ

<img width="292" alt="image" src="https://github.com/ExploreASL/ExploreASL/assets/27774254/5b9bfbc3-56cf-44cb-9f25-924a9ab7f285">

Now this nicely ends up at the correct location, including the missing FoV:

<img width="423" alt="image" src="https://github.com/user-attachments/assets/3c3581bd-a80b-4355-ab80-8975bf12e4e2">

### Tasks

- [x] Very early in the ASL module, set "true" zeroes to NaN (not isnear), for 3D spiral specifically (because with Cartesian the FoV == the reconstruction matrix more or less)
- [x] Add this example to TestDataSets
- [x] Once merged, notify Torstein Torgan

### How to test

- [x] Test this with the new example in TestDataSets

### Release notes

Fix issue with wrongly planned GE ASL scan.
