### ISSUE TITLE
Deployment issue Google Drive for Docker automation & Deploy instructions for V1.12

### ISSUE THREAD

**Issue by maartenhammer** [ExploreASL/ExploreASL#1714]
### Description
As of right now the deployment workflow of the dockerhub release of ExploreASL relies on the compiled MCR version of ExploreASL being hosted on our Google Drive. The script used to scrape this compiled version of Google Drive has broken and now results in the script downloading a HTML-page describing that the file is too big to be automatically scanned by Google, do you want to download anyway? Which needs user input to actually get the proper download. 

For releases after v1.12 the compiled version of ExploreASL should be hosted at an alternative place instead, such as the [releases](https://github.com/ExploreASL/ExploreASL/releases/tag/v1.11.0) section in Github. 

With my departure from ExploreASL the Deployment scripts should also be updated to use someone else's docker account, as mine has been deactivated.

Continuation of #1437

### Tasks

- [ ] Add compiled version of the code in the [releases](https://github.com/ExploreASL/ExploreASL/releases/tag/v1.11.0) section instead of hosting it in google drive
- [ ] Change the `wget ` command in [the docker(hub) file ](https://github.com/ExploreASL/Deploy/blob/master/docker/xasl_base/Dockerhubfile) to fetch the image from the location above instead. Ideally change both files, Dockerhubfile is used by Github Action
- [ ] Update the [Github Secrets](https://github.com/ExploreASL/Deploy/settings/secrets/actions) to new dockerhub credentials as my account has been deactivated and can no longer be used for this.
- [ ] Follow the steps ["How to deploy"](https://github.com/ExploreASL/Deploy/tree/master) when releasing v1.12 to release on dockerhub (change version numbers in the docker(hub) files, and run the dockerhub automation.

### How to test

- [ ] Test if the docker image runs (explained in the [deployment repository](https://github.com/ExploreASL/Deploy/))

### Release notes

None
