### ISSUE TITLE
Implement Bullseye Plot 

### ISSUE THREAD

**Issue by maartenhammer** [ExploreASL/ExploreASL#1715]
### Description

With the inclusion of #1374 in ExploreASL it is now time to create images from them.
For this we could for example use the regions of the brain. 

### Tasks
- [ ] Create a function that generates a value for each plot-segment and put it in an NxM matrix.
- [ ] Call the bullseye function with the this NxM matrix with a datalabel array containing N-Labels matching for example brain regions.
- [ ] Save this to a location in the derivatives folder.

Example of a plot this script delivers:
![image](https://github.com/ExploreASL/ExploreASL/assets/40172631/eb237707-b43d-41ae-a6b1-cb85309bc52f)

Example from BaMoS:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/27774254/235301262-54868ecc-2544-4c0b-b9b9-b8fa1ad6df10.png">
