### ISSUE TITLE
DICOM parameters summary

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1717]
### Description

The DICOM parameters overview created by `xASL_stat_GetDICOMStatistics` in /derivatives/ExploreASL/Population/DICOMparameters was not complete, this function still relied on the old legacy _parms.mat.

### Tasks

- [x] add bUnique as option to xASL_num2str
- [x] xASL_stat_GetDICOMStatistics: initialize the revamping
- [x] Test this with a large dataset
- [x] Revamp fully to our current BIDS nomenclature

### How to test

Tested this with the EPOD dataset, works nicely.

### Release notes

Update DICOM parameter reporting to work with BIDS
