### ISSUE TITLE
Multiple M0 volumes defaults to revPE

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1718]
### Description

M0 with multiple volumes automatically defaults to having an integrated reverse phase encoding. 

Sentence in the middle:
<img width="853" alt="image" src="https://github.com/ExploreASL/ExploreASL/assets/27774254/2fd2999d-4815-499d-8eda-05d3a0608d1c">

This issue was fixed already and the flavor now works normally.

### Tasks

- [x] Switch FlavorDatabase to branch #1718_SEMVIE
- [x] Run `ExploreASL('/FlavorDatabase/SEMVIE', [1 1 0],0);`
- [x] Flavor fixed, tested, added

### Release notes

Nothing to report. Flavor added.
