### ISSUE TITLE
Single-PLD sequence becomes multi-PLD after merging

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1721]
### Description

Currently, we are checking if a sequence is multi-PLD at the start of the ASL module for each session. So for single-PLD sequences that become multi-PLD only after merging, we are setting the multi-PLD aspect to false at the start of the ASL module. And so later on during the quantification, we don't run BASIL by default. This is for example the case of Siemens_PCASL_3DGRASE_VE11C_5.

### Tasks

- [x] We first need to split ASL to ASL and M0 and only afterwards check the ASL image parameters like multi-PLD. While splitting was added as the last section of the config in the ASL module, this really made no sense, because we had to make sure that splitting was done correctly before calculating any further options. Otherwise, we incorrectly thought that there are multi-PLD acquisitions because M0 had a different PLD. The order is now correct. df70ee37
- [x] After splitting ASL to M0 and ASL_source with 8 PLDs, we should move PLD 2:8 to ASL and PLD 1 to M0. But instead, we move PLD 1:7 to ASL. I couldn't reproduce this.
- [x] SaveCBF4D option needs to be rechecked after merging.  ed507f21
- [x] We have a bQuantifyMultiPLD option to set in the config file. And we now use it later as well and adjust based on data. But that means we can readjust this option when needed. So we need to separate the input from data and the real detected value - there's really no way around that cause the first single-session pass always sets it to OFF otherwise. So we need an config value and the really used value. We have discussed this with Henk and new solution is above.
- [x] Put multi-parameter identification to a sub-function. Call it at the start and also after merging. dfced3b6
- [x] Set bQuantifyParameters only later after merging. Make sure none of the parameters is used before. 9c9bf810
- [x] Verify that this works.

### Release notes

Make multi-PLD quantification work even when multi-PLD is created by session merging.
