### ISSUE TITLE
Population stats multisession error

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1723]
### Description

The entire reporting of Stats for multi-session setup is full of bugs. Several things are wrong:

1. In case we have 3 subjects and 2 ASLs. The file with GM volumes then contains 6 lines. But in the case that processing of ASL_1 goes wrong and we only have CBF for ASL_2, then the CBF-stats file contains only 3 lines (ASL_2 for all subjects). But when it adds GM volumes inside, it takes the first three (sub1+ASL1, sub1+ASL2, sub2+ASL1). 
2. The second error is when we have CBF files that are wrong (e.g. have 4th dimension 2 and not 1). That's of course an error, but the Population module should be able to handle that and print "error" on that specific CBF line. Issues 1 and 2 are relevant for TBI data from Ulm.
3. Once we fix that above, we have to check cases where we have for Sub1 CBF1 and 2, but for Sub2 only CBF 1.
4. Once we fix that above, we have to check what happens if we have Sub1 ASL1 and ASL2, but for sub2 only ASL1 (similar to above, but above affects the CBF part and this below affects also the GM volume part). At the same time, we can check scenario that for sub1, we have ASL2 and 3 and for sub 2 only ASL3.

### Tasks

- [x] Fix issue with ASL_1 not having CBF quantified. This is because in printing, we use two different SubjSession indexes. One that goes through all existing ASL sessions (for GM volume part) and one that goes through CBF images (for CBF values). Those two indices differ, but the code was using only the second index for both cases. 9839f7c
- [x] Fix issue with wrong CBF images. This actually crashes in the template creation. So I fixed that template creation is skipped for wrong CBF images and warning reported. And for calculation of CBF mean, we report warning as well and assign N/A to values. 7fb3b437
- [x] Fix issue with missing CBF images. This worked out of the box.
- [x] Fix issue with missing and skipped ASL sessions. This worked out of the box.

### Release notes

Fix population stats printing for missing sessions and CBF images.
