### ISSUE TITLE
Trivial version of mutli-TE multi-TI M0 quantification

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1726]
### Description

DEBBIE (but also other sequences) could have M0 images scanned at multi-TE and multi-TI. This currently will either not work, or it will incorrectly average over those and mess up the quantification.

### Tasks

- [x] Make sure that multi-TI setup for an M0 is identified correctly during the import. d84b1285
- [x] Identify that this is happening in the M0 quantification (and later as well). d84b1285
- [x] Throw away all multi-TE but the first one d84b1285
- [x] Throw away all multi-TI but the last one with the highest TI. d84b1285
- [x] Do the simple single-TE single-TI M0 quantification and make sure the correct parameters are used. d84b1285
- [x] Add RepetitionTimeM0 somehwere in the documentation
- [x] Update all Flavor sequences to use the multi-TI version automatically
- [x] Run all testing

### Release notes

Select optimal TI for multi-TI M0scans.
