### ISSUE TITLE
Automatic reading of DEBBIE parameters

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1727]
### Description

Now added in the flavor description. 

### Tasks

- [ ] Implement Phoenix decoding for DEBBIE
- [ ] Check flavors that have multi-TE M0 and make sure we automatically read it as multi-TE and multi-TI. Because we can do that as we now automatically revert to a single-TI. So we can make the first step of correct import before we continue with a proper multi-TI quantification
- [ ] Test Flavors
- [ ] Test on all DEBBIE and see if we can clean the studyPar.json in all cases
- [ ] Make sure the calculation of the background suppresion works - there was some bug discovered in the calculation process.

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by jan-petr** [comment]
<img width="1048" height="700" alt="Image" src="https://github.com/user-attachments/assets/7acfcee2-243e-4a0b-b2f1-c4a757a7e5e2" />
