### ISSUE TITLE
Bugs found by the EPOD team (Zarah) Master issue

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1731]
### Description

1. When using 11.0Beta, there is a weird transformation field error (y_T1.nii) at the superior end of the MNI space, leading to part of the structural image transformed outside of the brain, the brain itself seems unharmed
2. Not all cases had this, e.g. the follow-up data of the below examples were fine (could also have been different pipeline reruns)

Went wrong in several EPOD cases, 017_1 & 074_1 are good major and minor error examples.
Data are in /home/rnga/zvanderpal/my-rdisk/r-divi/RNG/Projects/epod/ExploreASL_ePOD2/ as mounted on Luna.
Including DataPar, StudyPar en SourceStructure jsons

-       Output xASL pipeline met CAT12: xASL_output_CAT12_OLD.zip
-       Output xASL pipeline met SPM12: xASL_output_SPM_20240624.zip
-       Derivatives map na het runnen van de structurele module met SPM12: derivatives_struc_module_SPM12_20240620.zip
-       Slurm output txt files (pipeline gerund met SPM12): xASL_SPM12_output_txtfiles/
-       Side-by-side vergelijking van de berekende CBF-waarden (met CAT12 vs SPM12): CBF_ROIs_SPM_vs_CAT12_long.csv

Could this be the weird transformation field lines at the edges that we saw before?

### Tasks
- [x] 1. Check which 11.0Beta they downloaded?
   This is 11.0 beta from 12-05-2023, this commit: https://github.com/ExploreASL/ExploreASL/commit/6f1b4a79c8cec443baf1ba23431285dfd4e3c85a.
   They added some atlases/ROIs, which are not super but also not bad.
   When unzipping example "CAT12_OLD", the dataPar.json still contains the old parameters that belong to the data, which may have confused ExploreASL when comparing with the BIDS sidecars? (as per Zarah's comment that "M0 absent" was changed to "UseMeanControlAsM0" or vice versa).

- [x] 2. Try reproducing the error with their 11.0Beta or use the example derivatives
    I cannot reproduce this flowfield error with 1.12.0 Beta.

- [x] 3. Test that we create the final masks now, to verify that the original ROI-wise CBF estimates of Zarah were fine
   The ROIs look fine, using branch #1712 which I now fixed. 
- [x] 4. Using the SPM segmentation derivatives, check why the ASL-M0 registration went wrong
             It seems this was simply a rerun in which a pseudo-M0 (copy of mean_control as this is a dataset without M0 and without Bsup) had an unchanged orientation whereas ASL4D had a changed orientation because e.g. the structural module was repeated and ASL registration was repeated.

- [x] 5. Incorrect registration between ASL and M0
What would a bug then, is that if the structural module affects ASL files, all ASL files need to have their orientation defaulted to mat0 and re-oriented with the new rigid-body alignment at the start of xASL_module_Structural.
I have now addressed this in #1733.

- [x] 6. Still, our pseudo-M0 file management could remain suboptimal, see #1744

- [x] 7. Fix NaNs and erroneous edges transformation flow field: #1039

 
<img width="1161" alt="image" src="https://github.com/ExploreASL/ExploreASL/assets/27774254/cb5498aa-b358-453f-ae2e-7d783d4ba1ab">
<img width="1118" alt="image" src="https://github.com/ExploreASL/ExploreASL/assets/27774254/ca39c1ad-65f5-4a80-83b6-1cf19aedac06">

### Release notes

Nothing. An overview issue.

**Comment by HenkMutsaerts** [comment]
This is an overview issue, all are either fixed or created as todo in another issue.
