### ISSUE TITLE
Flavor Siemens_PCASL_3DGRASE_VE11C_6

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1737]
### Description

See branch flavor-#1737_Siemens_PCASL_3DGRASE_VE11C_6.
This flavor seems to work nicely except for the number of control-label volumes. It has a single M0 (it seems) and then 15 volumes.
Also, I get this warning:
> Warning: The following user-defined/DICOM fields and DICOM-Phoenix fields differ:  SoftwareVersions
Also, it says:
> Phase-encoding direction for reversed-PE M0 is not specified, using the default PA direction.
But there is no separate reversed-PE M0 it seems, and the direction is clearly stated in the DICOM header for ASL.

### Tasks

- [x] Check studyPar.json->ASLcontext
JAN: Flavor fixed and added
- [x] Check warning `The following user-defined/DICOM fields and DICOM-Phoenix fields differ:  SoftwareVersions`
That's what it is :) Complain to Siemens :) 'N4_VE11C_LATEST_20160120' in Phoenix and 'syngo MR E11' in DICOM.
- [x] Check print `Phase-encoding direction for reversed-PE M0 is not specified, using the default PA direction.`

### Release notes

Nothing adding a flavor.
