### ISSUE TITLE
Allow use of brainmask_supratentorial

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1740]
### Description

Provide the possibility to evaluate ROI in the whole brain without the cerebellum using the brainmask_supratentorial.

### Tasks
- [x] Adapt brainmask_supratentorial such that it has the same definition as totalGM.nii
- [x] Create .nii.mat sidecar
- [x] Rename to Supratentorial_GM_WM
- [x] Create bSubjectTissueMask with [GM WM WB] (we could add other tissue types like CSF or WMH that may have certain use cases, or do this later). Fixed by #1753 as x.S.TissueMasking
- [x] Add the atlas as dataPar.json option

Edited the supratentorial atlas:

<img width="419" alt="image" src="https://github.com/user-attachments/assets/82962989-3d01-439a-b9e8-e5fe3fe66dd6">
Added this to the README. The code can be found in CustomScripts.

When merging, check the atlas/ROI moving in #900

### Release notes

Duplicate, nothing to report.

**Comment by HenkMutsaerts** [comment]
I need to understand a bit more before I can help here.
Do you want to have the WholeBrain mask, but then for supratentorial only?
So this is for the total GM?
Then I would call it totalGM_supratentorial.
And we need to have the same brainmask as total GM (the supratentorial mask is a bit narrower).

If this is then only for total GM ROIs supratentorial, this is fine. And for smaller ROIs or WM this is not needed by design.

Note BTW that the cerebellum is already excluded for sequences that have no information there. E.g., for most 2D EPI sequences it is included for the top only, and the 3D sequences do include it. It is a good idea to exclude the cerebellum though for total GM.

One other thing that we need to do is add a .nii.mat sidecar, which ExploreASL can use without having to unzip (keeping the repository unchanged).

**Comment by jan-petr** [comment]
Answers in the PR

**Comment by HenkMutsaerts** [comment]
* Henk was confused: #1740 adds x.P.Atlas.Supratentorial to x.P.Atlas paths in section 6 in  xASL_init_FileSystem, but this doesn’t exist in the develop version, so must be added recently in an unmerged branch? The last 3 issues shown in the 1740 log were already merged, so that cannot be it…
Anyway, this is obsolete as in #900 we added all NIfTIs in the subdirectories of the new atlas maps to x.D.Atlas instead.
* 1740 the supratentorial mask that Henk created was already merged in #900
