### ISSUE TITLE
Resolution estimation

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1747]
### Description

The resolution estimation needs to be revisited inside xASL_init_DefaultEffectiveResolution.m

### Tasks

- [x] Fix code on line 136 of xASL_adm_DefineASLResolution to qnt = sort(imCBF(~isnan(imCBF),'ascend'))) a39081d3
- [x] If AcquisitionVoxelSize is provided, use this value instead of guessing a39081d3
HENK: we need to check that in BIDS this is the effective spatial resolution, not the nominal one
JAN:AcquisitionVoxelSize is the nominal one. So not effective one. But still better than the reconstructed resolution :) We should indeed add those extra effects to the VoxelSize - which we are doing.
HENK2: Nominal can be reconstructed resolution?
JAN2: No, nomimal is defined by acquisition matrix and acquisition FOV. It's close to the acquired voxel size (but not equal to), which might be still different from effective resolution. Reconstructed is what you choose to upsample to - can be kept at nominal, or can be upsampled.

- [x] Input resolutions only for <= 3T, we don't know them for 7T (as blurring in 3D ASL depends on T2, which depends on fieldstrength) a39081d3
- [x] GE resolution lower than 2mm in-plane needs to be adjusted as two times upsampled for 3T sequence. But do this only for 8 spirals. For 4 spirals, the resolution is worse. For no spiral information, we skip this. 5717eefc
HENK: why only lower than 2mm? I would definitely not skip this when not knowing the spiral information, often we don't know the spiral information, this is not a required BIDS field, and with GE we can safely assume that most users have 8 spirals. 80%20% rule: it is better to have better quantification in the majority of the users than to have better quantification in the minority of experts testing something exotic
JAN: Spiral information is saved in 95% of GE DICOMs, so we have this information in nearly all cases. But I'm fine setting the default to 8 when the DICOM info isn't available - added a task below.
HENK2: Great, and we could issue a warning. 99% of all GE data is 8 spirals. BTW: this is in the import right, because it is a BIDS parameter? (we should do data-dependent parameters mostly in import, and only processing settings/choices in the processing, as much as we can)
JAN2: We should be careful in setting unknown things to defaults in import. It is simply unknown and reported unknown, but we shouldn't invent values. Instead, during processing, we can make educated guess, but we can't assume things during import which is supposed to be rigorous. When spiral info isn't known - default to 8 during resolution estimation.  3a4cd7c
- [ ] GRASE - lower resolution than 3mm is fine, we set the threshold to 2mm for 3T and 1.5T but not 7T and we only know these for Siemens
HENK: why? with lower resolution than 3 mm you still have the PSF right?
JAN: The point here is to identify the difference between nominal and reconstructed resolution. GE never has lower resolution than 3mm unless this is a reconstructed resolution by a factor of 2. For GRASE and Siemens, nominal resolution between 2-3mm is not uncommon, so we don't raise any red flags. But when the resolution is below 2mm, then we need to sound the alarm.
HENK2: OK; afaik the nominal resolution IS the reconstruction resolution (at how it is reported and seems to be for many users).
JAN2: No, reconstruction might be equal to acquisition and nominal. but nominal IS NOT reconstruction and IS NOT acquisition. These are 3 distinct terms. Most people report "resolution" and do not care about the difference between them - but that's either simplification, or is true for a particular sequence only, or is plainly wrong. The fact the most people use terms incorrectly doesn't make the terms right and doesn't justify incorrect usage :)
Reconstruction = whatever grid you choose to use for final data display
Nominal = theoretical voxel size based on FOV and matrix
Acquisition = nominal, but taking into account partial Fourier etc.
Effective = taking into account blurring and imperfections etc

### Release notes

Update resolution defaults for GRASE and Spiral sequences.
