### ISSUE TITLE
xASL_stat_GetROIstatistics: create tissue-type choice

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1753]
### Description

Create bSubjectTissueMask with [GM WM WB] (we could add other tissue types like CSF or WMH that may have certain use cases, or do this later).

### Tasks

- [x] In the code, default x.S.TissueMasking at the same location where x.S.Atlases is defaulted, these should match. If TissueMasking is missing or non-matching (because a user uses an old dataPar.json) the user will be correctly notified and hinted on what should be the input.
HENK: Ah, reading your point below I understand what you mean by "backward compatibility", that the input settings are also still compatible. To me, "backward compatibility" is mostly "can you use partly processed data correctly with the new pipeline". Of course, new settings that are unspecified will lead to errors but those will be unknown to the user. I agree that it would be nice to provide an error that x.S.TissueMasking needs to be provided.
JAN: Yes :) The compatibility of partly processed data will be there as well as atlases are only dealt with in the Population module. So that's not an issue. I've updated the description above.
HENK: x.S.Atlases was defaulted at the start of xASL_module_Population, and I have now moved this together with defaulting x.S.TissueMasking to a subfunction of xASL_module_Population, including the user feedback that you propose. Done in c2a0eed625816dd344b8513734221a9985a6cda2.
- [x] x.S.TissueMasking, x.S.bTissueMasking is used inside the GetROI function.
- [x] Replace automatic GM-WM-WB recognition from atlas name to x.S.bTissueMasking
- [x] Add this to the Documentation. Jan can do this, Henk drafted an explanation:
ExploreASL's population module produces ROI values that are obtained by a combination of an MNI ROI atlas with subject-specific GM and WM segmentations. 
In 1.11.0 and earlier versions, xASL_module_Population->xASL_wrp_GetROIstatistics automatically decided if GM, WM, or wholebrain (meaning GM+WM) values should be extracted from an ROI, based on the name of the atlas. It would default to GM values, unless an atlas contained the name WM or WB (wholebrain).
From 1.12.0 onwards, the subject-specific tissue masking is specified by the user, using the parameter x.S.TissueMasking, with option 1=GM, 2=WM, 3=WB (GM+WM).
x.S.Atlases has not changed, but the parameter x.S.TissueMasking should be the same length as x.S.TissueMasking.
When not specified, these default to:
x.S.Atlases = {'TotalGM' 'DeepWM'};
x.S.TissueMasking = [1 2];
JAN: Isn't it better to use string instead of numbers for TissueMasking? Maybe the answer for backwards compatibility issue will be that an error will be reported if Atlases are defined and TissueMasking undefined. So any older version users, will be notified to add the TissueMasking vector. This might be the easiest solution. It might be better than trying to guess TissueMasking from Atlases when TissueMasking would be missing. And the error could sort of provide some nice hints on what to fill and where.
HENK: Changed to strings in 6ca435024689dde2b6495a806334d1fae5bd3be9.
PS: may change 1.12.0 to 2.0.0 with the new license.

### How to test

I tested this in xASL_module_Population and it works. Easiest to visualize test this is by enabling x.S.SubjectWiseVisualization and looking in the population stats Check... folder.

### Release notes

Separate the option for subject-wise tissue masking (x.S.TissueMasking) and ROI atlas selection (x.S.Atlases)
