### ISSUE TITLE
Add ASPIRE contributors to all-contributorsrc

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1763]
### Description

Add Vera Keil and Joost Kuijer to ExploreASL 

in the following file:

https://github.com/ExploreASL/ExploreASL/blob/main/.all-contributorsrc

### Tasks

- [x] Add https://github.com/Vkeil-tech
- [x] Add https://github.com/wadqc
- [x] Vera needs to add a picture to her profile
- [x] Add [Aaron](https://github.com/aot) (Henk asked him through Whatsapp)

### Release notes
Add ASPIRE staff to ExploreASL's README.md
