### ISSUE TITLE
ASL perfusion atlas software

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1768]
### Description

Software that creates Z-score maps

### Tasks

- [ ] Enable creating NIfTIs that are averaged spatially ROI-wise
- [ ] Add output relative CBF (normalized by global (PM: labeling territory) for small ROIs -> rCBF
- [ ] Enable comparison with template ROI-wise
- [ ] This requires global (WB?) intensity scaling
- [ ] Should we also do resolution matching?
- [ ] xASL_stat_GetROIstatistics also keeps the ROI values on a map & creates JPGs of CBF ROI-values

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
