### ISSUE TITLE
Older macOS with bash as default instead of Z-shell

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1772]
### Description

Rik Achten had an issue with `xASL_system` which runs `source .<SHELLTYPE>rc`

### Tasks

- [x] xASL_system: detect shell-type with system('echo $0')
- [x] xASL_fsl_SetFSLdir: add `getenv('FSLDIR')`
- [x] Remove ismac where isunix suffices

### Release notes

Automatic shell and FSL directory detection improved
