### ISSUE TITLE
Add copyright statement

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1778]
### Description

```
% Copyright (c) 2015-2024 ExploreASL
%
% Licensed under Apache 2.0, see permissions and limitations at 
% https://github.com/ExploreASL/ExploreASL/blob/main/LICENSE-EXPLOREASL
% you may not use this file except in compliance with the License.
```

Henk does this with `WorkInProgress/Administration/xASL_adm_ChangeHeaders` after Jan checked the rest in the PR.
This follows #900.

### Tasks

- [x] Base branch on #900 to include `WorkInProgress/Administration/xASL_adm_ChangeHeaders` (so merge #900 first)
- [x] Remove % Copyright lines in subfunctions (copyright is required once per file)
- [x] Add % Copyright lines to WorkInProgress functions
- [x] run xASL_adm_ChangeHeaders
- [x] Rename /Modules/Module_Import/Import -> /Modules/Module_Import/DICOM2NII (including hardcoded lines)
- [x] Jan reviews `xASL_adm_ChangeHeaders` as well as the changes (note that I ran xASL_adm_ChangeHeaders "manually" in stages

COMMENTS JAN:

I have merged 900 and created new 1778 that I have rebased on the new develop.
It wasn't possible to continue with the older 1778 branch, so that was deleted, please only use feature-#1778_CopyrightHeaderRebased
I like all the changes and fixed one or two minor typos.
Single thing I don't like -> the commit https://github.com/ExploreASL/ExploreASL/commit/7a79ac16392579ea6c12ffab20ee1e1b21564b15 . I have now moved this commit as the last one, but it has one major issue - it removes a lot of empty lines. This has two very large problems -> it will create a huge mess with all other issues during merging. Secondly, while removing lines was justified in some cases, for most of the code, it had removed all empty lines and make the code extremely condensed and unreadable.
So if you could remove the last commit and re-run the function with headers without cleaning the empty lines, I'd be happier.
You then have to approve this as I've recreated the branch and PR. I'll merged it afterwards.

COMMENTS HENK
Good catch. The problem was that empty lines were ignored when reading the .m-files. I now fixed this in the last commit. But that means that two commits need reverting so I can add the Copyright statement without removing empty lines. You probably have to cherry-pick, the reason is that the empty lines were also ignored when I added Copyright statements to the WorkInProgress files.

- [x] JAN: rebase and cherry-pick again
- [x]  JAN: revert https://github.com/ExploreASL/ExploreASL/commit/0931798db39765556f5eea02624f6930bfab7943 and https://github.com/ExploreASL/ExploreASL/commit/7a79ac16392579ea6c12ffab20ee1e1b21564b15
- [x]  HENK: Add Copyright to WorkInProgress files
- [x]  HENK: Expand Copyright statements with Apache 2.0
- [x]  HENK: ExploreASL_Initialize: fix adding unexisting folders
- [x]  HENK: ExploreASL_Initialize: fix warnings removing /ExploreASL/SPM folders from the Matlab path

### Release notes

Report with #900
