### ISSUE TITLE
new DCMTK version

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1787]
### Description

There's a new DCMTK version from February 2024, not only it should work better and have a better ASL support, but it should also work on the new MacOS

### Tasks

- [x] main question: doe you mean DCMTK or DCM2NIIX? afaik dcm2niix was never an issue with macOS, only Jan's dcmtk compilation. For Rik, this was somehow an issue, so doesn't hurt to update :)
- [x] JAN pick dataset that Henk tests DcmTK conversion with. JAN: Just try any dataset, any flavor and carefully check if DCMTK throws an error and rolls back to DCMTK or not.
- [x] JAN give address where Henk downloads dcmtk 2024. No need, this is donwloaded and integrated to ExploreASL already.
- [x] @HenkMutsaerts  tests dcm2niix by calling it on DICOMs from commandline (ideally by calling it through system from Matlab) and sees if it works (enough to test if it invokes help screen, but slightly better to test real conversion). -> HENK: I will test real conversion. Rik already tried.
- [x] @HenkMutsaerts Confirms that dcm2niix from 2022 that is included in ExploreASL works with Intel Mac and crashes with M1 Mac. Rik did that already
- [x] @HenkMutsaerts Confirms that dcm2nii from February 2024 (downloaded newly) work with both Intel Mac and M1 Mac
- [x] Once this is done, @jan-petr will initiate the update
- [x] Add new dcm2niix version to ExploreASL
- [x] Update code that 2024 version is taken by default
- [x] Inform Rik
- [x] Run all flavors and check for errors

### How to test

- [x] macARM dcm2niiX 2024 works, dcmtk doesn't work, not compiled yet
- [x] macINTEL dcm2niiX 2024 works, but dcmTk gives the following warning"
       DcmDataDictionary: Cannot open file: /opt/local/share/dcmtk/dicom.d100% -> is this path fixed? Because we 
       assume that users don't have dcmtk installed right? So we cannot point to a shared dcmtk library
- [x] Single-PLD doesn't have M0 PLD as 0 anymore 'GE_PCASL_3Dspiral_DV22.0_1' , 'GE_PCASL_3Dspiral_DV23.1_1'   ,'GE_PCASL_3Dspiral_DV24.0_1','GE_PCASL_3Dspiral_DV25.0_1.5T_1', 'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1', 'GE_PCASL_3Dspiral_RX28.0_multiPLD_1'  
- [x] multi-PLD ignores studyPar values  ,'GE_PCASL_3Dspiral_DV25.0_eASLPLD3_1', ,'GE_PCASL_3Dspiral_DV25.0_eASLPLD7_1'
- [x] Philips - extra Tags
- [x] Philips Lock-Locker messed up
- [x] Siemens_PCASL_2DEPI_VB17A_BSupN_1 - wrong labeling duration
- [x] Siemens extra tags

### Release notes

Required: summarize the changes for the release notes here
