### ISSUE TITLE
TestDataSet

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1788]
### Description

Has several errors that need fixing

### Tasks
- [x] Fix Siemens_PCASL_3DGRASE_VE11C_DEBBIE_2 import on Luna - done in issue #1800 

![image](https://github.com/user-attachments/assets/170a31d2-445b-40fd-afc5-62b3cab0499a)

[BEA: I can't move past the import module because of this bug, but if I just want to re-run the quantification of and LCBC subject with a different T2 value, I added a printscreen below of what is happening. If you have any idea let me know Jan]

- [x] GE_3Dspiral_misaligned_LoQ: It ignores that bUseMNIasDummyStructural is provided. Fixed previously in TestDataSets.
- [x] xASL_stat_GetDICOMStatistics fails in some datasets as there's a wrong struct for printing at the end. 
7a79ac1
- [x] Fix Philips_2DEPI_FLAIR_Segm_PWI4D_Quant_Parameters_LoQ - fixed dataPar in TestDataSets
- [x] Fix Philips_2DEPI_FLAIR_Segm_PWI4D_Quant_Parameters_LoQ - error in TC calculation - dataPar was in second and not miliseconds. Fix in TestDataSet repository.
- [x] Update the Table with new reference values (GE_3Dspiral_misalig)
- [x] Check values against older reference (Siemens3DGRASE_Stru)
- [x] Comparison returns all nans
- [x] Population module tissue masking and atlases done in #1801 
- [x] Run a final test.

### Release notes

Added extra GE TestDataSet.

**Comment by BeatrizPadrela** [comment]
In temp folder, during import, it created a json for ASL_1 but not for ASL_2

![image](https://github.com/user-attachments/assets/5326b2c6-29e6-4b73-9806-a07b2d8d449a)

![image](https://github.com/user-attachments/assets/82734160-32a6-4014-9803-313979911e9b)


so it creates this error:

![image](https://github.com/user-attachments/assets/c89d6d2f-abdc-4815-a07a-387588733867)

I debugged a bit, and it created the ASL.json of ASL_2 it seems, but then it doesn't work again:

![image](https://github.com/user-attachments/assets/66614fdf-34d1-44ea-a0e6-e4bc32876f55)

and then it crashes with this error:

![image](https://github.com/user-attachments/assets/fb98fcfc-9d3a-432d-8c18-526227c0bb76)




(I've added this flavor name in the description of the issue above. I can't do more than import with DEBBIE sequences)

**Comment by BeatrizPadrela** [comment]
If I don't start from scratch and if I just want to re-un quantification (to quantify Tex maps with different T2 value), these are the problems:
[example with LCBC example]

![image](https://github.com/user-attachments/assets/5a52c119-960d-4943-b5fc-b1474ee3abde)

**Comment by MDijsselhof** [comment]
The `xASL_wrp_Population_PrepareAtlas4ROI` crashes. I'm using the normal vascular territories and GM and WM ROIs, nothing else, and all the tissues are segmented and properly registered to the ASL4D. DataPar text: {"x":{"S":{"Atlases":["TotalGM","DeepWM","Tatu_ACA_MCA_PCA","Tatu_ACA_MCA_PCA_Prox_Med_Dist"]}}}

![image](https://github.com/user-attachments/assets/94317230-7531-4aee-835e-7dbbd87c0908)
