### ISSUE TITLE
Add AgeSex2Hct option & hct revamp

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#1797]
### Description

We realized that the function xASL_quant_AgeSex2Hct is not anywhere implemented in ExploreASL:
![Screenshot 2024-09-27 at 15 21 19](https://github.com/user-attachments/assets/c345ac16-867e-43ef-995d-d61d1e609c05)

So, we have agreed (27 September 2024) to add it to xASL_wrp_Quantify, in this part:
![Screenshot 2024-09-27 at 12 31 54](https://github.com/user-attachments/assets/a6b94e03-750f-4e85-9ac7-3073b91c42ce)

### Tasks

- [x] Add xASL_quant_AgeSex2Hct to xASL_wrp_Quantify
- [x] Allow user to disable xASL_quant_AgeSex2Hct
- [x] Move hct parsing to xASL_quant_DefineQuantificationParameters
- [x] CleanUp x.Q at the start of xASL_module_ASL (check that this doesn't hurt stuff)
- [x] Jan adds to documentation: x.modules.asl.bHct2BloodT1. 0 = off, 1== use hct 2==use age & sex. DEFAULT = use hct if exist, use age&sex if exist, otherwise disabled (in this order)
- [x] Add bHct2BloodT1 into parameter loading
- [x] Backwards compatibility is removed, now only hematocrit from participants.tsv -> x.S.Sets* is used

### Testing

- [x] Henk tested with FlavorDatabase/Siemens_PCASL_2DEPI_E11_1

### Release
Improved hematocrit->bloodT1 management, including the ability to infer this from age & sex

**Comment by BeatrizPadrela** [comment]
Just tested it: it doesn't read the age correctly
![image](https://github.com/user-attachments/assets/93ea9509-8d79-49b9-836f-dde49c4234df)

**Comment by BeatrizPadrela** [comment]
It works with Hematocrit!
But the warning is still wrong
![image](https://github.com/user-attachments/assets/9fc2d859-764f-4783-9846-dbac69bfd539)

**Comment by BeatrizPadrela** [comment]
It prints this even without debugging

![Uploading image.png…]()
