### ISSUE TITLE
Atlas ROI expansion based on pvGM & mutual ROI exclusivity

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1799]
### Description

Problem is that some MNI atlas ROIs are thin, which will easily lead to too few voxels included when there is even slight misalignment and pvGM>0.7. We want to optimize this based on the mutual exclusivity of other ROIs and 

Both Jan & Henk agree that we need to mask with pvGM>0.7 for PVC==0
Currently, both PVCs will work with this mask (for a certain Mindboggle atlas ROI):
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/b2b4dec9-c450-4268-b739-52cd75f28f10">

### First suggestion by Henk:
- [ ] 1. Modify the expansion such that we also try to 
a. increase the pvGM content of a ROI — by simply dilating to e.g., a max of 3 dilations, where each dilation needs to add a significant amount of pvGM, so this will depend on the ROI shape and size. We ensure mutual exclusitivity, i.e. we cannot expand into another ROI.
Alternatively, we calculate for each voxel the distance to a ROI, and it gets assigned to the closest ROI. This goes from the assumption that there are other ROIs defined as well, so we still need a max (like a max of 3 dilations in (a), to avoid dilating too much when there is a single ROI.
b. before expanding to try to increase the pvWM content of a ROI — which is also dilating but restricted to WM voxels only (keeping this unchanged)
- [ ] 2. a. CurrentMask is intersected with (pvGM+pvWM)>0.5 instead of pvGM>0.5
b. For xASL_stat_Compute(Mean|SpatialCoV), bPVC==0 will change from imCBF to imCBF(pvGM>0.5)

Example (though you have to think not of a thin pvGM per se (that was my thought mistake) but of thin atlas ROIs.
<img width="976" alt="image" src="https://github.com/user-attachments/assets/2a52afdd-5fb7-4df0-90d6-3247f815f944" />

### Second answers by Jan
1a - I think I know what the confusion probably is. I was talking about segmented GM maps from individual subjects = pvGM. pvGM should be kept at 0.7 for PVC0, 0.5 for PVC2 (or pvGM+pvWM>0.5). But you were talking about GM-ROI from the atlas, which is very wide for some atlases, but very thin for other atlases. That's a different question and we can of course dilate those a bit - that makes sense. However, the thing is that we will anyway mask with pvGM. And while the registration might not be perfect, GM-ROI vs pvGM registration with DARTEL is usually great. So in the end, dilating GM-ROI will not change anything because we will anyway mask with pvGM. But still, if you think that dilate GM-ROI is needed (while keeping pvGM untouched) then I'm fully fine. 

2a - I think we have an agreement on this -> there was a similar confusion between GM-ROI and pvGM>0.7 I guess.

HENK: Yes. So the dilations are based on adding significant pvGM. This indeed won't do much if there is no misalignment, but there's always some non-linear misalignment. Think of the misalignment between-subjects.

Last comment - I've added this issue to #1845 so that we avoid conflicts... So lets answer here, but during implementation follow the plan in #1845 

### Tasks

- [ ] Implement _xyz_ in function `xASL_[abc]_...`

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
