### ISSUE TITLE
Small ROIs

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1813]
### Description
Some warnings & disclaimers

### Tasks

- [x] 1. Add a disclaimer that we are not liable for processing errors, to README
- [x] 2.⁠ ⁠Add a warning or note that ROIs smaller than 1 mL are not calculated to avoid publication of spurious findings, name of this ROI, but that these can be enabled
- [x] 3.⁠ ⁠Add x.S.MinimalROIVolume
- [x] 4. Output the name of the current ROI?
- [x] Update WorkflowUpdate.png: remove BIDS2Legacy from import
- [x] Add new funders to README.md
- [x] @jan-petr Add x.S.MinimalROIVolume to documentation
- [x] Add disclaimer also at end of processing
- [x] If the user inputs a single Atlas, convert this to cell

### Release notes

Improve processing explanations to the user in the population module
