### ISSUE TITLE
GE import minor confusions

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1816]
### Description

- [x] If you don't provide a studyPar.json file for GE ASL (which should have most parameters), it doesn't find PLD but mentions that there is a difference between the "studyPar.json" PLD and the DICOM inversion time.
How is this possible?
JAN: Done in #1516. It merged dcm2nii and studyPar values and then thought dcm2nii is the studyPar version :)
- [x] While EchoTime and PLD correctly get two values in *_asl.json and ASL4D_Source.json, this is not done for LD; shouldn't LD also always be created as a vector?
JAN: If the values don't differ, provide only a single value - per BIDS definition. For TE, this should be a single value. For LD, it indeed should give 0 for M0. Fixed in #1898 
- [x] When splitting ASL4D_Source -> ASL4D.json & M0.json in BIDS2Legacy, PLD is nicely split (though it is not mentioned in M0.json, which might be correct?), this is not the case for TE; TE keeps 2 values in ASL4D.json & M0.json. Fix in #1898 
- [x] GE doesn't provide the `TotalAcquiredPairs` in the DICOM it seems? Should we be able to calculate the acquisition duration from the DICOMs? Because we know approx how long a single control-label acquisition takes for this sequence. This could be a nice to have, again limiting our user questions. The same goes for other sequences, the number of repeats/dynamics could be calculated. 
- [x] If the studyPar.json doesn't contain the M0type, but it contains `"ASLContext":"deltaM,M0scan"`, then in rawdata M0Type becomes absent... Done in #1898 
- [x] Make ASLcontext case insensitive in import->NII2BIDS (interpreting studyPar.json)... Done in #1898 
- [x] Make ASLcontext case insensitive in processing->BIDS2Legacy (interpreting ASLcontext)... Done in #1898 
- [x] Likewise, the BIDS validator states that this volume type inside the TSV is incorrect (though the error message seems inconcistent):
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/752703b5-0119-47d5-ad39-a10ccc3759c5">
This then leads to `x.modules.asl.M0PositionInASL4D` being empty, and the M0 file is not split, also leading to problems with PLD, TE, etc having too many values (2) and crashing xASL_module_ASL.
The issue seems to be the case sensitivity of ASLcontext (also in the bids validator); while this is perhaps correct, this can lead to users contacting us for not being able to process the data; so I suggest that we make ASLcontext in all stages case insensitive

- [x] Start of xASL_module_ASL should read ASLcontext instead of relying on `x.modules.asl.M0PositionInASL4D`. Yes we already plan this in #1020 
- [x] Test in `/FlavorDatabase/GE_PCASL_3Dspiral_DV29.1_2`, branch `bug-#1816_GE_product_import`, dataset provided by Miguel (Jan is CCed in recent e-mail chain)
- [x] Check issue #1730

### Release notes

Nothing. An overview issue.
