### ISSUE TITLE
Nifti import doesn't work without JSON

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1825]
### Description

If JSON is missing when trying to import NII, then it crashes.

### Tasks

- [x] Allow missing JSONs for anat files
- [x] Allow missing JSONs for perf files
- [x] Handle missing JSON parameters for ASL
- [x] Test and update flavor Siemens_VE11_NiftiOnly_1

### Release notes

Allow NIfTI import without JSON.
