### ISSUE TITLE
Temporal variability of a metric in the ASL QC module

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1828]
### Description

In general, we want to be able to take features from the PWI4D image (such as CBF or spatial CoV) per deltaM, and output their variance/SD/MAD.

As a use case, we take the pvGM>0.7 spatial CoV of each deltaM of the PWI4D.nii and output its sCoV.

In standard space, we have this feature in #594.

### Tasks

- [x] Always save CBF4D in quantification for single-PLD and single-TE  0670e96e
- [x] Create new function in xASL_wrp_VisualQC_ASL, between step 8 and 9. JAN: I added it to step 9 as it already deals with CBF and masks, so best to keep this unified and together.  0670e96e
- [x] Calculate mean, median, spatial sCoVfor each subtraction repetition from PWI4D. Using pvGM>0.7.  0670e96e JAN: diffCoV 
- [x] Calculate diffCoV. JAN: Note that diffCoV requires spatial relations and thus cannot be calculated on masked images like is done for GM. So I had to use the original images before masking. 86a8c775
- [x] I calculated temporal SD over GM and WM in CBF. and temporal mean and SD in ScoV - the normalization can be done afterwards.
- [x] delete CBF4D after the end of ASL module unless save CBF4D is specified fe0e7457

### How to test

temporal sCoV -> do we want to exclude the cerebellum?
Also, we should actually include the CoW; so for now perhaps the full brain (pGM+pWM) works best.

<img width="560" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/6fd95016-56bb-426b-9afb-4847ff411a3c">
<img width="558" alt="Pasted Graphic 1" src="https://github.com/user-attachments/assets/3a0ccb91-27c3-4ad9-9a18-3c46fa2f14db">

### Release notes

Report sCoV in QC based on CBF4D

**Comment by HenkMutsaerts** [comment]
Create new function in xASL_wrp_VisualQC_ASL, between step 8 and 9

**Comment by HenkMutsaerts** [comment]
x.Output.ASL.(x.SESSIONS{x.iSession}).<NAME>
x.Output.ASL.(x.SESSIONS{x.iSession}).<NAME> = NaN

**Comment by HenkMutsaerts** [comment]
x.Output.ASL.(x.SESSIONS{x.iSession}).deltaM-[parameter]_temporal-[parameter]
