### ISSUE TITLE
Temporal variability in population module

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1831]
### Description

We want to run the temporal variability stats that we defined in #1828 in `xASL_qc_CollectQC_ASL` also in the population module, because I will generate a new NIfTI mask that has both the supratentorial WB mask and the Circle of Willis.

### Tasks
- [x] Cherry pick from #594 and remove it there 7808fb23
- [x] Load data 4D 7808fb23
- [x] inside Population module, inside native space analysis, when SaveCBF4D is on (so that we have CBF4D.nii in the native space) we calculate 4D stats 7808fb23
- [x] Using any atlas provided in dataPar.json and called for population analysis. Move it to the native space and get the same temporal variability etc. parameters as defined in xASL_qc_CollectQC_ASL, but then within this mask 
-> HENK: I thought of doing this in a separate function, because otherwise all the ROIstats calculations have to accommodate an extra dimension (for 4D instead of 3D, add the different ROIs etc, so multi-dim, so quite an overhaul of the ROIstats functions, which I started in #594 but will create much extra work. And we want to change the native space stuff. So I thought easiest for now is to create a function separate from GetROIstats and do this all there, but you can also do it with GetROIstats, but then please create separate sections or subfunctions for this . 7808fb23
- [x] If CBF4D image is found, then it will do all analysis (all atlases and all contrasts like scov and CBF) in native space in 4D
-> I meant in 3D per deltaM, so it will do it nDeltaM times, and then after we take the mean/median/sCoV of these parameters, like in #1828
-> HENK: note that  this has to be per deltaM calculated, and then the temporal mean or SD of that. So 1. spatial 2. temporal function (not the other way around). 11005589
- [x] We calculate spatialCoV4D and diffCoV4D over an atlas from MNI transformed to native space per 1 deltaM. From that, we take mean/median/SD.
-> for each deltaM separately indeed, so we calculate spatialCoV3D and diffCoV3D for each deltaM separately, and then get the mean/median/SD etc over those nDeltaM spatialCoV3D's etc. 11005589
- [x] Fix calculate sptialCoV function to work in 4D

- [x] 1. Add function for within-mask calculation of the Z-direction center-of-mass (slice with the average label position: first take average of each slice within the mask, then the center-of-mass across the Z-direction); center-of-mass is the "intensity-weighted center", so not the geometric center (for which you would binarize first).
- [x] Case A) Function (1) is performed per deltaM, and the temporal SD and mean are calculated of this. JAN: Called LabLoc4D_mean and LabLoc4D_sd. I've additionally did the same for sCoV- first calculate per slice/repetition, then center per repetition, then mean/sd over repetitions.
- [x] Case B) Temporal SD is first calculated voxel-wise and function (1) is ran after it. JAN: I calculated temporal SD voxelwise, then slice-wise mean and weighted-slice-mean. Called StdLoc4D.
- [x] xASL_stat_ComputeDifferCoV doesn't work in the current implementation, the input arguments don't correspond. JAN: Fixed, minor error in the header that I forgot to update.
- [x] HENK: I did the following changes in my last commit for xASL_stat_GetROIstatistics:
* Some calculations do not need the second dimension because they already had 1 dimension
* Also initialize sCoV4D_SliceWise & tempSD4D_SliceWise (this fixes a bug if different subjects have different FoV/nSlices)
* do not set NaNs to zeroes (to avoid bias), though we may want to improve vectorSlice such that it doesn’t take slices that only contain NaNs
* flip negative values by abs() instead of setting them to 0
* Add new parameters to output
* renamed 
mean4D -> mean4D_SliceWise
sCoV4D -> sCoV4D_SliceWise
tempSD4D -> tempSD4D_SliceWise
vecSlice -> vectorSlice
mean4Dcenter -> mean4DcenterSlice
sCoV4Dcenter -> sCoV4DcenterSlice
x.S.DAT_LabLoc4D_mean_PVC0 -> x.S.DAT_LabelSliceLocation4D_tMean_PVC0
x.S.DAT_LabLoc4D_sd_PVC0 -> x.S.DAT_LabelSliceLocation4D_tSD_PVC0
x.S.DAT_sCoVLoc4D_mean_PVC0 -> x.S.DAT_LabelsCoV_SliceLocation_tMean_PVC0
x.S.DAT_sCoVLoc4D_sd_PVC0 -> x.S.DAT_LabelsCoV_SliceLocation_tSD_PVC0
x.S.DAT_StdLoc4D_PVC0 -> x.S.DAT_SlicetSD_SliceLocation_PVC0

### Release notes

New population statistics on CBF4D data.

**Comment by HenkMutsaerts** [comment]
Looks very nice! I commented on things that seemed to change 1 commit later, so perhaps not all my comments need answering. I wonder if we cannot do it in such a way that we always calculate stuff in 4D, which will just give a single value for non-4D (same philosophy as always calculating PWI4D even for single-PLD single-TE) to keep simple code.
