### ISSUE TITLE
Motion correction for multi-PLD and multi-TE goes wrong

### ISSUE THREAD

**Issue by rikAchten** [ExploreASL/ExploreASL#1833]
### Description

Similarly to control vs label images, images acquired at different PLD or TE will differ because of different TR after saturation, different amount of labeling inside, or different contrast because of different TE.
So if we perform motion correction, we need to be sure that it correct for motion and doesn't try to overcompensate for expected signal differences.

In DEBBIE sequence, This is mostly a problem for different TEs: they produce very different contrast leading to artificial estimated motion. For Time-encoding -> this doesn't generate large false motion. See images below for HAD4 and HAD8

<img width="999" alt="image" src="https://github.com/user-attachments/assets/99abecb8-c664-427e-9385-d232876a5f68">
This image shows for control and 3 PLDs and 8 TEs (DEBBIE FME HAD4, here still Hadamard encoded) that the assumed position change based on intensity-based alignment incorrectly thinks of pseudo-motion due to echo time changes.

Below the same for DEBBIE FME HAD8: single TE 7 PLDs & 1 control, two repetitions
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/b0df7cce-731c-4355-b433-2101735ba469">

### Tasks

- [x] During motion correction, identify multi-TE acquisition, time-encoded acqusition, multi-PLD without time-encoded, or standard acquisition.
- [x] For multi-TE: Perform motion correction only on the shortest TE. Turn of Zig-zag. Register to first image. Apply estimated motion in shortest TE for the other TEs within the same block.
- [x] For Time-encoded: Turn off Zig-zag. Register to first image. Perform normal motion correction as the images have the same TR.
- [x] For simple multi-PLD (without multi-TE and without time-encoding): Use Zig-zag. Register to first. For each PLD - register the images to the first for that PLD. Do not register across different PLDs
- [x] For standard acquisition. Use Zig-zag, register to mean. The standard way.
- [x] For multi-TE and multi-PLD - make sure the estimated parameters are put together correctly and saved to TXT and NII files as if a normal  motion correction would be executed. That means -> we only change the motion estimation and don't have to change any of the other functions.
- [x] Functions for calculating mean motion and plotting motion are moved to a sub-function for readability.

### How to test
Corrected version - see how motion doesn't change across TEs, but only between blocks.
<img width="875" height="656" alt="Image" src="https://github.com/user-attachments/assets/d1b235fe-8d62-41a3-b5c6-ce97994adecc" />

### Release notes

Fix multi-TE motion correction.
