### ISSUE TITLE
Sync ASL->T1w registration for merged ASL sessions/runs

### ISSUE THREAD

**Issue by rikAchten** [ExploreASL/ExploreASL#1834]
### Description

Each ASL session/run is independently registered to the T1w, which is perhaps correct for separate (different) ASL sequences, but incorrect for two ASL sessions/runs that need to be merged.

### Tasks

- [ ] Keep registration ASL->T1w for each session, don't change this
- [ ] if bMerged==true, after registration, for all filenames that are equal between ASL_1 & ASL2, average their orientations
       (because we cannot only do this for ASL4D.nii, there are other dependent files)
- [ ] Improve the clean up such that the merged PWI4D_ASL1_ASL2 etc is deleted if we rerun the merging part

### Release notes

Duplicate. Solved in #2048
