### ISSUE TITLE
Create supratentorial+CoW brainmask

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1838]
### Description

The goal is to have both the brain parenchyma and the Circle of Willis, as an template in standard space. We store this in the same folder as the MaxVesselTemplate.

### Tasks

- [x] Create VascularMasking script in CustomScripts/Vascular*/
- [x] Make CustomScripts private
- [x] Add masks
- [x] Add .tsv sidecars containing the mask names (same as filenames)

### Release notes

Adding supratentorial atlases without subcorted and with the Circle of Willis.
