### ISSUE TITLE
Master issue native space atlas dealing stuff/xASL_stats_GetROIstatistics

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1845]
### Description

Atlas dealing stuff/xASL_stats_GetROIstatistics

### Tasks

- [x] Add new functionality to #1831 HENK: this is done right?
- [x] HENK: Jan reviews Henk's last changes to #1831:
I checked the diff with what I did in my dirty branch for the abstract, added it as last commit (also 1 small commit on xASL_wrp_GetROIstatistics) and described my changed to xASL_stat_GetROIstatistics in the last issue task of #1831. Can you check and approve? Then we can merge #1831.
- [x] Review & merge #1838 (no documentation to be added, this is for internal use, we don't want to advertise our vascular distality idea)
- [x] Check Henk's review for #1826 (Henk is fine with the question in the issue)
- [x] Check Henk's points in #1844 & decide which should go to #1826 already, or keep them in #1844
- [x] Merge #1826
- [x] Review #1844 (not a PR, this is a messy branch that will not be merged, at least not for now)
- [ ] Do #1849 
- [ ] Do #594 
- [x] Fix #249 
- [x] #1588 
- [ ] Fix #58 
- [ ] #1799 

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here
