### ISSUE TITLE
xASL_quant_BSupCalculation crashes with ReadoutTime as vector

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1848]
### Description

I found a few issues, the main one being this crash with ReadoutTime being a vector.

### Tasks

- [ ] warn the user that this is still under development
- [ ] why does it check for the existence of M0_Check.jpg (PathGraph on line 105) rather than checking the existence of the M0 in general?
- [ ] line 108: ReadoutTime should be max(ReadoutTime) for the initialization of the timecurve SignalPercentageVector?
- [ ] likewise in the rest of this function, when ReadoutTime is a vector, the function crashes. Can you easily make this robust for multiple ReadoutTimes, e.g. in this use case you could do unique(ReadoutTime) and issue a warning if that has multiple elements?
- [ ] Note that the path where you save (/Population/M0Check.jpg) should be renamed, I suggest storing it in the M0Check folder, and calling it <SUBJECT><SESSION>meanControl_BsupCalculation or something similar

### How to test

Found these bugs with `FlavorDatabase/Siemens_PCASL_3DGRASE_XA31_DEBBIE_1`

### Release notes

Required: summarize the changes for the release notes here
