### ISSUE TITLE
AAL3 and WMPM atlases

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1855]
### Description

Add a script that coregisters an atlas from ICBM152 into IXI.
Add two new atlases

### Tasks

- [x] Add script that co-register the atlas from ICBM152 to IXI512
- [x] Co-register and transform the atlases 
- [x] Add atlases
- [x] Add license AAL3 (GNU) -> HENK: I cannot find the AAL3v2 package, which contains the exact license text. But it is standard GPL so it is fine for now.
- [x] Add TSV for AAL3 & convert LeftRight->Bilateral
- [x] Add license WMPM
- [x] Add TSV for WMPM & convert LeftRight->Bilateral
- [x] Jan adds a summary of the registration he did to the details.txt sidecar
- [x] Nico check visually if the final atlas is OK
- [x] Jan: Add to manual
- [x] Henk: transpose all atlas TSV's (columns to rows) so they are easier to read: done in #1869 (requires merging this issue first)

### How to test

Visualization overlay: there seems to be slight misalignment still, we can keep this but need to check that we implement a ROI-growing algorithm that keeps ROIs mutually exclusive, accounting for the individual GM mask

/ExploreASL/External/SPMmodified/toolbox/cat12/templates_volumes/Template_6_IXI555_MNI152.nii.
![image](https://github.com/user-attachments/assets/d516c8ba-1879-47d4-82ef-43850add785b)
![image](https://github.com/user-attachments/assets/0372169a-115d-4b57-b22c-f0779155627a)
![image](https://github.com/user-attachments/assets/f1250c75-a701-4b00-9255-29048e4c796b)

### Release notes

Add WMPM Type III and AAL3v3 atlas

**Comment by jan-petr** [comment]
[AAL3_UserGuide_April2024.pdf](https://github.com/user-attachments/files/18203521/AAL3_UserGuide_April2024.pdf)
[AAL3v1_1mm.nii.TXT](https://github.com/user-attachments/files/18203524/AAL3v1_1mm.nii.TXT)

**Comment by jan-petr** [comment]
[AAL3v2_for_SPM12.tar.gz](https://github.com/user-attachments/files/18228054/AAL3v2_for_SPM12.tar.gz)
