### ISSUE TITLE
Follow up of issue 900 for fixing atlases & supratentorial

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1858]
### Description

This issue solves some follow-up work after #900. Some of this was planned in #1740 which was outdated.

### Tasks

- [x] Create Atlases4ROIs/LicensePermissive/SPM_CAT_GPL/README.md from old ROI location
- [x] Remove TotalWM, this is the same as WholeBrain but was used for WM, this is now obsolete with x.S.TissueMasking

We use TotalGM.nii:
1. Comparison/ReferenceValues
2. xASL_qc_SortBySpatialCoV
3. All users are used to having TotalGM output; renaming this to WholeBrain_GM will confuse them

We don't really use WholeBrain.nii. We can keep it for now, and remove it later.

Easy suggestion:
Renaming TotalGM.nii -> Total.nii
Output name should then instead of Total_GM be TotalGM, and the rest stays the same

- [x] Upon loading atlases and finding TotalGM or TotalWM, replace this by x.S.Atlas = 'Total' & x.S.TissueMasking = 'GM' or 'WM'
HENK: so I now fixed that it always adds the TissueMaskingLocal{1} to the ROI name.
E.g.,
ROIname = Total
TissueMasking = GM
-> TotalGM
ROIname = DeepWM
TissueMasking = WM
-> DeepWMWM
ROIname = Supratentorial
TissueMasking = WM
-> SupratentorialWM
ROIname = Hammers
TissueMasking = GM
-> HammersGM

so only for DeepWM this now is DeepWMWM so needs some changes in our testing code etc, but otherwise this seems most optimal

### Docu tasks
@jan-petr Do you need to update the documentation based on these changes and the changes in #900?
JAN: Yes, definitively, please list the tasks and I will do them before merging.
HENK: OK. Task = add #900 changes and #1858 changes to the documentation :)

- [x] Verify the paths to atlases in the manual
- [x] Remove TotalWM 
- [x] In the example cases, talk about Total + WM as a replacement for the total WM. This shouldn't be a problem since we have the basic atlas as DeepWM.

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Nothing. Report with #900, #1740
