### ISSUE TITLE
Minor feedback improvement for bUseMNIAsDummyStructural

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1862]
### Description

Minor feedback improvement for bUseMNIAsDummyStructural. Some users keep this option enabled. They should be aware that if some subjects don't have a structural module yet processed, it will continue processing ASL data with dummy MNI images. If you then reprocess modules or something else, this can potentially lead to registration issues as the NIfTI orientation matrix is not always restored upon rerunning.

### Tasks
- [x] xASL_module_ASL: improve bUseMNIAsDummyStructure feedback
- [x] xASL_wrp_RegisterASL: improve bUseMNIAsDummyStructure feedback
- [x] Good practice with rerunning is first deleting the derivatives folder, perhaps we can also add a warning or something for this somewhere

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Improving user feedback with bUseMNIAsDummyStructural
