### ISSUE TITLE
Flavor import error

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1866]
### Description

Many flavors don't work

### Tasks
- [x] Assign atlas defaults in population module only 6657f40f
- [x] Fix atlas entry in dataPar.json - fixed 4 flavors
- [x] Dataset `Siemens_PCASL_2DEPI_XA20_1` has an extra field "PostLabelingDelay_1"

### How to test
- [x] Run full flavor test

### Release notes

Minor fix. Report with #1801
